{
  "hash": "c95c1bab1950e06946198136605d053e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regresión Bayesiana\"\nsubtitle: \"Modelos de regresión lineales y no lineales, evaluación de modelos y predicciones\"\nauthor: \"Alfredo Sánchez Alberca &nbsp; [{{< fa envelope >}}](mailto:asalber@ceu.es) [{{< fa brands linkedin >}}](https://www.linkedin.com/in/asalber/) [{{< fa home >}}](https://aprendeconalf.es)\"\nlogo: img/logos/sticker-estadistica-bayesiana-r.png\n# title-slide-attributes:\n#     #data-background-color: black\n#     data-background-image: img/prompt-julia.pngr\n#     data-background-size: contain\nfig-align: center\nfilters:\n  - arrows\nlang: es\n---\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n::: {.cell}\n\n:::\n\n\n## {background-color= .myblue}\n\n:::{.main-title}\nRegresión lineal simple\n:::\n\n## Modelos de regresión\n\nEn Estadística se utilizan  _modelos de regresión_ para describir la relación entre una variable dependiente $Y$ y una o varias variables independientes $X_1, X_2, \\ldots, X_n$.\n\nEn el caso de una sola variable independiente, se habla de _regresión simple_, y el modelo se expresa como\n\n$$\nY = f(X) + \\varepsilon,\n$$\n\ndonde $f(X)$ es una función de $X$ que describe la relación entre $Y$ y $X$, y $\\varepsilon$ es un término de error que refleja la variabilidad de $Y$ que no se explica por $X$, y que se asume que sigue una distribución normal con media cero y desviación típica $\\sigma$,\n\n$$\n\\varepsilon \\sim \\mathcal{N}(0, \\sigma).\n$$\n\n## Diagrama de dispersión\n\nPara analizar la relación entre dos variables cuantitativas, debemos estudiar la variabilidad de la distribución conjunta de las dos variables. Esta variabilidad conjunta se suele representar gráficamente mediante un _diagrama de dispersión_. Un diagrama de dispersión se representa sobre unos ejes cartesianos, donde el eje $X$ normalmente representa la variable independiente, y el eje $Y$ representa la variable dependiente, y por cada par de valores $(x_i,y_j)$ en la muestra se dibuja un punto en el plano con esas coordenadas.\n\n:::{.content-visible when-format=\"html\"}\n![Diagrama de dispersión.](img/04-regresion-bayesiana/diagrama_dispersion){width=500}\n:::\n\n---\n\n:::{#exm-diagrama-dispersion}\nEl conjunto de datos [`peso-estatura`](https://aprendeconalf.es/estadistica-bayesiana-presentacion/datos/peso-estatura.csv) contiene el peso y la estatura de una muestra de 200 personas mayores de 18 años. El siguiente código muestra el diagrama de dispersión de peso frente a estatura.\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\ndf <- read_csv(\"datos/peso-estatura.csv\")\nggplot(df, aes(x = estatura, y = peso)) +\n  geom_point(color = myblue) +\n  labs(x = \"Estatura (cm)\", y = \"Peso (kg)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n:::\n\n## Tipos de modelos de regresión simple\n\nLa forma de la nube de puntos en el diagrama de dispersión nos da una idea de la forma de la función $f$ que describe la relación entre $Y$ y $X$.\n\n![Tipos de regresión simple.](img/04-regresion-bayesiana/diagrama_dispersion_tipos_relaciones){width=500}\n\n## Regresión lineal simple\n\nCuando $f$ es una recta, se dice que el modelo es un modelo de _regresión lineal simple_, y se expresa como\n$$\nY = \\beta_0 + \\beta_1 X + \\varepsilon,\n$$\n\ndonde $f(x) = \\beta_0 + \\beta_1 x$ es una una recta que expresa la relación lineal entre $Y$ y $X$, y $\\varepsilon \\sim N(0, \\sigma).$\n\nPara cada valor $x_i$ de la variable independiente, el modelo de regresión lineal simple asume que la variable dependiente $Y$ sigue una distribución normal con media $\\mu_i = \\beta_0 + \\beta_1 x_i$ y varianza $\\sigma$.\n\nLa relación lineal queda determinada por dos coeficientes:\n\n- **Término independiente $\\beta_0$**. Es la media de $Y$ cuando $X=0$.\n- **Pendiente $\\beta_1$**. Es el cambio que experimenta la media de $Y$ por cada unidad que se incrementa $X$.\n\n## Regresión lineal en Estadística frecuentista\n\nEn Estadística frecuentista, el modelo de regresión lineal simple se estima a partir de los datos utilizando el método de los mínimos cuadrados, que consiste en encontrar los valores de $\\beta_0$ y $\\beta_1$ que minimizan la suma de los cuadrados de las diferencias entre los valores observados $y_i$ y los valores predichos por el modelo $\\hat{y}_i = \\beta_0 + \\beta_1 x_i$.\n\nEsto da lugar a la famosa fórmula de la recta de regresión lineal simple:\n\n$$\ny = \\bar{y} + \\frac{\\sigma_{xy}}{\\sigma_x^2}(x-\\bar{x}),\n$$\n\ndonde $\\bar{x}$ y $\\bar{y}$ son las medias de $X$ e $Y$, respectivamente, $\\sigma_{xy}$ es la covarianza entre $X$ e $Y$, y $\\sigma_x^2$ es la varianza de $X$, es decir,\n\n$$\n\\beta_0 = \\bar{y} - \\beta_1 \\bar{x} \\quad \\text{y} \\quad \\beta_1 = \\frac{\\sigma_{xy}}{\\sigma_x^2},\n$$\n\nson dos estimaciones puntuales.\n\n\n## Ajuste de modelos de regresión con R\n\nEn R existen varias funciones para ajustar modelos de regresión lineal. Las más habituales son:\n\n- `lm()`. Se utiliza para variables dependientes continuas con distribución normal. Ajusta un modelo de regresión lineal utilizando el método de los mínimos cuadrados ordinarios.\n\n- `glm()`. Se utiliza para variables dependientes con distribuciones de la familia exponencial: normal, binomial, Poisson, gamma, etc. Ajusta un modelo de regresión generalizada utilizando el método de máxima verosimilitud (minimiza la log-verosimilitud).\n\n## Ajuste de un modelo de regresión lineal simple con `lm()`\n\n:::{.callout-note}\n## `lm()`\n\nRealiza un ajuste de un modelo de regresión lineal utilizando el método de los mínimos cuadrados ordinarios.\n\nParámetros:\n\n- `formula`: fórmula que especifica el modelo de regresión lineal a ajustar.\n- `data`: conjunto de datos que se utilizará para ajustar el modelo de regresión lineal.\n:::\n\nConviene recordar que la fórmula para especificar un modelo de regresión en R tiene la siguiente sintaxis:\n\n```r\nvar_dependiente ~ var_independientes\n```\n\ndonde las variables independientes en modelos de regresión múltiple se pueden combinar con los operadores\n\n- `+` para incluir varias variables independientes sin interacción.\n- `*` para incluir varias variables independientes con interacción.\n- `:` para incluir sólo la interacción entre varias variables independientes.\n\n---\n\n:::{#exm-regresion-lineal-simple-frecuentista}\nRecordemos el ajuste de un modelo de regresión lineal simple del peso sobre la estatura utilizando el método de mínimos cuadrados con la función `lm()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(broom)\nlibrary(knitr)\nmodelo_lineal <- lm(peso ~ estatura, data = df)\ntidy(modelo_lineal) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|term        |   estimate|  std.error| statistic|   p.value|\n|:-----------|----------:|----------:|---------:|---------:|\n|(Intercept) | -59.675687| 17.1130556| -3.487144| 0.0006014|\n|estatura    |   0.770071|  0.1003361|  7.674912| 0.0000000|\n\n\n:::\n:::\n\n:::\n\n## Ajuste de un modelo de regresión lineal simple con `glm()`\n\n:::{.callout-note}\n## `glm()`\nRealiza un ajuste de un modelo de regresión generalizada utilizando el método de máxima verosimilitud.\n\nParámetros:\n\n- `formula`: fórmula que especifica el modelo de regresión generalizada a ajustar.\n- `family`: familia de distribuciones del error aleatorio en el modelo y de la función de enlace.\n- `data`: conjunto de datos que se utilizará para ajustar el modelo de regresión generalizada.\n:::\n\nDonde la familia de distribuciones `family` puede ser cualquiera de las siguientes:\n\n| `family` | Variable dependiente | Función de enlace | Uso típico |\n|---|---|---|---|\n| `gaussian()` | Continua | identidad $\\mu$ | Equivalente a `lm` |\n| `binomial()` | 0/1 o proporción | logit $\\log\\left(\\frac{\\mu}{1-\\mu}\\right)$ | Regresión logística |\n| `poisson()` | Conteos | logaritmo $\\log(\\mu)$ | Modelos de conteo |\n| `Gamma()` | Continua positiva | inversa $1/\\mu$ | Tiempos, costes |\n| `inverse.gaussian()` | Continua positiva | inversa cuadrada $1/\\mu^2$ | Tiempos de espera |\n\n---\n\n:::{#exm-regresion-lineal-simple-generalizada}\nRecordemos el ajuste de un modelo de regresión lineal simple del peso sobre la estatura utilizando el método de máxima verosimilitud con la función `glm()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_lineal <- glm(peso ~ estatura, data = df, family = gaussian())\ntidy(modelo_lineal) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|term        |   estimate|  std.error| statistic|   p.value|\n|:-----------|----------:|----------:|---------:|---------:|\n|(Intercept) | -59.675687| 17.1130556| -3.487144| 0.0006014|\n|estatura    |   0.770071|  0.1003361|  7.674912| 0.0000000|\n\n\n:::\n:::\n\n:::\n\n## Regresión lineal en Estadística bayesiana\n\nEn Estadística bayesiana, los dos coeficientes del modelo $\\beta_0$ y $\\beta_1$ son dos parámetros más del modelo, que tienen asociada una distribución que refleja la incertidumbre sobre su valor. \n\nSi asumimos que el término de error $\\varepsilon$ sigue una distribución normal, entonces tenemos el modelo\n\n$$\nY_i|\\beta_0, \\beta_1, \\sigma \\sim N(\\beta_0 + \\beta_1 x_i, \\sigma).\n$$\n\nAl igual que para otros parámetros, asignaremos una distribución a priori a cada uno de los coeficientes, así como a la desviación típica $\\sigma$ del término de error, y actualizaremos estas distribuciones a priori con los datos para obtener las distribuciones a posteriori de cada uno de los parámetros del modelo.\n\n## Supuestos del modelo de regresión lineal simple\n\nEl modelo de regresión lineal simple se basa en los siguientes supuestos:\n\n1. **Linealidad**. La relación entre $Y$ y $X$ es lineal, es decir, la función $f$ que describe la relación entre $Y$ y $X$ es una recta.\n2. **Independencia**. Las observaciones son independientes entre sí.\n3. **Normalidad**. El término de error $\\varepsilon$ sigue una distribución normal con media cero y desviación típica $\\sigma$.\n4. **Homoscedasticidad**. La varianza del término de error $\\varepsilon$ es constante para todos los valores de $X$.\n\n## Distribución a priori de los parámetros del modelo\n\nComo vimos, para especificar las distribuciones a priori de los parámetros del modelo podemos utilizar distribuciones no informativas o distribuciones informativas. Si disponemos de información previa sobre los parámetros del modelo, debemos utilizar distribuciones informativas para reflejar esa información previa.\n\nPuesto que $\\beta_0$ y $\\beta_1$ son parámetros de localización, es decir, parámetros que pueden tomar cualquier valor real, una distribución a priori adecuada para estos parámetros es la distribución normal. \n\n\\begin{align*} \n\\beta_0 & \\sim N(\\theta_0,\\tau_0) \\\\\n\\beta_1 & \\sim N(\\theta_1,\\tau_1)\n\\end{align*}\n\nMientras que para la desviación típica $\\sigma$ del término de error, que es un parámetro de escala, es decir, un parámetro que sólo puede tomar valores positivos, una distribución a priori adecuada es la distribución exponencial o la Gamma invertida.\n\n$$\n\\sigma \\sim \\text{Exp}(\\lambda).\n$$\n\n## Modelo de regresión lineal simple con distribuciones a priori\n\nDistribución de los datos\n\n$$\nY_i|\\beta_0, \\beta_1, \\sigma \\sim N(\\beta_0 + \\beta_1 x_i, \\sigma).\n$$\n\nDistribución a priori de los parámetros\n\n\\begin{align*}\n\\beta_0 & \\sim N(\\theta_0,\\tau_0) \\\\\n\\beta_1 & \\sim N(\\theta_1,\\tau_1) \\\\\n\\sigma & \\sim \\text{Exp}(\\lambda)\n\\end{align*}\n\n---\n\n:::{#exm-regresion-lineal-simple}\nPara modelizar la relación entre el peso y la estatura, podemos utilizar un modelo de regresión lineal simple con las siguientes distribuciones a priori para los parámetros del modelo:\n\n\\begin{align*}\n\\beta_0' & \\sim N(70, 10) \\\\\n\\beta_1 & \\sim N(2, 1) \\\\\n\\sigma & \\sim \\text{Exp}(0.5)\n\\end{align*}\n\nEn este caso hemos cambiado $\\beta_0$, que sería el peso de una persona de estatura 0, algo que no tiene sentido en nuestro caso, por un término independiente centrado, $\\beta_0'$, que representa el peso típico de una persona de estatura media.\n\n- $\\beta_0'$, que sería el peso de una persona de estatura media, podemos asumir que está entre 45 y 95 kg (media de 70 kg y desviación típica de 10 kg).\n- $\\beta_1$, que sería el incremento en peso por unidad de estatura, podemos asumir que no es negativo y podría estar entre 0 y 4 kg/cm (media de 2 kg/cm y desviación típica de 1 kg/cm).\n- $\\sigma$, que mide la variabilidad de los pesos para personas de la misma estatura, no puede ser negativa y parece razonable también asumir un rango de desviaciones típicas entre 0 y 10 kg.\n:::\n\n## Validación de las distribuciones a priori\n\nCuando utilicemos distribuciones a priori informativas, es importante validar que estas distribuciones reflejan realmente la información previa que tenemos sobre los parámetros del modelo. Para ello, podemos simular valores de los parámetros a partir de las distribuciones a priori y comprobar que estos valores son razonables.\n\nPodemos usar la función `stan` del paquete `rstan` para simular valores de los parámetros a partir de sus distribuciones a priori, utilizando la opción `algorithm = \"Fixed_param\"` para indicar que no queremos ajustar el modelo a los datos, sino sólo simular valores de los parámetros a partir de sus distribuciones a priori.\n\n---\n\n:::{#exm-validacion-distribuciones-priori}\nPara validar las distribuciones a priori del ejemplo anterior, podemos simular 100 valores de $\\beta_0'$, $\\beta_1$ y $\\sigma$ a partir de sus distribuciones a priori.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rstan)\nset.seed(123)\nmodelo <- \"\ndata {\n  int<lower=1> n;   // número de simulaciones (100)\n}\n\ngenerated quantities {\n  real beta0 = normal_rng(70, 10);      \n  real beta1 = normal_rng(1.5, 0.5);        \n  real sigma = exponential_rng(0.5);   \n}\n\"\nprior <- stan(model_code = modelo, data = list(n = 100), \n    chains = 1, iter = 200,  algorithm = \"Fixed_param\")\n```\n:::\n\n:::\n\n---\n\nA continuación, podemos representar gráficamente los valores simulados de cada uno de los parámetros para comprobar que estos valores son razonables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidybayes)\nprior |> \n  spread_draws(beta0, beta1, sigma) |> \n  expand_grid(x = seq(120, 220, length.out = 2)) |>\n  mutate(y = beta0 + beta1 * (x - 170)) |>\n  ggplot(aes(x = x, y = y, group = .draw)) +\n  geom_line(color = myred, alpha = 0.2) +\n  labs(title = \"100 posibles rectas regresión a priori\", x = \"Estatura (cm)\", y = \"Peso (kg)\")\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n## Simulaciones de las distribuciones a posteriori\n\nUna vez validadas las distribuciones a priori, tenemos que definir la función de verosimilitud para los parámetros del modelo $L(\\beta_0, \\beta_1, \\sigma|X,Y)$, y finalmente, aplicar la regla de Bayes para obtener las distribuciones a posteriori de los parámetros del modelo.\n\n$$\nf(\\beta_0, \\beta_1, \\sigma | X, Y) \\propto  f(\\beta_0, \\beta_1, \\sigma) * L(\\beta_0, \\beta_1, \\sigma|X,Y) \n$$\n\n---\n\n:::{#exm-simulaciones-distribuciones-posteriori}\n\nVeamos cómo ajustar el modelo de regresión lineal simple a los datos de los pesos y las estaturas.\n\n```r\nmodelo <- \"\n  data {\n    int<lower = 0> n;\n    vector[n] Y;\n    vector[n] X;\n  }\n  parameters {\n    real beta0;\n    real beta1;\n    real<lower = 0> sigma;\n  }\n  model {\n    Y ~ normal(beta0 + beta1 * X, sigma);\n    beta0 ~ normal(70, 10);\n    beta1 ~ normal(1.5, 0.5);\n    sigma ~ exponential(0.5);\n  }\n\"\npost <- stan(model_code = modelo, \n    data = list(n = nrow(df), Y = df$peso, X = df$estatura), \n    chains = 4, iter = 5000*2, seed = 84735)\n```\n:::\n\n## Simulaciones de las distribuciones a posteriori con el paquete `rstamarm`\n\nAunque ya hemos visto como ajustar un modelo de regresión directamente con `rstan`, la definición del modelo en el lenguaje de programación de Stan puede resultar algo compleja, especialmente para modelos más elaborados. Para facilitar el ajuste de modelos de regresión lineal y generalizada, podemos utilizar la función `stan_glm()` del paquete [`rstanarm`](https://mc-stan.org/rstanarm/articles/rstanarm.html), que proporciona una interfaz más sencilla para ajustar estos modelos de regresión bayesianos.\n\n:::{.callout-note}\n## `stan_glm()`\n\nRealiza un ajuste de un modelo de regresión lineal generalizado mediante inferencia bayesiana. \n\nParámetros: \n\n- `formula`: fórmula que especifica el modelo de regresión lineal generalizado a ajustar. Permite especificar el modelo de regresión de forma sencilla, utilizando una sintaxis similar a la función `glm()` del paquete `stats`.\n- `data`: conjunto de datos que se utilizará para ajustar el modelo de regresión lineal generalizado.\n- `family`: familia de distribuciones que se utilizará para modelar la variable dependiente. Para un modelo de regresión lineal simple, se utiliza la familia `gaussian()`, que asume que la variable dependiente sigue una distribución normal.\n- `prior`: distribución a priori del coeficiente de regresión (la pendiente).\n- `prior_intercept`: distribución a priori del término independiente.\n- `prior_aux`: distribución a priori de la desviación típica del término de error.\n:::\n\n---\n\n:::{#exm-ajuste-regresion-lineal-simple}\nVeamos cómo ajustar el modelo de regresión lineal simple a los datos de los pesos y las estaturas utilizando la función `stan_glm()` \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rstanarm)\nset.seed(123)\nmodelo_peso_estatura <- stan_glm(peso ~ estatura, data = df, family = gaussian(),\n  prior = normal(1.5, 0.5),\n  prior_intercept = normal(70, 10),\n  prior_aux = exponential(0.5),\n  iter = 5000*2, chains = 4, seed = 123)\n```\n:::\n\n:::\n\n:::{.callout-warning}\nLa función `stan_glm` asume que el término independiente está centrado en la media de la variable independiente, por lo que el término independiente $\\beta_0$ representa el peso medio de una persona de estatura media, y no el peso de una persona de estatura 0.\n:::\n\n---\n\nA continuación analizamos las cadenas de Markov generadas por el ajuste del modelo.\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nlibrary(bayesplot)\nmcmc_trace(modelo_peso_estatura, size = 0.1)\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nmcmc_dens_overlay(modelo_peso_estatura)\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n\nSe observa que las cadenas de Markov de los tres parámetros son estables y convergentes.\n\n---\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nneff_ratio(modelo_peso_estatura) |> t() |>  kable()\n```\n\n::: {.cell-output-display}\n\n\n| (Intercept)| estatura|   sigma|\n|-----------:|--------:|-------:|\n|     0.95725|   0.9583| 0.96935|\n\n\n:::\n:::\n\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nrhat(modelo_peso_estatura) |> t() |>  kable()\n```\n\n::: {.cell-output-display}\n\n\n| (Intercept)| estatura|     sigma|\n|-----------:|--------:|---------:|\n|    1.000273| 1.000265| 0.9999572|\n\n\n:::\n:::\n\n\nSe observa que el número efectivo de simulaciones es alto para los tres parámetros, y que el valor de $\\hat{R}$ es casi 1, lo que indica que las cadenas de Markov han convergido correctamente.\n\n## Distribuciones a priori por defecto\n\nCuando no tengamos evidencias fundadas sobre los posibles valores de los parámetros, es mejor utilizar distribuciones a priori poco informativas. La función `stan_glm` utiliza por defecto distribuciones a priori poco informativas para los parámetros del modelo, cuando se indica la opción `autoscale = TRUE` en las distribuciones a priori.\n\n---\n\n:::{#exm-distribuciones-priori-por-defecto}\nVeamos qué distribuciones a priori propone `stan_glm()` para los parámetros del modelo de regresión lineal simple del peso sobre la estatura.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_peso_estatura_2 <- stan_glm(peso ~ estatura, data = df, family = gaussian(), \n  prior_intercept = normal(0, 2.5, autoscale = TRUE), \n  prior = normal(0, 2.5, autoscale = TRUE),\n  prior_aux = exponential(1, autoscale = TRUE),\n  iter = 5000*2, chains = 4, seed = 123)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_summary(modelo_peso_estatura_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPriors for model 'modelo_peso_estatura_2' \n------\nIntercept (after predictors centered)\n  Specified prior:\n    ~ normal(location = 0, scale = 2.5)\n  Adjusted prior:\n    ~ normal(location = 0, scale = 39)\n\nCoefficients\n  Specified prior:\n    ~ normal(location = 0, scale = 2.5)\n  Adjusted prior:\n    ~ normal(location = 0, scale = 4)\n\nAuxiliary (sigma)\n  Specified prior:\n    ~ exponential(rate = 1)\n  Adjusted prior:\n    ~ exponential(rate = 0.064)\n------\nSee help('prior_summary.stanreg') for more details\n```\n\n\n:::\n:::\n\n:::\n\n---\n\n:::{#exr-ajuste-regresion-lineal-simple}\nUtilizar la función `stan_glm()` para realizar un ajuste del modelo de regresión del peso sobre el sexo usando el conjunto de datos [`peso-estatura`](https://aprendeconalf.es/estadistica-bayesiana-presentacion/datos/peso-estatura.csv) y distribuciones a priori poco informativas para los parámetros del modelo. ¿Qué distribuciones a priori propone `stan_glm()` para los parámetros del modelo?\n¿Qué representan los parámetros del modelo?\n:::\n\n:::{.callout-tip}\nCuando la variable independiente es categórica `stan_glm()` crea automáticamente una o varias variables indicadoras (dummy) tomando una categoría como referencia. Por ejemplo en el caso del sexo, toma H como referencia y le asigna el valor 0, mientras que a M le asignar el valor 1.\n:::\n\n---\n\n<details>\n<summary>**Solución**</summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_peso_sexo <- stan_glm(peso ~ sexo, data = df, family = gaussian(),\n  prior_intercept = normal(0, 2.5, autoscale = TRUE),\n  prior = normal(0, 2.5, autoscale = TRUE),\n  prior_aux = exponential(1, autoscale = TRUE),\n  chains = 4, iter = 5000*2, seed = 123)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_summary(modelo_peso_sexo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPriors for model 'modelo_peso_sexo' \n------\nIntercept (after predictors centered)\n  Specified prior:\n    ~ normal(location = 0, scale = 2.5)\n  Adjusted prior:\n    ~ normal(location = 0, scale = 39)\n\nCoefficients\n  Specified prior:\n    ~ normal(location = 0, scale = 2.5)\n  Adjusted prior:\n    ~ normal(location = 0, scale = 79)\n\nAuxiliary (sigma)\n  Specified prior:\n    ~ exponential(rate = 1)\n  Adjusted prior:\n    ~ exponential(rate = 0.064)\n------\nSee help('prior_summary.stanreg') for more details\n```\n\n\n:::\n:::\n\n\n</details>\n\n## Intervalos de credibilidad de los parámetros\n\nAl igual que vimos en el capítulo anterior, podemos describir las distribuciones a posteriori simuladas mediante estadísticos de tendencia central y mediante intervalos de credibilidad.\n\nPara extraer las muestras de las distribuciones de los parámetros generadas por `stan_glm`, podemos utilizar la \nfunción `gather_draws` del paquete `tidybayes`. \n\n:::{.callout-note}\n## `gather_draws`\n\nDevuelve un data frame con las muestras de los parámetros en formato _tidy_, es decir, con una fila por cada simulación de cada parámetro.\n\nParámetros:\n\n- `modelo`: modelo ajustado con `stan_glm()`.\n- `...`: nombres de los parámetros que se quieren extraer. \n:::\n\n---\n\n:::{#exm-intervalos-credibilidad-regresion-lineal-simple}\nVeamos cómo obtener la media y los intervalos de credibilidad del 90% de las distribuciones a posteriori de los parámetros ajustados en el modelo de regresión del peso sobre la estatura.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidybayes)\nmodelo_peso_estatura |>\n  gather_draws(`(Intercept)`, estatura, sigma) |>\n  mean_qi(.width = 0.9) |> \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|.variable   |      .value|      .lower|      .upper| .width|.point |.interval |\n|:-----------|-----------:|-----------:|-----------:|------:|:------|:---------|\n|(Intercept) | -64.4740183| -91.4707326| -37.4422453|    0.9|mean   |qi        |\n|estatura    |   0.7981501|   0.6401111|   0.9565813|    0.9|mean   |qi        |\n|sigma       |  13.6417060|  12.5861465|  14.8037084|    0.9|mean   |qi        |\n\n\n:::\n:::\n\n\nSegún esto, por cada centímetro más de estatura se espera un incremento en el peso de entre 0.64 y 0.95 kg. \n:::\n\n---\n\n:::{#exr-intervalos-credibilidad-regresion-lineal-simple}\nObtener los intervalos de credibilidad del 90% de las distribuciones a posteriori de los parámetros ajustados en el modelo de regresión del peso sobre el sexo. ¿Cómo se interpretarían?\n:::\n\n<details>\n<summary>**Solución**</summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_peso_sexo |>\n  gather_draws(`(Intercept)`, sexoM, sigma) |>\n  mean_qi(.width = 0.9) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|.variable   |    .value|    .lower|    .upper| .width|.point |.interval |\n|:-----------|---------:|---------:|---------:|------:|:------|:---------|\n|(Intercept) |  82.84897|  80.77726|  84.92759|    0.9|mean   |qi        |\n|sexoM       | -20.61104| -23.42480| -17.82881|    0.9|mean   |qi        |\n|sigma       |  11.92269|  10.95815|  12.96286|    0.9|mean   |qi        |\n\n\n:::\n:::\n\n\nCon una probabilidad del 90%, el peso medio de los hombres está entre 80.78 y 84.93 kg, mientras que el peso medio de las mujeres sería entre 17.83 y 23.42 kg menor que el de los hombres.\n</details>\n\n## Dibujo de las rectas de regresión a posteriori\n\nRecordemos que lo que obtenemos es una muestra aleatoria de la distribución a posteriori de los parámetros, obtenida mediante cadenas de Markov. Cada caso de la muestra definie una recta de regresión distinta, y todas ellas reflejan la incertidumbre sobre el modelo de regresión lineal\n\nPodemos dibujar algunas de estas rectas para darnos una idea visual de cómo es el ajuste. Para ello podemos utilizar la función `add_epred_draws` del paquete `tidybayes`.\n\n:::{.callout-note}\n## `add_epred_draws`\n\nAñade al conjunto de datos original las predicciones de un modelo de regresión bayesiano ajustado con `stan_glm()`.\n\nParámetros:\n\n- `modelo`: distribución a posteriori de los parámetros del modelo obtenida mediante las cadenas de Markov.\n- `ndraws`: número de simulaciones de la distribución a posteriori de la predicción que se quieren generar.\n- `value`: nombre de la columna donde se guardarán las predicciones.\n:::\n\n---\n\n:::{#exm-rectas-regresion-posteriori}\nVeamos cómo dibujar 50 de las rectas de regresión obtenidas a partir de la simulación de las distribuciones a posteriori de los parámetros.\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\ndf |>\n  add_epred_draws(modelo_peso_estatura, ndraws = 50, value = \"Predicción_media\") |>\n  ggplot(aes(x = estatura, y = peso)) +\n  geom_point(data = df, color = myblue) +\n  geom_line(aes(y = Predicción_media, group = .draw), color = myred, alpha = 0.2) +\n  labs(x = \"Estatura\", y = \"Peso\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-19-1.png){width=960}\n:::\n:::\n\n:::\n\n## Contraste de hipótesis sobre los coeficientes de regresión\n\nEn Estadística frecuentista, después de ajustar un modelo de regresión lineal, es habitual realizar el contraste de hipótesis sobre los coeficientes de regresión \n\n::::{.columns}\n::: {.column width=\"50%\"}\nContraste sobre el término independiente\n\n\\begin{align*}\nH_0: & \\beta_0 = 0 \\\\\nH_1: & \\beta_0 \\neq 0\n\\end{align*}\n:::\n\n::: {.column width=\"50%\"}\nContraste sobre la pendiente\n\n\\begin{align*}\nH_0: & \\beta_1 = 0 \\\\\nH_1: & \\beta_1 \\neq 0   \n\\end{align*}\n\n:::\n::::\n\nEstos contrastes se realizan con el test t de Student, que se basa en la distribución t de Student, y que nos permite obtener un $p$-valor para cada uno de los coeficientes de regresión, que nos indica la probabilidad de obtener un valor tan extremo como el observado si la hipótesis nula fuera cierta.\n\nEn cambio, en Estadística bayesiana, el contraste de hipótesis sobre los coeficientes de regresión se realiza mediante la comparación de las distribuciones a posteriori de los parámetros con un valor nulo o con un valor específico.\n\n---\n\n:::{#exm-contraste-hipotesis-regresion-lineal-simple}\nVeamos cómo realizar el contraste de hipótesis bayesiano para ver si la pendiente del modelo de regresión lineal del peso sobre la estatura es positiva.\n\n\\begin{align*}\nH_0: & \\beta_1 > 0 \\\\\nH_1: & \\beta_1 \\leq 0\n\\end{align*}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidybayes)\nmodelo_peso_estatura |>\n  spread_draws(estatura) |>\n  summarise(prob = mean(estatura > 0)) |>\n  kable(col.names = \"P(β1 > 0)\")\n```\n\n::: {.cell-output-display}\n\n\n| P(β1 > 0)|\n|---------:|\n|         1|\n\n\n:::\n:::\n\n\nEs decir, podemos afirmar casi con total certeza que la pendiente del modelo de regresión lineal del peso sobre la estatura es positiva, lo que indica que a mayor estatura, mayor peso.\n:::\n\n---\n\n:::{#exr-intervalos-credibilidad-regresion-lineal-simple}\nRealizar un contraste de comparación de medias para ver si el peso medio de los hombres es mayor que el de las mujeres, y calcular la probabilidad de que esto sea cierto a partir de las distribuciones a posteriori de los parámetros del modelo.\n:::\n\n<details>\n<summary>**Solución**</summary>\n\nPara el contraste de comparación de medias, la hipótesis de interés es:\n\n$$H_0: \\mu_H > \\mu_M \\iff \\beta_1 < 0$$\n\nLa probabilidad a posteriori de que el peso medio de los hombres sea mayor que el de las mujeres se calcula como la proporción de muestras de la distribución a posteriori en que $\\beta_1 < 0$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_peso_sexo |>\n  spread_draws(`(Intercept)`, sexoM) |>\n  summarise(prob_H_mayor_M = mean(sexoM < 0)) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| prob_H_mayor_M|\n|--------------:|\n|              1|\n\n\n:::\n:::\n\n\n</details>  \n\n\n## Predicciones con modelos de regresión\n\nUna de las principales utilidades de los modelos de regresión es la posibilidad de realizar predicciones sobre nuevos casos a partir de los valores de las variables independientes.\n\nA la hora de hacer predicciones con un modelo de regresión, es importante tener en cuenta que existen dos fuentes de variabilidad que afectan a la predicción:\n\n- **Variabilidad de los parámetros del modelo**. Esta variabilidad se refleja en las distribuciones a posteriori de los parámetros del modelo, que se han obtenido a partir de la simulación mediante cadenas de Markov.\n- **Variabilidad en el muestreo**. Es la variabilidad asociada al término de error que viene dada por el parámetro $\\sigma$ del modelo, que también tiene una distribución a posteriori obtenida a partir de la simulación mediante cadenas de Markov.\n\n## Tipos de predicciones\n\nDado un nuevo caso con un valor concreto de la variable independiente $\\hat{x}$, podemos estar interesados en dos tipos de predicciones:\n\n- **Predicción de la media** de la variable dependiente para ese caso $E[Y|\\hat{X}]$. Esta predicción se obtiene a partir de la distribución a posteriori de los parámetros del modelo, y refleja la incertidumbre sobre el valor de la media de $Y$ para ese caso. _Solo tiene en cuenta la variabilidad de los parámetros del modelo, pero no tiene en cuenta la variabilidad en el muestreo._\n  \n- **Predicción de un nuevo valor** de la variable dependiente para ese caso $Y|\\hat{X}$. Esta predicción se obtiene a partir de la distribución a posteriori de los parámetros del modelo y de la distribución del término de error, y refleja la incertidumbre sobre el valor de $Y$ para ese caso. _Tiene en cuenta tanto la variabilidad de los parámetros del modelo como la variabilidad en el muestreo._\n\n## Predicción de la media de la variable dependiente para un nuevo caso\n\nPara predecir la media de la variable dependiente para un nuevo caso, basta con tener en cuenta que \n\n$$\nE[Y|\\hat{x}] = \\beta_0 + \\beta_1\\hat{x},\n$$\n\npor lo que podemos generar la distribución a posteriori de la predicción de la media de $Y$ para ese caso aplicando esta fórmula a cada una de las simulaciones de los parámetros del modelo obtenidas mediante las cadenas de Markov.\n\nPara ello podemos usar la función `epred_draws` del paquete `tidybayes`.\n\n:::{.callout-note}\n## `epred_draws`\n\nGenera una simulación de la distribución a posteriori de la predicción de la media de la variable dependiente para un nuevo caso, a partir de un modelo de regresión bayesiano ajustado con `stan_glm()`.\n\nParámetros:\n\n- `modelo`: distribución a posteriori de los parámetros del modelo obtenida mediante las cadenas de Markov.\n- `newdata`: nuevo caso para el que se quiere realizar la predicción, especificado como un data frame con las mismas variables independientes que el modelo de regresión.\n- `value`: nombre de la columna donde se guardarán las predicciones.\n:::\n\n---\n\n:::{#exm-predicciones-regresion-lineal-simple}\nVeamos cómo obtener la distribución a posteriori de la predicción del peso medio para una persona de estatura 180 cm, utilizando el modelo de regresión lineal simple ajustado anteriormente.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndatos_nuevos <- tibble(estatura = c(180))\npred_media_180 <- epred_draws(modelo_peso_estatura, newdata = datos_nuevos, value = \"Predicción_media\")\npred_media_180\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20,000 × 6\n# Groups:   estatura, .row [1]\n   estatura  .row .chain .iteration .draw Predicción_media\n      <dbl> <int>  <int>      <int> <int>            <dbl>\n 1      180     1     NA         NA     1             79.5\n 2      180     1     NA         NA     2             78.9\n 3      180     1     NA         NA     3             78.9\n 4      180     1     NA         NA     4             81.0\n 5      180     1     NA         NA     5             81.9\n 6      180     1     NA         NA     6             77.2\n 7      180     1     NA         NA     7             81.3\n 8      180     1     NA         NA     8             79.8\n 9      180     1     NA         NA     9             79.3\n10      180     1     NA         NA    10             79.8\n# ℹ 19,990 more rows\n```\n\n\n:::\n:::\n\n:::\n\n---\n\nAunque podríamos haber obtenido lo mismo con el siguiente código.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidybayes)\nmodelo_peso_estatura |> \n  spread_draws(`(Intercept)`, estatura) |>\n  mutate(Prediccion_media = `(Intercept)` + estatura * 180)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20,000 × 6\n   .chain .iteration .draw `(Intercept)` estatura Prediccion_media\n    <int>      <int> <int>         <dbl>    <dbl>            <dbl>\n 1      1          1     1         -60.7    0.779             79.5\n 2      1          2     2         -68.6    0.819             78.9\n 3      1          3     3         -63.4    0.791             78.9\n 4      1          4     4         -71.0    0.844             81.0\n 5      1          5     5         -80.6    0.903             81.9\n 6      1          6     6         -60.9    0.767             77.2\n 7      1          7     7         -73.4    0.860             81.3\n 8      1          8     8         -59.4    0.773             79.8\n 9      1          9     9         -80.7    0.888             79.3\n10      1         10    10         -81.2    0.894             79.8\n# ℹ 19,990 more rows\n```\n\n\n:::\n:::\n\n\n---\n\nY una vez que tenemos la distribución a posteriori de la predicción, podemos describirla mediante su media y su intervalo de credibilidad como es habitual.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_qi(pred_media_180, .width = 0.9) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| estatura| .row| Predicción_media|   .lower|   .upper| .width|.point |.interval |\n|--------:|----:|----------------:|--------:|--------:|------:|:------|:---------|\n|      180|    1|         79.19299| 77.00875| 81.38256|    0.9|mean   |qi        |\n\n\n:::\n:::\n\n\nEs decir, para una persona de estatura 180 cm, el peso medio estaría entre 77 y 81.4 kg, con una probabilidad del 90%.\n\n## Predicción de un nuevo valor de la variable dependiente para un nuevo caso\n\nPara predecir un nuevo valor de la variable dependiente para un nuevo caso, debemos tener en cuenta tanto la variabilidad de los parámetros del modelo como la variabilidad en el muestreo, por lo que la distribución a posteriori de la predicción será\n\n$$\nY|\\hat{x},\\beta_0,\\beta_1,\\sigma \\sim N(\\beta_0 + \\beta_1 \\hat{x}, \\sigma),\n$$\n\nAsí pues, para obtener una muestra aleatoria de esta distribución, basta con generar una simulación de esta distribución para cada una de las simulaciones de los parámetros del modelo obtenidas mediante las cadenas de Markov. \n\n\\begin{align*}\n\\beta_{0,1}, \\beta_{1,1}, \\sigma_1 &\\longrightarrow \\hat{y}_1 = \\text{rnorm}(1, \\beta_{0,1} + \\beta_{1,1} \\hat{x}, \\sigma_1) \\\\\n\\beta_{0,2}, \\beta_{1,2}, \\sigma_2 &\\longrightarrow \\hat{y}_2 = \\text{rnorm}(1, \\beta_{0,2} + \\beta_{1,2} \\hat{x}, \\sigma_2) \\\\\n&\\vdots \\\\\n\\beta_{0,n}, \\beta_{1,n}, \\sigma_n &\\longrightarrow \\hat{y}_n = \\text{rnorm}(1, \\beta_{0,n} + \\beta_{1,n} \\hat{x}, \\sigma_n) \\\\\n\\end{align*}\n\n---\n\nAunque no es complicado simular esta muestra con R, podemos aprovechar la función `predicted_draws` del paquete `tidybayes`.\n\n:::{.callout-note}\n## `predicted_draws`\n\nGenera una simulación de la distribución a posteriori de la predicción de un nuevo valor de la variable dependiente para un nuevo caso, a partir de un modelo de regresión bayesiano ajustado con `stan_glm()`.\n\nParámetros:\n\n- `modelo`: distribución a posteriori de los parámetros del modelo obtenida mediante `stan_glm()`.\n\n- `newdata`: nuevos casos para los que se quiere realizar la predicción, especificado como un data frame con las mismas variables independientes que el modelo de regresión.\n\n- `value`: nombre de la columna donde se guardarán las predicciones.\n:::\n\n---\n\n:::{#exm-prediccion-nuevo-valor-regresion-lineal-simple}\n\nVeamos cómo obtener la distribución a posteriori de la predicción de un nuevo valor del peso para una persona de estatura 180 cm, utilizando el modelo de regresión lineal simple ajustado anteriormente.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_180 <- predicted_draws(modelo_peso_estatura, newdata = datos_nuevos, value = \"Predicción\")\nmean_qi(pred_180, .width = 0.9) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n| estatura| .row| Predicción|   .lower|   .upper| .width|.point |.interval |\n|--------:|----:|----------:|--------:|--------:|------:|:------|:---------|\n|      180|    1|   79.31403| 56.86489| 102.0955|    0.9|mean   |qi        |\n\n\n:::\n:::\n\n\nEs decir, el rango de pesos factibles para una persona de estatura 180 cm estaría entre 56.9 y 102.1 kg, con una probabilidad del 90%, aunque evidentemente no todos los valores de esta distribución son igualmente probables, por lo que a veces es más útil representar gráficamente esta distribución para tener una idea visual de la predicción.\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nggplot(pred_180, aes(x = Predicción)) +\n  stat_halfeye(.width = 0.9, fill = myblue, alpha = 0.5) +\n  labs(x = \"Peso (kg)\", y = \"Densidad\")\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-26-1.png){width=960}\n:::\n:::\n\n:::\n\n---\n\nEn la siguiente gráfica se puede apreciar sobre el digrama de dispersión el intervalo de credibilidad para la predicción media (en verde) y para la predicción de un nuevo valor (en rojo) para una persona de estatura 180 cm.\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nggplot(df, aes(x = estatura, y = peso)) +\n  geom_point(color = myblue) +\n  stat_pointinterval(\n    data = pred_180,\n    aes(x = estatura, y = Predicción),\n    .width = 0.9, color = myred, size = 5\n  ) +\n  stat_pointinterval(\n    data = pred_media_180,\n    aes(x = estatura, y = Predicción_media),\n    .width = 0.9, color = mygreen, size = 5,\n  ) +\n  labs(x = \"Estatura (cm)\", y = \"Peso (kg)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-27-1.png){width=960}\n:::\n:::\n\n\n---\n\n:::{#exr-predicciones-regresion-lineal-simple}\nRealizar la predicción de la media y de un nuevo valor del peso para un hombre y para una mujer utilizando el modelo de regresión del peso sobre el sexo. Calcular los intervalos de credibilidad del 90% para cada una de las predicciones y representarlas gráficamente sobre el diagrama de dispersión de los datos.\n:::\n\n---\n\n<details>\n<summary>**Solución**</summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndatos_nuevos_sexo <- tibble(sexo = c(\"H\", \"M\"))\npred_media_sexo <- epred_draws(modelo_peso_sexo, newdata = datos_nuevos_sexo, value = \"Predicción_media\")\nmean_qi(pred_media_sexo, .width = 0.9) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|sexo | .row| Predicción_media|   .lower|   .upper| .width|.point |.interval |\n|:----|----:|----------------:|--------:|--------:|------:|:------|:---------|\n|H    |    1|         82.84897| 80.77726| 84.92759|    0.9|mean   |qi        |\n|M    |    2|         62.23793| 60.38337| 64.10886|    0.9|mean   |qi        |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_sexo <- predicted_draws(modelo_peso_sexo, newdata = datos_nuevos_sexo, value = \"Predicción\")\nmean_qi(pred_sexo, .width = 0.9) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|sexo | .row| Predicción|   .lower|    .upper| .width|.point |.interval |\n|:----|----:|----------:|--------:|---------:|------:|:------|:---------|\n|H    |    1|   82.85949| 63.30231| 102.45972|    0.9|mean   |qi        |\n|M    |    2|   62.19614| 42.33077|  81.86533|    0.9|mean   |qi        |\n\n\n:::\n:::\n\n</details>\n\n---\n\n<details>\n<summary>**Solución (continuación)**</summary>\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nggplot(df, aes(x = sexo, y = peso)) +\n  geom_jitter(color = myblue, alpha = 0.4, width = 0.1) +\n  stat_pointinterval(\n    data = pred_media_sexo,\n    aes(x = sexo, y = Predicción_media),\n    .width = 0.9, color = mygreen, linewidth = 3, size = 5\n  ) +\n  stat_pointinterval(\n    data = pred_sexo,\n    aes(x = sexo, y = Predicción),\n    .width = 0.9, color = myred, linewidth = 1, size = 3\n  ) +\n  labs(x = \"Sexo\", y = \"Peso (kg)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-30-1.png){width=960}\n:::\n:::\n\n\n</details>\n\n## Evaluación de modelos de regresión\n\nTodos los modelos de regresión son aproximaciones de la realidad, y por tanto, es importante evaluar la calidad del ajuste de un modelo a los datos, sobre todo si queremos hacer predicciones con ese modelo.\n\nLa manera más lógica de evaluar la calidad del ajuste de un modelo de regresión es comparar las predicciones del modelo con los valores observados en los datos, y medir la discrepancia entre ambos.\n\nPara ello, primero debemos obtener las distribuciones a posteriori de las predicciones para cada uno de los casos de la muestra. Como ya hemos visto esto podemos hacerlo con la función `predicted_draws()` del paquete `tidybayes`.\n\n---\n\n:::{#exm-evaluacion-modelo-regresion}\nVeamos cómo obtener los intervalos de credibilidad de las predicciones para cada una de las estaturas del conjunto de datos, utilizando el modelo de regresión lineal simple ajustado anteriormente.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npost_pred <- predicted_draws(modelo_peso_estatura, newdata = df, value = \"Predicción\")\nggplot(post_pred, aes(x = estatura, y = Predicción)) +\n  stat_pointinterval(.width = c(0.5, 0.95), color = myred) +\n  geom_point(data = df, aes(y = peso), color = myblue) +\n  labs(x = \"Estatura (cm)\", y = \"Peso (kg)\")\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-31-1.png){width=960}\n:::\n:::\n\n:::\n\n## Métricas de evaluación \n\nUna vez hemos generado las distribuciones a posteriori de las predicciones para cada uno de los casos de la muestra, podemos usar las siguientes métricas para evaluar la precisión de las predicciones del modelo:\n\n- **Error absoluto mediano (MAE)**. Es la mediana de los valores absolutos de las diferencias entre los valores observados y los valores predichos por el modelo.\n\n$$\nMAE = \\mbox{Mediana}\\{|y_i - \\hat{y}_i|\\}\n$$\n\n- **Error absoluto mediano tipificado ($MAE_t$)**. Es la mediana de los valores absolutos de las diferencias entre los valores observados y los valores predichos por el modelo, tipificados por la desviación típica de los valores observados.\n\n$$\nMAE_t = \\mbox{Mediana}\\left\\{\\frac{|y_i - \\hat{y}_i|}{\\sigma_y}\\right\\}\n$$\n\n---\n\n- **Raíz del Error cuadrático medio (RMSE)**. Es la media de los cuadrados de las diferencias entre los valores observados y los valores predichos por el modelo. \n\n$$ \nRMSE = \\sqrt{\\frac{1}{n} \\sum_{i=1}^{n} (y_i - \\hat{y}_i)^2}\n$$\n\n- **Cobertura de los intervalos de credibilidad de las predicciones**. Es la proporción de casos de la muestra para los que el valor observado se encuentra dentro del intervalo de credibilidad de las predicciones del modelo. Se puede hacer para distintos niveles de credibilidad, por ejemplo, 50%, 90% y 95%.\n\n\n- **Coeficiente de determinación bayesiano $R^2$**. Es la proporción de la variabilidad total de los valores observados que es explicada por el modelo de regresión.\n\n$$\nR^2_{\\mbox{Bayes}} = \\frac{\\mbox{Var}(\\hat{y})}{\\mbox{Var}(\\hat{y}) + \\mbox{Var}(y - \\hat{y})}\n$$\n\n---\n\nExisten diferentes paquetes de R que permiten calcular estas métricas de evaluación de modelos de regresión. \n\nPara calcular el error absoluto mediano, el error absoluto mediano tipificado y los intervalos de cobertura, podemos usar la función `prediction_summary()` del paquete [`bayesrules`](https://bayes-rules.github.io/bayesrules/docs/).\n\n:::{.callout-note}\n## `prediction_summary`\n\nDevuelve el error absoluto mediano, el error absoluto mediano tipificado y los intervalos de cobertura de las predicciones de un modelo de regresión bayesiano.\n\nParámetros:\n\n- `model`: modelo de regresión bayesiano ajustado con `stan_glm`.\n- `data`: conjunto de datos con los valores de la variable dependiente y las variables independientes.\n- `prob_inner`: nivel de credibilidad para los intervalos de cobertura. Por defecto 50%.\n- `prob_outer`: nivel de credibilidad para los intervalos de cobertura. Por defecto 90%.\n:::\n\n---\n\n:::{#exm-metricas-evaluacion-modelo-regresion-1}\nVeamos cómo calcular el error absoluto mediano, el error absoluto mediano tipificado y los intervalos de cobertura de las predicciones del modelo de regresión lineal simple ajustado anteriormente.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(bayesrules)\nprediction_summary(modelo_peso_estatura, data = df, prob_outer = 0.9) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|      mae| mae_scaled| within_50| within_90|\n|--------:|----------:|---------:|---------:|\n| 9.326715|  0.6812318|       0.5|     0.915|\n\n\n:::\n:::\n\n\nEn los 200 individuos de la muestra, el peso observado se encuentra típicamente a 9.3 kg de distancia de la mediana de la distribución predictiva correspondiente a su estatura, o a 0.68 desviaciones típicas. Además, el 50% de los pesos caen dentro del intervalo de credibilidad del 50% y el 91.5% caen dentro del intervalo de credibilidad del 90% de la distribución predictiva correspondiente a su estatura. \n:::\n\n---\n\nY para calcular el coeficiente de determinación bayesiano $R^2$, podemos usar la función `bayes_R2()` del paquete [`rstanarm`](https://mc-stan.org/rstanarm/reference/bayes_R2.html).\n\n:::{.callout-note}\n## `bayes_R2`\n\nCalcula la distribución a posteriori del coeficiente de determinación bayesiano $R^2$ de un modelo de regresión bayesiano ajustado con `stan_glm`.\n\nParámetros:\n\n- `object`: modelo de regresión bayesiano ajustado con `stan_glm`.\n:::\n\n---\n\n:::{#exm-metricas-evaluacion-modelo-regresion-2}\nVeamos cómo calcular la distribución a posteriori del coeficiente de determinación bayesiano $R^2$ del modelo de regresión lineal simple ajustado anteriormente.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rstanarm)\nbayes_R2(modelo_peso_estatura) |>\n  mean_qi(.width = 0.9) |>\n  kable(col.names = c(\"R² medio\", \".lower\", \".upper\", \".width\", \".point\", \".interval\"))\n```\n\n::: {.cell-output-display}\n\n\n|  R² medio|    .lower|   .upper| .width|.point |.interval |\n|---------:|---------:|--------:|------:|:------|:---------|\n| 0.2462697| 0.1683791| 0.324617|    0.9|mean   |qi        |\n\n\n:::\n:::\n\nLa media de la distribución a posteriori del coeficiente de determinación bayesiano es 0.25, lo que indica que el modelo de regresión lineal explica alrededor del 25% de la variabilidad del peso, o teniendo en cuenta el intervalo de credibilidad, entre el 16.8% y el 32.5% de la variabilidad del peso con una probabilidad del 90%.     \n:::\n\n---\n\n:::{#exr-metricas-evaluacion-modelo-regresion}\nCalcular las métricas de evaluación del modelo de regresión del peso sobre el sexo. ¿Qué conclusiones se pueden extraer de estas métricas?\n:::\n\n<details>\n<summary>**Solución**</summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprediction_summary(modelo_peso_sexo, data = df, prob_outer = 0.9) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|      mae| mae_scaled| within_50| within_90|\n|--------:|----------:|---------:|---------:|\n| 8.026257|  0.6680014|       0.5|     0.895|\n\n\n:::\n:::\n\n\nEl error absoluto mediano es de 8.03 kg, lo que indica que el peso observado se encuentra típicamente a 8.03 kg de distancia de la mediana de la distribución predictiva correspondiente a su sexo, o a 0.67 desviaciones típicas. Además, el 50% de los pesos caen dentro del intervalo de credibilidad del 50% y el 89.5% caen dentro del intervalo de credibilidad del 90% de la distribución predictiva correspondiente a su sexo.\n\n</details>\n\n---\n\n<details>\n<summary>**Solución (continuación)**</summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_R2(modelo_peso_sexo) |>\n  mean_qi(.width = 0.9) |>\n  kable(col.names = c(\"R² medio\", \".lower\", \".upper\", \".width\", \".point\", \".interval\"))\n```\n\n::: {.cell-output-display}\n\n\n|  R² medio|   .lower|    .upper| .width|.point |.interval |\n|---------:|--------:|---------:|------:|:------|:---------|\n| 0.4255578| 0.344607| 0.5009578|    0.9|mean   |qi        |\n\n\n:::\n:::\n\n\nLa media de la distribución a posteriori del coeficiente de determinanción es 0.43, lo que indica que el modelo de regresión explica aproximadamente el 43% de la variabilidad del peso, o teniendo en cuenta el intervalo de credibilidad, entre el 34.5% y el 50.1% de la variabilidad del peso con una probabilidad del 90%.\n</details>\n\n## Evaluación del modelo de regresión en datos nuevos\n\nEn general, un modelo de regresión ajustado a un conjunto de datos se ajustará mejor a esos datos que a otros datos nuevos. Este problema se conoce como _sobreajuste_ (_overfitting_).\n\nCuando hay sobreajuste de un modelo de regresión, las medidas de precisión del modelo evaluadas sobre el propio conjunto de datos sobreestiman la capacidad predictiva del modelo, por lo que es importante evaluar la capacidad de predicción del modelo en datos nuevos. Para ello se suele dividir el conjunto de datos en dos subconjuntos:\n\n- **Conjunto de entrenamiento**. Se utiliza para ajustar el modelo de regresión y obtener las distribuciones a posteriori de los parámetros del modelo.\n- **Conjunto de prueba**. Se utiliza para evaluar la precisión del modelo. \n\nEsta división permite ajustar el modelo de regresión a partir del conjunto de entrenamiento y evaluar la precisión del modelo en el conjunto de prueba, que no se ha utilizado para ajustar el modelo.\n\n## Validación cruzada\n\nRealizar la evaluación de un modelo de regresión con un conjunto de datos nuevos, sin duda dará una estimación más realista de la precisión predictiva del modelo. Para que esta estimación sea más fiable, es recomendable repetir el proceso varias veces con distintos conjuntos de entrenamiento y prueba, y calcular la media de las métricas de evaluación obtenidas en cada repetición.\n\nLa _validación cruzada_ se basa en esta idea y consiste en dividir el conjunto de datos en $k$ subconjuntos llamados _pliegues_ (_folds_), y realizar $k$ iteraciones. En cada iteración se reserva uno de los $k$ subonjuntos como conjunto de prueba y se ajusta el modelo de regresión con los $k-1$ subconjuntos restantes, que forman el conjunto de entrenamiento. En cada iteración se calculan las métricas de evaluación del modelo en el conjunto de prueba, y al final se calcula la media de estas métricas a lo largo de las $k$ iteraciones.\n\n---\n\n![Validación cruzada con 4 pliegues](/img/04-regresion-bayesiana/validacion-cruzada)\n\n---\n\nPara realizar la evaluación de un modelo de regresión mediante validación cruzada, podemos utilizar la función `prediction_summary_cv` del paquete [`bayesrules`](https://bayes-rules.github.io/bayesrules/docs/).\n\n:::{.callout-note}\n## `prediction_summary_cv`\n\nDevuelve el error absoluto mediano, el error absoluto mediano tipificado y los intervalos de cobertura de las predicciones de un modelo de regresión bayesiano mediante validación cruzada.\n\nParámetros:\n\n- `model`: modelo de regresión bayesiano ajustado con `stan_glm`.\n- `data`: datos de entrenamiento.\n- `k`: número de pliegues para la validación cruzada.\n- `prob_inner`: nivel de credibilidad para los intervalos de cobertura menores. Por defecto 50%.\n- `prob_outer`: nivel de credibilidad para los intervalos de cobertura mayores. Por defecto 90%.\n:::\n\n---\n\n:::{#exm-metricas-evaluacion-modelo-regresion-cv}\nVeamos cómo realizar la evaluación del modelo de regresión lineal simple del peso sobre la estatura mediante validación cruzada con 10 pliegues.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\neval_cv <- prediction_summary_cv(model = modelo_peso_estatura, data = df, k = 5, prob_outer = 0.9)\neval_cv$folds |> kable()\n```\n\n::: {.cell-output-display}\n\n\n| fold|       mae| mae_scaled| within_50| within_90|\n|----:|---------:|----------:|---------:|---------:|\n|    1| 11.570890|  0.8955285|     0.400|     0.800|\n|    2|  9.951345|  0.7217875|     0.475|     0.900|\n|    3| 11.452480|  0.8399348|     0.450|     0.900|\n|    4|  8.998740|  0.6471245|     0.500|     0.925|\n|    5|  5.617575|  0.3934988|     0.625|     0.975|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\neval_cv$cv |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|      mae| mae_scaled| within_50| within_90|\n|--------:|----------:|---------:|---------:|\n| 9.518206|  0.6995748|      0.49|       0.9|\n\n\n:::\n:::\n\n:::\n\nSi comparamos estas métricas con las obtenidas anteriormente sin validación cruzada, vemos que la precisión es un poco menor, pero más realista.\n\n---\n\n:::{#exr-metricas-evaluacion-modelo-regresion-cv}\nRealizar la evaluación del modelo de regresión del peso sobre el sexo mediante validación cruzada con 10 pliegues. ¿Qué conclusiones se pueden extraer de estas métricas?\n:::\n\n<details>\n<summary>**Solución**</summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\neval_cv <- prediction_summary_cv(model = modelo_peso_sexo, data = df, k = 5, prob_outer = 0.9)\neval_cv$cv |> kable()  \n```\n\n::: {.cell-output-display}\n\n\n|      mae| mae_scaled| within_50| within_90|\n|--------:|----------:|---------:|---------:|\n| 8.209561|  0.6868003|     0.505|      0.89|\n\n\n:::\n:::\n\n\nSe observa que el error absoluto mediano es ahora 8.2, ligeramente mayor que el obtenido sin validación cruzada, lo que indica que el modelo de regresión del peso sobre el sexo tiene un ligero sobreajuste a los datos de entrenamiento. \n\n## {background-color= .myblue}\n\n:::{.main-title}\nRegresión lineal múltiple\n:::\n\n## Regresión lineal múltiple\n\nCuando la variable dependiente $Y$ depende de varias variables independientes $X_1, X_2, \\ldots, X_p$, se habla de _regresión lineal múltiple_:\n\n$$\nY = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\cdots + \\beta_p X_p + \\varepsilon, \\quad \\varepsilon \\sim N(0, \\sigma).\n$$\n\nEl procedimiento para ajustar un modelo de regresión lineal múltiple mediante inferencia bayesiana es el mismo que para un modelo de regresión lineal simple, solo que con más parámetros a estimar y de los que debemos especificar sus distribuciones a priori.\n\n---\n\n:::{#exr-regresion-multiple}\n¿Qué modelo de regresión lineal múltiple ajustarías para modelizar el peso de una persona en función de su estatura y su sexo? ¿Qué distribuciones a priori utilizarías para los parámetros del modelo?\n:::\n\n<details>\n<summary>**Solución**</summary>\nAntes de nada, puesto que el sexo es una variable categórica, debemos codificarla como variable númerica para poder introducirla en el modelo de regresión múltiple (por ejemplo 0 para hombres y 1 para mujeres).\n\nSi llamamos $X_1$ a la estatura y $X_2$ al sexo, el modelo de regresión lineal múltiple sería:\n\n$$\nY|\\beta_0, \\beta_1, \\beta_2, \\sigma \\sim N(\\beta_0 + \\beta_1 X_1 + \\beta_2 X_2, \\sigma)\n$$\n\nDe esta manera, para cada categoría de sexo, el modelo de regresión lineal múltiple nos da una recta de regresión distinta:\n\n::::{.columns}\n::: {.column width=\"50%\"}\nRecta de regresión de hombres ($X_2 = 0$)\n\n$$\nY = \\beta_0 + \\beta_1 X_1 + \\varepsilon\n$$\n:::\n\n::: {.column width=\"50%\"}\nRecta de regresión de mujeres ($X_2 = 1$)\n\n$$\nY = (\\beta_0 + \\beta_2) + \\beta_1 X_1 + \\varepsilon\n$$\n:::\n::::\n</details>\n\n---\n\n<details>\n<summary>**Solución** (continuación)</summary>\nEste modelo asume que la pendiente de la recta de regresión es la misma para hombres y mujeres, pero que el término independiente es distinto. \n\nPara las distribuciones a priori de los parámetros $\\beta_0, \\beta_1$ y $\\sigma$, podemos utilizar las mismas distribuciones a priori que en el modelo de regresión lineal simple. \n\nY para  la distribución a priori de $\\beta_2$ podemos usar una distribución normal que refleje la diferencia de peso entre hombres y mujeres, que sabemos por experiencia que es positiva. Por ejemplo, $\\beta_2 \\sim N(-10, 5)$, que refleja que la diferencia de peso entre hombres y mujeres de la misma estatura es de unos 10 kg, con una desviación típica de 5 kg.\n</details>\n\n## Evaluación de las distribuciones a priori\n\nComo ya vimos con los modelos de regresión simple, antes de hacer el ajuste del modelo, conviene evaluar las distribuciones a priori de los parámetros del modelo para comprobar que son razonables. Para ello podemos simular valores de los parámetros a partir de sus distribuciones a priori y dibujar las rectas de regresión correspondientes.\n\nRecordemos que podemos usar la misma función `stan_glm` para simular las distribuciones a priori de los parámetros del modelo, añadiendo la opción `prior_PD = TRUE`.\n\n---\n\n:::{#exm-evaluacion-distribuciones-priori-regresion-multiple}\nVeamos cómo simular las distribuciones a priori de los parámetros del modelo de regresión lineal múltiple del peso sobre la estatura y el sexo. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rstanarm)\nset.seed(123)\nmodelo_peso_estatura_sexo_prior <- stan_glm(\n  peso ~ estatura + sexo,\n  data = df,\n  family = gaussian(),\n  prior_intercept = normal(70, 10),\n  prior = normal(location = c(1.5, -10), scale = c(0.5, 5)),\n  prior_aux = exponential(0.5),\n  chains = 4, iter = 5000 * 2, seed = 123,\n  prior_PD = TRUE\n)\n```\n:::\n\n:::\n\n:::{.callout-warning}\nLa función `stan_glm` realiza la codificación de las variables categóricas de forma automática y asigna el código 0 a la primera categoría alfabéticamente y el código 1 a la segunda categoría.\n:::\n\n---\n\nA continuación podemos dibujar algunas de las rectas de regresión obtenidas a partir de la simulación de las distribuciones a priori de los parámetros del modelo para ver si son razonables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |>\n  add_epred_draws(modelo_peso_estatura_sexo_prior, ndraws = 50, value = \"Predicción_media\") |>\n  ggplot(aes(x = estatura, y = peso, color = sexo)) +\n  geom_line(aes(y = Predicción_media, group = paste(sexo, .draw)), alpha = 0.2) +\n  labs(x = \"Estatura\", y = \"Peso\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-40-1.png){width=960}\n:::\n:::\n\n\n## Ajuste del modelo de regresión lineal múltiple\n\nUna vez que hemos evaluado las distribuciones a priori de los parámetros del modelo y hemos comprobado que son razonables, podemos ajustar el modelo de regresión lineal múltiple a los datos.\n\nEn realidad no hace falta especificar de nuevo las distribuciones a priori de los parámetros del modelo. Basta con usar la función `update` pasándole el modelo anterior con la opción `prior_PD = FALSE`, para que se ajusten las distribuciones a posteriori de los parámetros del modelo a partir de los datos.\n\n:::{#exm-ajuste-regresion-multiple}\nPara ajustar el modelo de regresión lineal múltiple del peso sobre la estatura y el sexo, basta con usar el siguiente código.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_peso_estatura_sexo <- update(modelo_peso_estatura_sexo_prior, prior_PD = FALSE)\n```\n:::\n\n:::\n\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmcmc_trace(modelo_peso_estatura_sexo, size = 0.2)\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-42-1.png){width=960}\n:::\n:::\n\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmcmc_dens_overlay(modelo_peso_estatura_sexo)\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-43-1.png){width=960}\n:::\n:::\n\n\nObservando las trazas y las distribuciones de las cadenas de Markov, se puede ver que las cadenas son estables y convergentes.\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nneff_ratio(modelo_peso_estatura_sexo) |> t() |> kable()\n```\n\n::: {.cell-output-display}\n\n\n| (Intercept)| estatura|   sexoM|   sigma|\n|-----------:|--------:|-------:|-------:|\n|       0.591|   0.6041| 0.58735| 0.83105|\n\n\n:::\n\n```{.r .cell-code}\nrhat(modelo_peso_estatura_sexo) |> t() |> kable()\n```\n\n::: {.cell-output-display}\n\n\n| (Intercept)| estatura|    sexoM|    sigma|\n|-----------:|--------:|--------:|--------:|\n|    1.000261| 1.000247| 1.000196| 1.000207|\n\n\n:::\n:::\n\n\nEl número efectivo de simulaciones es razonablemente alto para los tres parámetros, y el valor de $\\hat{R}$ es casi 1, lo que indica que las cadenas de Markov han convergido correctamente.\n\n## Intervalos de credibilidad de los parámetros\n\n:::{#exm-intervalos-credibilidad-regresion-lineal-multiple}\nVeamos cómo obtener la media y los intervalos de credibilidad del 90% de las distribuciones a posteriori de los parámetros ajustados en el modelo de regresión del peso sobre la estatura y el sexo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidybayes)\nmodelo_peso_estatura_sexo |> \n  gather_draws(`(Intercept)`, estatura, sexoM, sigma) |>\n  mean_qi(.width = 0.9) |> \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|.variable   |      .value|      .lower|      .upper| .width|.point |.interval |\n|:-----------|-----------:|-----------:|-----------:|------:|:------|:---------|\n|(Intercept) |  47.0945188|  14.0946583|  79.3162041|    0.9|mean   |qi        |\n|estatura    |   0.1987756|   0.0168533|   0.3852026|    0.9|mean   |qi        |\n|sexoM       | -17.1067779| -20.5298792| -13.5971472|    0.9|mean   |qi        |\n|sigma       |  11.8219469|  10.8935085|  12.8477475|    0.9|mean   |qi        |\n\n\n:::\n:::\n\n\nSe observa que cuando se controla por el sexo, por cada centímetro más de estatura se espera un incremento en el peso de entre 0.02 y 0.39 kg, tanto para hombres como para mujeres. Por otro lado, cuando se controla por la estatura, se espera que las mujeres pesen entre 13.6 y 20.5 kg menos que los hombres.\n:::\n\n\n## Dibujo de las rectas de regresión a posteriori\n\n:::{#exm-rectas-regresion-posteriori-multiple}\nVeamos cómo dibujar 50 de las rectas de regresión obtenidas a partir de la simulación de las distribuciones a posteriori de los parámetros del modelo de regresión lineal múltiple del peso sobre la estatura y el sexo.\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\ndf |>\n  add_epred_draws(modelo_peso_estatura_sexo, ndraws = 50, value = \"Predicción_media\") |>\n  ggplot(aes(x = estatura, y = peso, color = sexo)) +\n  geom_point(data = df) +\n  geom_line(aes(y = Predicción_media, group = paste(sexo, .draw)), alpha = 0.2) +\n  labs(x = \"Estatura\", y = \"Peso\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-46-1.png){width=960}\n:::\n:::\n\n\nSe observa claramente que hay una relación positiva entre la estatura y el peso, aunque de menor magnitud que en el modelo de regresión simple, y que las mujeres tienen un peso medio menor que los hombres para la misma estatura, lo que es consistente con la experiencia.\n:::\n\n## Predicciones del modelo de regresión múltiple\n\n:::{#exm-distribucion-predictiva-regresion-multiple}\nVeamos cómo obtener la distribución a posteriori de la predicción del peso para una un hombre y una mujer de estatura 160 cm, utilizando el modelo de regresión lineal múltiple ajustado anteriormente.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndatos_nuevos <- tibble(estatura = c(160,160), sexo = c(\"H\",\"M\"))\npost_pred_160<- predicted_draws(modelo_peso_estatura_sexo, newdata = datos_nuevos, value = \"Predicción\")\nmean_qi(post_pred_160, .width = 0.9) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n| estatura|sexo | .row| Predicción|   .lower|   .upper| .width|.point |.interval |\n|--------:|:----|----:|----------:|--------:|--------:|------:|:------|:---------|\n|      160|H    |    1|   78.81856| 59.16354| 98.62678|    0.9|mean   |qi        |\n|      160|M    |    2|   61.74201| 42.10047| 81.24572|    0.9|mean   |qi        |\n\n\n:::\n:::\n\n\nUn hombre de 160 cm tendría un peso entre 59.2 y 98.6 kg con una probabilidad del 90%, mientras que una mujer de la misma estatura tendría un peso entre 42.1 y 81.2 kg. \n:::\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredicted_draws(modelo_peso_estatura_sexo, newdata = tibble(estatura = c(160,160), sexo = c(\"H\", \"M\")), value = \"Predicción\") |>\n  ggplot(aes(x = Predicción, y = sexo, color = sexo)) +\n  stat_halfeye(.width = c(0.5, 0.9), fill = \"gray90\") +\n  scale_y_discrete(labels = c(\"H\" = \"Hombre\", \"M\" = \"Mujer\")) +\n  labs(\n    title = \"Distribuciones de las predicciones del peso para personas de estatura 160 cm\",\n    x = \"Peso (kg)\", y = \"Sexo\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-48-1.png){width=960}\n:::\n:::\n\n## Distribuciones predictivas del modelo de regresión múltiple\n\n:::{#exm-distribuciones-predictivas-regresion-multiple}\nVeamos cómo obtener las distribuciones a posteriori de las predicciones del peso para todas las personas de la muestra, utilizando el modelo de regresión lineal múltiple ajustado anteriormente.\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\npost_pred <- predicted_draws(modelo_peso_estatura_sexo, newdata = df, value = \"Predicción\")\nggplot(post_pred, aes(x = estatura, y = Predicción, color = sexo)) +\n  stat_pointinterval(.width = c(0.5, 0.95), position = position_dodge(width = 0.5)) +\n  geom_point(data = df, aes(y = peso), position = position_dodge(width = 0.5)) +\n  labs(x = \"Estatura (cm)\", y = \"Peso (kg)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-49-1.png){width=960}\n:::\n:::\n\n:::\n\n## Evaluación del modelo de regresión múltiple\n\n:::{#exm-evaluacion-regresion-multiple}\nVeamos cómo obtener las métricas de evaluación del modelo de regresión lineal múltiple del peso sobre la estatura y el sexo mediante validación cruzada con 10 pliegues.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\neval_cv <- prediction_summary_cv(model = modelo_peso_estatura_sexo, data = df, k = 10, prob_outer = 0.9)\neval_cv$cv |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|      mae| mae_scaled| within_50| within_90|\n|--------:|----------:|---------:|---------:|\n| 8.387603|    0.70545|     0.495|      0.89|\n\n\n:::\n:::\n\n\nPodemos observar que el error absoluto mediano ha disminuido en 1.13 kg, lo que indica que el modelo de regresión múltiple es ligeramente mejor que el modelo de regresión simple, pero la inclusión de la variable sexo no mejora mucho la precisión del modelo.\n:::\n\n---\n\nVeamos ahora cuánto vale el coeficiente de determinación bayesiano.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_R2(modelo_peso_estatura_sexo) |>\n  mean_qi(.width = 0.9) |>\n  kable(col.names = c(\"R² medio\", \".lower\", \".upper\", \".width\", \".point\", \".interval\"))\n```\n\n::: {.cell-output-display}\n\n\n|  R² medio|    .lower|   .upper| .width|.point |.interval |\n|---------:|---------:|--------:|------:|:------|:---------|\n| 0.4169204| 0.3385185| 0.490067|    0.9|mean   |qi        |\n\n\n:::\n:::\n\n\nPodemos observar que el modelo de regresión múltiple explica alrededor del 42% de la variabilidad del peso, por lo que explica mejor la variabilidad del peso que el modelo de regresión simple.\n\n## Comparación de modelos de regresión\n\nEn general, cuantas más variables independientes agreguemos a un modelo de regresión múltiple, mayor será el coeficiente de determinación ya que la variabilidad no explicada por el modelo disminuirá. No obstante, esto no significa que el modelo sea mejor, ya que al aumentar el número de variables independientes, también aumentará el sobreajuste al conjunto de entrenamiento.\n\nPara comparar la capacidad predictiva de distintos modelos de regresión, podemos utilizar la métrica de la _densidad logarítmica predictiva esperada_ (ELPD), que penaliza la complejidad del modelo y nos permite comparar modelos de regresión con distinto número de variables independientes.\n\n## Densidad logarítmica predictiva esperada (ELPD) \n\nEsta métrica mide el logaritmo de la densidad predictiva puntual de los valores observados en los datos de prueba, según la distribución predictiva del modelo ajustado a los datos de entrenamiento.\n\nNormalmente se utiliza validación cruzada de $n$ pliegues, conocida como _leave-one-out cross-validation_ (LOO-CV), de manera que se realiza una iteración por cada caso de la muestra, reservando ese caso como conjunto de prueba y ajustando el modelo con el resto de los casos como conjunto de entrenamiento.\n\nPara cada caso $y_i$ de la muestra $(y_1, y_2, ..., y_n)$, se calcula el logaritmo de la densidad predictiva de $y_i$ según la distribución predictiva del modelo ajustado a los datos de la muestra menos $y_i$:\n\n$$\n\\mbox{lpg}_i = \\log p(y_i|y_{-i}) = \\log \\int p(y_i|\\theta)p(\\theta|y_{-i})d\\theta,\n$$\n\ndonde $y_{-i}$ es el conjunto de datos sin el caso $y_i$, $p(y_i|\\theta)$ es la densidad predictiva esperada para el valor $y_i$ dado los parámetros del modelo $\\theta$, y $p(\\theta|y_{-i})$ es la distribución a posteriori de los parámetros del modelo ajustado a los datos de entrenamiento. \n\n---\n\nFinalmente, la densidad logarítmica predictiva esperada (ELPD) se calcula como la suma de los logaritmos de las densidades predictivas de todos los casos de la muestra.\n\n:::{#def-elpd}\n## Densidad logarítmica predictiva esperada (ELPD)\nDada una muestra de datos $(y_1, y_2, ..., y_n)$, la _densidad logarítmica predictiva esperada_ (ELPD) de un modelo de regresión con parámetros $\\theta$, ajustado a los datos de entrenamiento mediante validación cruzada LOO-CV se define como\n\n$$\n\\mbox{elpd} = \\sum_{i=1}^n \\log p(y_i|y_{-i}) = \\sum_{i=1}^n \\log \\int p(y_i|\\theta)p(\\theta|y_{-i})d\\theta,\n$$\n\ndonde $y_{-i}$ es el conjunto de datos sin el caso $y_i$, $p(y_i|\\theta)$ es la densidad predictiva esperada para el valor $y_i$ dado los parámetros del modelo $\\theta$, y $p(\\theta|y_{-i})$ es la distribución a posteriori de los parámetros del modelo ajustado a los datos de entrenamiento. \n:::\n\nCuanto mayor sea el valor de la ELPD, mejor será la capacidad predictiva del modelo, por lo que podemos comparar distintos modelos de regresión mediante esta métrica.\n\n---\n\nPodemos calcular la ELPD de un modelo de regresión bayesiano ajustado con `stan_glm` mediante la función `loo` del paquete [`rstanarm`](https://mc-stan.org/loo/reference/loo.html).\n\n:::{.callout-note}\n## `loo`\n\nCalcula la densidad logarítmica predictiva esperada (ELPD) de un modelo de regresión bayesiano ajustado con `stan_glm` mediante validación cruzada LOO-CV.\n\nParámetros: \n\n- `x`: modelo de regresión bayesiano ajustado con `stan_glm`.\n:::\n\n---\n\n:::{#exm-elpd-regresion-lineal}\nVamos a calcular la ELPD del modelo de regresión lineal simple y del modelo de regresión lineal múltiple ajustados anteriormente, para comparar su capacidad predictiva.\n\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\n# ELPD del modelo de regresión lineal simple\nloo(modelo_peso_estatura)$estimates[1,] |> t() |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|  Estimate|       SE|\n|---------:|--------:|\n| -810.5134| 9.779473|\n\n\n:::\n:::\n\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\n# ELPD del modelo de regresión lineal múltiple\nloo(modelo_peso_estatura_sexo)$estimates[1,] |> t() |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|  Estimate|       SE|\n|---------:|--------:|\n| -781.8458| 9.703278|\n\n\n:::\n:::\n\n\nLa diferencia de ELPD entre ambos modelos es \n\n$$\n\\Delta \\mbox{ELPD} = -781.8 - (-810.5) = 28.7,\n$$\n\nLa diferencia no se interpreta en términos absolutos sino en relación a su error estándar. \n:::\n\n---\n\nLa función `loo_compare` del paquete [`rstanarm`](https://mc-stan.org/loo/reference/loo_compare.html) permite comparar la ELPD de varios modelos de regresión bayesianos ajustados con `stan_glm`.\n\n:::{.callout-note}\n## `loo_compare`\n\nCompara la densidad logarítmica predictiva esperada (ELPD) de varios modelos de regresión bayesianos ajustados con `stan_glm`.\n\nParámetros:\n\n- `x`: lista de ELDPs de los modelos a comparar calculados con `loo`.\n:::\n\n---\n\n:::{#exm-comparacion-elpd-regresion-lineal}\nVeamos cómo comparar la ELPD de los modelos de regresión lineal simple y múltiple ajustados anteriormente.\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nloo1 <- loo(modelo_peso_estatura)\nloo2 <- loo(modelo_peso_estatura_sexo)\nloo_compare(loo1, loo2)[,c(\"elpd_diff\", \"se_diff\")] |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|                          | elpd_diff|  se_diff|\n|:-------------------------|---------:|--------:|\n|modelo_peso_estatura_sexo |    0.0000| 0.000000|\n|modelo_peso_estatura      |  -28.6676| 6.156593|\n\n\n:::\n:::\n\n\nEn este caso la diferencia tipificada de ELDP es\n\n$$\n\\frac{\\Delta \\mbox{ELPD}}{\\mbox{SE}(\\mbox{ELPD})} = \\frac{28.7}{6.2} \\approx 4.7\n$$\n:::\n\nSe suele utilizar la regla de Vehtari:\n\n- $\\Delta \\mbox{ELPD} / \\mbox{SE}(\\mbox{ELPD}) < 2 \\rightarrow$ Diferencia no sustancial.\n- $2\\leq \\Delta \\mbox{ELPD} / \\mbox{SE}(\\mbox{ELPD}) < 4 \\rightarrow$ Diferencia moderada.\n- $\\geq 4 \\rightarrow$ Diferencia sustancial.\n\nEn este caso podemos decir que el modelo de regresión múltiple es sustancialmente mejor que el modelo de regresión simple.\n\n---\n\n:::{#exr-comparacion-elpd-regresion-lineal}\nComparar la ELPD del modelo de regresión del peso sobre el sexo con la ELPD del modelo de regresión múltiple del peso sobre la estatura y el sexo. ¿Qué conclusiones se pueden extraer de esta comparación?\n:::\n\n<details>\n<summary>**Solución**</summary>\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nloo1 <- loo(modelo_peso_sexo)\nloo2 <- loo(modelo_peso_estatura_sexo)\nloo_compare(loo1, loo2)[,c(\"elpd_diff\", \"se_diff\")] |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|                          | elpd_diff|  se_diff|\n|:-------------------------|---------:|--------:|\n|modelo_peso_sexo          |  0.000000| 0.000000|\n|modelo_peso_estatura_sexo | -1.335325| 1.758407|\n\n\n:::\n:::\n\n\nEn este caso la diferencia tipificada de ELDP es\n\n$$\n\\frac{\\Delta \\mbox{ELPD}}{\\mbox{SE}(\\mbox{ELPD})} = \\frac{1.33}{1.75} \\approx 0.76 < 2.\n$$\n\nEn este caso, aunque la diferencia entre los dos modelos no es sustancial, el modelo de regresión simple es ligéramente mejor que el modelo de regresión múltiple, por lo que la inclusión de la variable estatura no mejora la capacidad predictiva del modelo.\n\n:::{.centered}\n_¿A qué puede ser debido?_\n:::\n\n</details>\n\n## Modelos de regresión con interacciones\n\nEn un modelo de regresión múltiple sin interacción como el que hemos visto \n\n$$\nY|\\beta_0,\\beta_1,\\beta_2,\\sigma \\sim N(\\beta_0 + \\beta_1 X_1+ \\beta_2 X_2, \\sigma)\n$$\n\nse asume que la pendiente $\\beta_1$ es la misma para cualquier valor de $X_2$. En el ejemplo anterior esto quiere decir que el incremento del peso por unidad de estatura es el mismo para hombres y para mujeres. Pero esto no es cierto cuando hay _interacción_ entre las variables independientes, es decir, podría ser que el incremento de peso por unidad de estatura en hombres fuese distinto que en mujeres.\n\nCuando no hay interacción entre $X_1$ y $X_2$, las rectas de regresión correspondientes a cada valor de $X_2$ son paralelas mientras que si hay interacción no.\n\n## Construcción de un modelo de regresión con interacción\n\nSi queremos modelar la interacción entre $X_1$ y $X_2$ en un modelo de regresión múltiple, tenemos que introducir un nuevo parámetro $\\beta_3$ que como coeficiente del producto de $X_1$ y $X_2$.\n\n$$\nY|\\beta_0,\\beta_1,\\beta_2,\\beta_3,\\sigma \\sim N(\\beta_0 + \\beta_1 X_1+ \\beta_2 X_2+\\beta_3X_1X_2, \\sigma)\n$$\n\n---\n\n:::{#exm-modelo-regresión-interacción}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_peso_estatura_sexo_interaccion <- stan_glm(\n  peso ~ estatura * sexo,\n  data = df,\n  family = gaussian(),\n  prior_intercept = normal(70, 10),\n  prior = normal(location = c(1.5, -10, 0), scale = c(0.5, 5, 0.5)),\n  prior_aux = exponential(0.5),\n  chains = 4, iter = 5000 * 2, seed = 123\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_peso_estatura_sexo_interaccion |> \n  gather_draws(`(Intercept)`, estatura, sexoM, `estatura:sexoM`, sigma) |>\n  mean_qi(.width = 0.9) |> \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|.variable      |     .value|      .lower|     .upper| .width|.point |.interval |\n|:--------------|----------:|-----------:|----------:|------:|:------|:---------|\n|(Intercept)    | 54.2966726|  21.0261777| 87.7697489|    0.9|mean   |qi        |\n|estatura       |  0.1610676|  -0.0271182|  0.3481525|    0.9|mean   |qi        |\n|estatura:sexoM | -0.0575595|  -0.1104301| -0.0051531|    0.9|mean   |qi        |\n|sexoM          | -9.0730883| -17.2234483| -0.8953664|    0.9|mean   |qi        |\n|sigma          | 11.7730969|  10.8614720| 12.7728411|    0.9|mean   |qi        |\n\n\n:::\n:::\n\n\n:::\n\n## Dibujo de las rectas de regresión a posteriori\n\n:::{exm-rectas-regresion-posteriori-interaccion}\nVeamos cómo dibujar 50 de las rectas de regresión obtenidas a partir de la simulación de las distribuciones a posteriori de los parámetros del modelo de regresión lineal múltiple del peso sobre la estatura y el sexo con interacción.\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\ndf |>\n  add_epred_draws(modelo_peso_estatura_sexo_interaccion, ndraws = 50, value = \"Predicción_media\") |>\n  ggplot(aes(x = estatura, y = peso, color = sexo)) +\n  geom_point(data = df) +\n  geom_line(aes(y = Predicción_media, group = paste(sexo, .draw)), alpha = 0.2) +\n  labs(x = \"Estatura\", y = \"Peso\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-58-1.png){width=960}\n:::\n:::\n\n\nEn este caso, se observa, a pesar de incluir la interacción el el modelo, las rectas de regresión son prácticamente paralelas, lo que indica que no hay casi interacción entre la estatura y el sexo.\n:::\n\n---\n\n:::{#exr-comparacion-elpd-regresion-interaccion}\nComparar la ELPD del modelo de regresión múltiple del peso sobre la estatura y el sexo con interacción con la ELPD del modelo de regresión múltiple del peso sobre la estatura y el sexo sin interacción. ¿Qué conclusiones se pueden extraer de esta comparación?\n:::\n\n<details>\n<summary>**Solución**</summary>\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nloo1 <- loo(modelo_peso_estatura_sexo)\nloo2 <- loo(modelo_peso_estatura_sexo_interaccion)\nloo_compare(loo1, loo2)[,c(\"elpd_diff\", \"se_diff\")] |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|                                      |  elpd_diff|   se_diff|\n|:-------------------------------------|----------:|---------:|\n|modelo_peso_estatura_sexo_interaccion |  0.0000000| 0.0000000|\n|modelo_peso_estatura_sexo             | -0.6400557| 0.7860038|\n\n\n:::\n:::\n\n\nEn este caso la diferencia tipificada de ELDP es\n\n$$\n\\frac{\\Delta \\mbox{ELPD}}{\\mbox{SE}(\\mbox{ELPD})} = \\frac{0.64}{0.79}   \\approx 0.81 < 2,\n$$\n\npor lo que no hay una diferencia sustancial entre los dos modelos.\n\n</details>\n\n## {background-color= .myblue}\n\n:::{.main-title}\nRegresión logística\n:::\n\n## Variables dependientes categóricas\n\nEn todos los modelos de regresión que hemos visto hasta ahora, la variable dependiente $Y$ era una variable cuantitativa continua (el peso). Sin embargo, en muchos problemas la variable dependiente es _categórica_, y lo que queremos modelizar es la _probabilidad_ de que ocurra un determinado suceso.\n\nEn el ámbito de la Epidemiología, por ejemplo, es muy habitual querer estudiar la probabilidad de que una persona padezca una enfermedad (variable dependiente dicotómica: enfermo / sano) en función de una serie de factores de riesgo (edad, sexo, índice de masa corporal, hábitos, etc.).\n\nEn estos casos, la variable dependiente $Y$ es una variable dicotómica que toma dos valores:\n\n$$\nY = \\begin{cases} 1 & \\text{si la persona padece la enfermedad,} \\\\ 0 & \\text{si la persona no la padece.} \\end{cases}\n$$\n\nUn modelo de regresión lineal no es adecuado en este caso, ya que podría predecir valores de $Y$ por debajo de 0 o por encima de 1, que no tendrían sentido como probabilidades.\n\n## El modelo de regresión logística\n\nCuando la variable dependiente $Y$ es dicotómica, asumimos que sigue una distribución de **Bernoulli** con probabilidad de éxito $\\pi_i$ (la probabilidad de padecer la enfermedad para el individuo $i$),\n\n$$\nY_i \\mid \\pi_i \\sim \\text{Bernoulli}(\\pi_i).\n$$\n\nEl objetivo es modelizar la probabilidad $\\pi_i$ en función de las variables independientes. Como $\\pi_i$ debe estar entre 0 y 1, no podemos modelizarla directamente con una combinación lineal de las variables independientes. En su lugar, modelizamos una transformación de $\\pi_i$ conocida como _logaritmo de las odds_ (_log-odds_ o _logit_):\n\n$$\n\\text{logit}(\\pi_i) = \\log\\left(\\frac{\\pi_i}{1-\\pi_i}\\right) = \\beta_0 + \\beta_1 x_i,\n$$\n\nya que cociente $\\frac{\\pi_i}{1-\\pi_i}$ es la _odds_ de padecer la enfermedad y expresa cuántas veces es más probable padecer la enfermedad que no padecerla.\n\n## La función logística\n\nDespejando $\\pi_i$ de la ecuación anterior, obtenemos la _función logística_ (de ahí el nombre del modelo), que transforma cualquier valor real del predictor lineal en una probabilidad entre 0 y 1:\n\n$$\n\\pi_i = \\frac{e^{\\beta_0 + \\beta_1 x_i}}{1 + e^{\\beta_0 + \\beta_1 x_i}} = \\frac{1}{1 + e^{-(\\beta_0 + \\beta_1 x_i)}}.\n$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-60-1.png){fig-align='center' width=960}\n:::\n:::\n\n\nLa función logística tiene forma de S (curva sigmoide), es creciente y siempre toma valores entre 0 y 1, por lo que es ideal para modelizar probabilidades.\n\n## Interpretación de los coeficientes\n\nA diferencia de la regresión lineal, en la regresión logística los coeficientes se interpretan en la escala de las _odds_:\n\n- **Término independiente $\\beta_0$**. Es el logaritmo de la odds de padecer la enfermedad cuando $X = 0$. Es decir, $e^{\\beta_0}$ es la odds base.\n\n- **Pendiente $\\beta_1$**. Es el cambio en el logaritmo de la odds por cada unidad que se incrementa $X$. Más útil es su exponencial $e^{\\beta_1}$, conocida como _razón de odds_ (_odds ratio_), que indica por qué factor se multiplica la odds de padecer la enfermedad por cada unidad que aumenta $X$.\n\n  - Si $e^{\\beta_1} > 1$, la variable $X$ es un **factor de riesgo** (aumenta la probabilidad de enfermedad).\n  - Si $e^{\\beta_1} < 1$, la variable $X$ es un **factor de protección** (disminuye la probabilidad de enfermedad).\n  - Si $e^{\\beta_1} = 1$, la variable $X$ no influye en la probabilidad de enfermedad.\n\n## Consrucción del modelo de regresión logística\n\nEl modelo de regresión logística se especifica como \n\n\\begin{align*}\nY_i \\mid \\beta_0, \\beta_1 & \\sim \\text{Bernoulli}(\\pi_i) \\\\\n\\text{logit}(\\pi_i) & = \\beta_0 + \\beta_1 x_i\n\\end{align*}\n\n:::{.callout-warning}\nObsérvese que, a diferencia de la regresión lineal, no hay un parámetro $\\sigma$ para la desviación típica del error, ya que la variabilidad de una distribución de Bernoulli queda determinada por su probabilidad $\\pi_i$.\n:::\n\nComo siempre, asignaremos distribuciones a priori a los coeficientes del modelo, y las actualizaremos con los datos para obtener las distribuciones a posteriori.\n\n## Distribuciones a priori de los parámetros\n\nPuesto que $\\beta_0$ y $\\beta_1$ son parámetros de localización que pueden tomar cualquier valor real (están en la escala logarítmica de las odds), y por tanto, una distribución a priori adecuada para ambos es la distribución normal:\n\n\\begin{align*}\n\\beta_0 & \\sim N(\\theta_0, \\tau_0) \\\\\n\\beta_1 & \\sim N(\\theta_1, \\tau_1)\n\\end{align*}\n\nConviene tener presente que, al estar en la escala _logit_, valores aparentemente pequeños de los coeficientes pueden corresponder a cambios grandes en la probabilidad. Por ejemplo, una distribución a priori $\\beta_1 \\sim N(0, 0.5)$ ya es bastante informativa, pues asume que la razón de ventajas $e^{\\beta_1}$ está, con un 95% de probabilidad, aproximadamente entre $e^{-1} \\approx 0.37$ y $e^{1} \\approx 2.72$.\n\n---\n\n:::{#exm-datos-diabetes}\nSupongamos que queremos estudiar la **prevalencia de diabetes tipo 2** en una población adulta en función de la edad. Para ello disponemos de los datos de una cohorte de 250 personas en las que se ha registrado su edad y si padecen o no diabetes.\n\nPara este ejemplo simularemos los datos a partir de un modelo conocido, lo que nos permitirá comprobar después que el modelo bayesiano es capaz de recuperar la prevalencia real.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nset.seed(123)\nn <- 250\nedad <- round(runif(n, 30, 85))\nimc <- round(rnorm(n, 27, 4), 1)\n# Modelo real: logit(pi) = -9 + 0.07 * edad + 0.12 * imc\nprob_real <- plogis(-9 + 0.07 * edad + 0.12 * imc)\ndiabetes <- rbinom(n, size = 1, prob = prob_real)\ndf <- tibble(edad = edad, imc = imc, diabetes = diabetes)\n```\n:::\n\n:::\n\n---\n\nLa _prevalencia_ es la proporción de individuos de la población que padecen la enfermedad. En la muestra, la prevalencia observada es\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |> summarise(prevalencia = mean(diabetes)) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n| prevalencia|\n|-----------:|\n|       0.184|\n\n\n:::\n:::\n\n\nPodemos representar gráficamente la presencia de diabetes frente a la edad. Como la variable dependiente solo toma los valores 0 y 1, añadimos un pequeño ruido vertical (_jitter_) para visualizar mejor la densidad de puntos.\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nggplot(df, aes(x = edad, y = diabetes)) +\n  geom_jitter(height = 0.05, alpha = 0.4, color = myblue) +\n  labs(x = \"Edad (años)\", y = \"Diabetes (0 = No, 1 = Sí)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-63-1.png){width=960}\n:::\n:::\n\n\n---\n\nEn este contexto, optaremos por utilizar distribuciones a priori poco informativas para los parámetros del modelo, de manera que los datos tengan un peso importante en la estimación de las distribuciones a posteriori.\n\nPara $\\beta_0$ asumimos una distribución normal con media -1.5 y desviación típica 1.5, lo que implica que la odds de padecer diabetes es baja para una persona de edad media. \n\n$$\n\\beta_0 \\sim N(-1.5, 1.5)\n$$\n\nPara $\\beta_1$ asumimos una distribución normal con media 0 y desviación típica 0.5, lo que implica que el efecto de la edad sobre la probabilidad de padecer diabetes es moderado y de signo desconocido.\n\n$$\n\\beta_1 \\sim N(0, 0.5)\n$$\n\n## Ajuste del modelo de regresión logística bayesiana\n\nPara ajustar un modelo de regresión logística bayesiano usamos de nuevo la función `stan_glm` del paquete `rstanarm`, pero esta vez indicando la familia `binomial()`, que utiliza por defecto la función de enlace _logit_.\n\n\n## Validación de las distribuciones a priori\n\nComo hicimos con la regresión lineal, antes de ajustar el modelo conviene comprobar que las distribuciones a priori son razonables. Para ello ajustamos el modelo con la opción `prior_PD = TRUE`, que simula los parámetros a partir de las distribuciones a priori sin usar los datos.\n\n:::{#exm-ajuste-regresion-logistica-prior}\nVeamos comó obtener las distribuciones a priori del modelo de regresión logística de la probabilidad de diabetes sobre la edad.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rstanarm)\nset.seed(123)\nmodelo_diabetes_prior <- stan_glm(\n  diabetes ~ edad, data = df, family = binomial(),\n  prior_intercept = normal(-1.5, 1.5),\n  prior = normal(0, 0.5),\n  chains = 4, iter = 5000 * 2, seed = 123,\n  prior_PD = TRUE\n)\n```\n:::\n\n\n:::\n\n---\n\nPodemos dibujar algunas de las curvas logísticas generadas a partir de las distribuciones a priori para comprobar que cubren un rango razonable de posibilidades.\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nlibrary(tidybayes)\ntibble(edad = seq(30, 85, length.out = 50)) |>\n  add_epred_draws(modelo_diabetes_prior, ndraws = 100, value = \"prob\") |>\n  ggplot(aes(x = edad, y = prob, group = .draw)) +\n  geom_line(color = myred, alpha = 0.2) +\n  labs(title = \"100 curvas logísticas a priori\",\n       x = \"Edad (años)\", y = \"Probabilidad de diabetes\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-65-1.png){width=960}\n:::\n:::\n\n\nLas curvas a priori contemplan tanto relaciones crecientes como decrecientes con la edad, y cubren todo el rango de probabilidades, lo que indica que las distribuciones a priori son poco informativas y razonables.\n\n## Ajuste de las distribuciones a posteriori\n\nUna vez validadas las distribuciones a priori, ajustamos el modelo a los datos. De nuevo, basta con actualizar el modelo anterior con la opción `prior_PD = FALSE`.\n\n:::{#exm-ajuste-regresion-logistica}\nVeamos cómo ajustar el modelo de regresión logística a los datos de diabetes y \n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_diabetes <- update(modelo_diabetes_prior, prior_PD = FALSE)\n```\n:::\n\n:::\n\n---\n\nComprobamos la convergencia de las cadenas de Markov.\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nlibrary(bayesplot)\nmcmc_trace(modelo_diabetes, size = 0.2)\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-67-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nmcmc_dens_overlay(modelo_diabetes)\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-68-1.png){width=960}\n:::\n:::\n\n\nSe observa que las trazas de las cadenas de Markov son estables y convergentes.\n\n---\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nneff_ratio(modelo_diabetes) |> t() |> kable()\n```\n\n::: {.cell-output-display}\n\n\n| (Intercept)|    edad|\n|-----------:|-------:|\n|     0.35125| 0.37115|\n\n\n:::\n:::\n\n\nSe observa que la proporción efectiva de muestras aleatorias es razonable para ambos parámetros.  \n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nrhat(modelo_diabetes) |> t() |> kable()\n```\n\n::: {.cell-output-display}\n\n\n| (Intercept)|     edad|\n|-----------:|--------:|\n|    1.000412| 1.000317|\n\n\n:::\n:::\n\n\nLas cadenas son estables y convergentes, y el valor de $\\hat{R}$ es prácticamente 1 para ambos parámetros.\n\n## Intervalos de credibilidad \n\n:::{#exm-intervalos-credibilidad-logistica}\nObtenemos la media y los intervalos de credibilidad del 90% de las distribuciones a posteriori de los parámetros.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_diabetes |>\n  gather_draws(`(Intercept)`, edad) |>\n  mean_qi(.width = 0.9) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|.variable   |     .value|     .lower|     .upper| .width|.point |.interval |\n|:-----------|----------:|----------:|----------:|------:|:------|:---------|\n|(Intercept) | -5.7656811| -7.2786113| -4.3930719|    0.9|mean   |qi        |\n|edad        |  0.0686002|  0.0480311|  0.0907883|    0.9|mean   |qi        |\n\n\n:::\n:::\n\n\nEl coeficiente de la edad es positivo, lo que indica que a mayor edad mayor probabilidad de diabetes. \n:::\n\n## Razón de odds\n\nPara interpretarlo mejor, calculamos la razón de odds $e^{\\beta_1}$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_diabetes |>\n  gather_draws(edad) |>\n  mutate(odds_ratio = exp(.value)) |>\n  mean_qi(odds_ratio, .width = 0.9) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|.variable | odds_ratio|   .lower|   .upper| .width|.point |.interval |\n|:---------|----------:|--------:|--------:|------:|:------|:---------|\n|edad      |     1.0711| 1.049203| 1.095037|    0.9|mean   |qi        |\n\n\n:::\n:::\n\n\nEs decir, por cada año más de edad, la odds de padecer diabetes se multiplica por aproximadamente 1.07 (un incremento del 7% en la odds por año), y de acuerdo al intervalo de credibilidad estaría entre el 1.05 y 1.1 con una probabilidad del 90%.\n\n## La curva logística a posteriori\n\nCada muestra de la distribución a posteriori de los parámetros define una curva logística distinta. Podemos dibujar algunas de ellas sobre los datos para visualizar el ajuste y la incertidumbre.\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\ntibble(edad = seq(30, 85, length.out = 100)) |>\n  add_epred_draws(modelo_diabetes, ndraws = 50, value = \"prob\") |>\n  ggplot(aes(x = edad, y = prob)) +\n  geom_line(aes(group = .draw), color = myred, alpha = 0.2) +\n  geom_jitter(data = df, aes(y = diabetes), height = 0.03,\n              alpha = 0.3, color = myblue) +\n  labs(x = \"Edad (años)\", y = \"Probabilidad de diabetes\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-73-1.png){width=960}\n:::\n:::\n\n\nSe observa claramente cómo la probabilidad de padecer diabetes aumenta con la edad, siguiendo una curva en forma de S.\n\n## Estimación de la prevalencia\n\nYa hemos visto que la estimación de un parámetro en Estadística bayesiana es su propia distribución a posteriori, aunque habitualmente la describiremos mediante su media o mediana y los intervalos de credibilidad para el parámetro.\n\n:::{#exm-prevalencia-logistica}\n\nPara estimar la prevalancia de la diabetes calculamos, para cada muestra de la distribución a posteriori, la probabilidad media de diabetes en toda la muestra.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |>\n  add_epred_draws(modelo_diabetes, value = \"prob\") |>\n  group_by(.draw) |>\n  summarise(prevalencia = mean(prob)) |>\n  mean_qi(prevalencia, .width = 0.9) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| prevalencia|    .lower|    .upper| .width|.point |.interval |\n|-----------:|---------:|---------:|------:|:------|:---------|\n|   0.1873307| 0.1500819| 0.2259585|    0.9|mean   |qi        |\n\n\n:::\n:::\n\n\nLa prevalencia estimada de diabetes en la población es de aproximadamente el 18.7%, con un intervalo de credibilidad del 90% que va del 15% al 22.6%.\n:::\n\n## Predicción de la probabilidad para nuevos casos\n\nPara predecir la probabilidad media de padecer la enfermedad de nuevos individuos, usamos la función `epred_draws`, que genera la distribución a posteriori de la probabilidad $\\pi$ para cada nuevo caso.\n\n:::{#exm-prediccion-probabilidad-logistica}\nVeamos la probabilidad de padecer diabetes para personas de 40, 60 y 80 años.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnuevos <- tibble(edad = c(40, 60, 80))\nepred_draws(modelo_diabetes, newdata = nuevos, value = \"prob\") |>\n  mean_qi(.width = 0.9) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| edad| .row|      prob|    .lower|    .upper| .width|.point |.interval |\n|----:|----:|---------:|---------:|---------:|------:|:------|:---------|\n|   40|    1| 0.0494743| 0.0241763| 0.0815658|    0.9|mean   |qi        |\n|   60|    2| 0.1629089| 0.1206937| 0.2077878|    0.9|mean   |qi        |\n|   80|    3| 0.4320676| 0.3343698| 0.5338063|    0.9|mean   |qi        |\n\n\n:::\n:::\n\n\nMientras que para una persona de 40 años la probabilidad de padecer diabetes es baja (entre 0.02 y 0.08), para una de 80 años es considerablemente mayor (entre 0.33 y 0.53).\n:::\n\n---\n\nPodemos representar gráficamente estas distribuciones a posteriori de la probabilidad.\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nepred_draws(modelo_diabetes, newdata = nuevos, value = \"prob\") |>\n  mutate(edad = factor(edad)) |>\n  ggplot(aes(x = prob, y = edad, fill = edad)) +\n  stat_halfeye(.width = 0.9, alpha = 0.6) +\n  labs(x = \"Probabilidad de diabetes\", y = \"Edad (años)\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](04-regresion-bayesiana_files/figure-revealjs/unnamed-chunk-76-1.png){width=960}\n:::\n:::\n\n\n## Clasificación de nuevos casos\n\nAdemás de predecir la probabilidad de padecer la enfermedad, a menudo queremos _clasificar_ a cada individuo en una de las dos categorías (enfermo / sano). Para ello fijamos un _umbral de clasificación_ (_cutoff_), de manera que si la probabilidad estimada supera ese umbral clasificamos al individuo como enfermo.\n\nEl umbral más habitual es 0.5, pero puede ajustarse en función del coste relativo de los errores: en cribados de enfermedades graves se suele bajar el umbral para no dejar pasar posibles enfermos (aumentar la sensibilidad).\n\nPara obtener las clases predichas usamos `predicted_draws`, que simula valores 0/1 de la distribución de Bernoulli para cada caso. La proporción de unos es una estimación de la probabilidad.\n\n---\n\n:::{#exm-clasificacion-logistica}\nClasifiquemos a las personas de 40, 60 y 80 años usando un umbral de 0.4.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredicted_draws(modelo_diabetes, newdata = nuevos, value = \"clase\") |>\n  group_by(edad) |>\n  summarise(prob_diabetes = mean(clase)) |>\n  mutate(clasificacion = if_else(prob_diabetes > 0.4, \"Enfermo\", \"Sano\")) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| edad| prob_diabetes|clasificacion |\n|----:|-------------:|:-------------|\n|   40|       0.05070|Sano          |\n|   60|       0.16340|Sano          |\n|   80|       0.42795|Enfermo       |\n\n\n:::\n:::\n\n\nCon el umbral de 0.4, solo las personas de 80 años serían clasificadas como enfermas.\n:::\n\n## Evaluación del modelo: matriz de confusión\n\nPara evaluar la capacidad de clasificación del modelo, comparamos las clases predichas con las clases observadas en los datos, construyendo una **matriz de confusión** que clasifica cada caso como:\n\n::::{.columns}\n::: {.column width=\"50%\"}\n- **Verdadero positivo (VP)**: enfermo clasificado como enfermo.\n- **Verdadero negativo (VN)**: sano clasificado como sano.\n:::\n\n::: {.column width=\"50%\"}\n- **Falso positivo (FP)**: sano clasificado como enfermo.\n- **Falso negativo (FN)**: enfermo clasificado como sano.\n:::\n::::\n\nA partir de la matriz de confusión se calculan las siguientes métricas:\n\n- **Sensibilidad** $= \\dfrac{VP}{VP + FN}$: proporción de enfermos correctamente clasificados.\n- **Especificidad** $= \\dfrac{VN}{VN + FP}$: proporción de sanos correctamente clasificados.\n- **Exactitud** (_accuracy_) $= \\dfrac{VP + VN}{VP + VN + FP + FN}$: proporción total de aciertos.\n\n## Cálculo de las métricas de clasificación\n\nPara calcular la matriz de confusión y las métricas de clasificación de un modelo de regresión logística bayesiano, podemos usar la función `classification_summary` del paquete `bayesrules`.\n\n:::{.callout-note}\n## `classification_summary`\n\nDevuelve la matriz de confusión y las métricas de sensibilidad, especificidad y exactitud de un modelo de clasificación bayesiano.\n\nParámetros:\n\n- `model`: modelo ajustado con `stan_glm`.\n- `data`: conjunto de datos con la variable dependiente y las variables independientes.\n- `cutoff`: umbral de clasificación. Por defecto 0.5.\n:::\n\n---\n\n:::{#exm-evaluacion-logistica}\nCalculemos la matriz de confusión y las métricas de clasificación del modelo de regresión logística de la diabetes sobre la edad, con un umbral de 0.4.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(bayesrules)\nset.seed(123)\nclasificacion <- classification_summary(model = modelo_diabetes, data = df, cutoff = 0.4)\nclasificacion$confusion_matrix |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|  y|   0|  1|\n|--:|---:|--:|\n|  0| 187| 18|\n|  1|  29| 16|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclasificacion$accuracy_rates |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|                 |          |\n|:----------------|---------:|\n|sensitivity      | 0.0222222|\n|specificity      | 0.9853659|\n|overall_accuracy | 0.8120000|\n\n\n:::\n:::\n\n\nLa exactitud global es alta, pero observamos que la sensibilidad es baja: con el umbral de 0.4 el modelo clasifica bien a los sanos (especificidad alta), pero deja sin detectar a muchos enfermos. Esto es habitual cuando la enfermedad es poco prevalente.\n:::\n\n## Ajuste del umbral de clasificación\n\nCuando interesa detectar el mayor número posible de enfermos (por ejemplo, en un cribado), podemos bajar el umbral de clasificación para aumentar la sensibilidad, a costa de reducir la especificidad.\n\n:::{#exm-umbral-logistica}\nRepitamos la evaluación bajando el umbral a 0.2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nclassification_summary(model = modelo_diabetes, data = df, cutoff = 0.2)$accuracy_rates |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|                 |          |\n|:----------------|---------:|\n|sensitivity      | 0.7333333|\n|specificity      | 0.6975610|\n|overall_accuracy | 0.7040000|\n\n\n:::\n:::\n\n\nAl bajar el umbral, la sensibilidad aumenta (detectamos más enfermos), pero la especificidad disminuye (clasificamos como enfermos a más sanos). La elección del umbral depende del coste relativo de los falsos positivos y los falsos negativos.\n:::\n\n## Evaluación mediante validación cruzada\n\nAl igual que en la regresión lineal, las métricas calculadas sobre el propio conjunto de datos tienden a ser optimistas debido al sobreajuste. Para obtener una estimación más realista usamos **validación cruzada** con la función `classification_summary_cv` del paquete `bayesrules`.\n\n:::{.callout-note}\n## `classification_summary_cv`\n\nDevuelve las métricas de clasificación de un modelo bayesiano mediante validación cruzada.\n\nParámetros:\n\n- `model`: modelo ajustado con `stan_glm`.\n- `data`: conjunto de datos.\n- `k`: número de pliegues.\n- `cutoff`: umbral de clasificación. Por defecto 0.5.\n:::\n\n---\n\n:::{#exm-evaluacion-cv-logistica}\nEvaluemos el modelo mediante validación cruzada con 10 pliegues.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\ncv_diabetes <- classification_summary_cv(model = modelo_diabetes, data = df, k = 10, cutoff = 0.4)\ncv_diabetes$cv |> kable()\n```\n\n::: {.cell-output-display}\n\n\n| sensitivity| specificity| overall_accuracy|\n|-----------:|-----------:|----------------:|\n|   0.1958333|   0.9076722|            0.792|\n\n\n:::\n:::\n\n\nLas métricas obtenidas por validación cruzada son ligeramente peores que las obtenidas sobre el conjunto de entrenamiento, lo que da una idea más realista de la capacidad predictiva del modelo sobre datos nuevos.\n:::\n\n## {background-color= .myblue}\n\n:::{.main-title}\nRegresión logística múltiple\n:::\n\n## Regresión logística múltiple\n\nAl igual que en la regresión lineal, podemos incluir varias variables independientes en el modelo de regresión logística para mejorar la predicción de la probabilidad de padecer la enfermedad:\n\n$$\n\\text{logit}(\\pi_i) = \\beta_0 + \\beta_1 x_{1i} + \\beta_2 x_{2i} + \\cdots + \\beta_p x_{pi}.\n$$\n\nCada coeficiente $\\beta_j$ se interpreta como el cambio en el logaritmo de la odds por cada unidad que aumenta la variable $X_j$, manteniendo constantes las demás variables, y su exponencial $e^{\\beta_j}$ es la razón de odds ajustada por el resto de factores de riesgo.\n\n---\n\n:::{#exr-regresion-logistica-multiple}\nAjustar un modelo de regresión logística múltiple para predecir la probabilidad de padecer diabetes en función de la edad y del índice de masa corporal (IMC), usando el conjunto de datos simulado anteriormente. Comparar su capacidad predictiva con la del modelo que solo incluye la edad mediante la ELPD.\n:::\n\n---\n\n<details>\n<summary>**Solución**</summary>\n\nAjustamos el modelo de regresión logística múltiple añadiendo el IMC como variable independiente.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nmodelo_diabetes_imc <- stan_glm(\n  diabetes ~ edad + imc, data = df, family = binomial(),\n  prior_intercept = normal(-1.5, 1.5),\n  prior = normal(0, 0.5),\n  chains = 4, iter = 5000 * 2, seed = 123\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_diabetes_imc |>\n  gather_draws(`(Intercept)`, edad, imc) |>\n  mean_qi(.width = 0.9) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|.variable   |     .value|      .lower|     .upper| .width|.point |.interval |\n|:-----------|----------:|-----------:|----------:|------:|:------|:---------|\n|(Intercept) | -9.3779220| -12.3025425| -6.6186382|    0.9|mean   |qi        |\n|edad        |  0.0745930|   0.0522112|  0.0987754|    0.9|mean   |qi        |\n|imc         |  0.1139061|   0.0375163|  0.1912513|    0.9|mean   |qi        |\n\n\n:::\n:::\n\n\nTanto la edad como el IMC tienen coeficientes positivos, lo que indica que ambos son factores de riesgo para la diabetes.\n\n</details>\n\n---\n\n<details>\n<summary>**Solución (continuación)**</summary>\n\nComparamos los dos modelos mediante la ELPD usando validación cruzada LOO-CV.\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nloo_edad <- loo(modelo_diabetes)\nloo_edad_imc <- loo(modelo_diabetes_imc)\nloo_compare(loo_edad, loo_edad_imc)[, c(\"elpd_diff\", \"se_diff\")] |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|                    | elpd_diff| se_diff|\n|:-------------------|---------:|-------:|\n|modelo_diabetes_imc |  0.000000|  0.0000|\n|modelo_diabetes     | -2.990543| 14.1705|\n\n\n:::\n:::\n\n\nEl modelo que incluye el IMC tiene una ELPD mayor, lo que indica que la inclusión del IMC mejora la capacidad predictiva del modelo, algo coherente con el hecho de que generamos los datos a partir de un modelo que dependía tanto de la edad como del IMC.\n\n</details>",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}