<!DOCTYPE html>
<html lang="es"><head>
<script src="02-regla-bayes_files/libs/clipboard/clipboard.min.js"></script>
<script src="02-regla-bayes_files/libs/quarto-html/tabby.min.js"></script>
<script src="02-regla-bayes_files/libs/quarto-html/popper.min.js"></script>
<script src="02-regla-bayes_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="02-regla-bayes_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="02-regla-bayes_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="02-regla-bayes_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<link href="02-regla-bayes_files/libs/quarto-contrib/fontawesome6-6.7.2/all.min.css" rel="stylesheet">
<link href="02-regla-bayes_files/libs/quarto-contrib/fontawesome6-6.7.2/latex-fontsize.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Alfredo Sánchez Alberca &nbsp;   ">
  <title>Introducción a la Estadística bayesiana</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="02-regla-bayes_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="02-regla-bayes_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="02-regla-bayes_files/libs/revealjs/dist/theme/quarto-310361485e3443f230591f918f692d18.css">
  <link href="02-regla-bayes_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="02-regla-bayes_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="02-regla-bayes_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="02-regla-bayes_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Introducción a la Estadística bayesiana</h1>
  <p class="subtitle">Regla de Bayes. Distribuciones a priori, funciones de verosimilitud y distribuciones a posteriori</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Alfredo Sánchez Alberca &nbsp; <a href="mailto:asalber@ceu.es"><i class="fa-solid fa-envelope" aria-label="envelope"></i></a> <a href="https://www.linkedin.com/in/asalber/"><i class="fa-brands fa-linkedin" aria-label="linkedin"></i></a> <a href="https://aprendeconalf.es"><i class="fa-solid fa-home" aria-label="home"></i></a> 
</div>
</div>
</div>

</section>
<section id="section" class="slide level2 myblue" data-background-color="">
<h2></h2>
<div class="main-title">
<p>Regla de Bayes</p>
</div>
</section>
<section id="section-1" class="slide level2">
<h2></h2>
<div id="def-sistema-completo-sucesos" class="theorem definition">
<p><span class="theorem-title"><strong>Definición 1 (Sistema completo de sucesos)</strong></span> Una colección de sucesos <span class="math inline">\(A_1,A_2,\ldots,A_n\)</span> de un mismo espacio muestral <span class="math inline">\(\Omega\)</span> es un <em>sistema completo</em> si cumple las siguientes condiciones:</p>
<ol type="1">
<li><p>La unión de todos es el espacio muestral: <span class="math inline">\(A_1\cup \cdots\cup A_n =\Omega\)</span>.</p></li>
<li><p>Son incompatibles dos a dos: <span class="math inline">\(A_i\cap A_j = \emptyset\)</span> <span class="math inline">\(\forall i\neq j\)</span>.</p></li>
</ol>
</div>
<p>En realidad un sistema completo de sucesos es una partición del espacio muestral de acuerdo a algún atributo, como por ejemplo el sexo o el grupo sanguíneo.</p>
</section>
<section id="teorema-de-la-probabilidad-total" class="slide level2">
<h2>Teorema de la probabilidad total</h2>
<p>Conocer las probabilidades de un determinado suceso en cada una de las partes de un sistema completo puede ser útil para calcular su probabilidad.</p>
<div id="thm-probabilidad-total" class="theorem">
<p><span class="theorem-title"><strong>Teorema 1 (Probabilidad total)</strong></span> Dado un sistema completo de sucesos <span class="math inline">\(A_1,\ldots,A_n\)</span> y un suceso <span class="math inline">\(B\)</span> de un espacio muestral <span class="math inline">\(\Omega\)</span>, la probabilidad de cualquier suceso <span class="math inline">\(B\)</span> del espacio muestral se puede calcular mediante la fórmula</p>
<p><span class="math display">\[P(B) = \sum_{i=1}^n P(A_i\cap B) = \sum_{i=1}^n P(A_i)P(B|A_i).\]</span></p>
</div>
</section>
<section class="slide level2">

<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/01-probabilidad/probabilidad_total.png" height="500"></p>
<figcaption>Teorema de la probabilidad total.</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<div id="exm-probabilidad-total" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 1</strong></span> Un test diagnóstico para una enfermedad <span class="math inline">\(E\)</span> tiene una sensibilidad del 90% y una especificidad del 95%, es decir,</p>
<p><span class="math display">\[
P(+|E)=0.9 \quad \mbox{y} \quad P(-|\overline{E})=0.95.
\]</span></p>
<p>Si la prevalencia de la enfermedad en una población es del 10%, ¿qué porcentaje de positivos se espera en una muestra aleatoria de la población?</p>
<p><br></p>
<div class="columns">
<div class="column" style="width:40%;">
<div style="margin:auto;">
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Enfermo</th>
<th style="text-align: center;">No enfermo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(+\)</span></td>
<td style="text-align: center;">0.090</td>
<td style="text-align: center;">0.045</td>
</tr>
<tr class="even">
<td><span class="math inline">\(-\)</span></td>
<td style="text-align: center;">0.010</td>
<td style="text-align: center;">0.855</td>
</tr>
<tr class="odd">
<td></td>
<td style="text-align: center;">0.1</td>
<td style="text-align: center;">0.9</td>
</tr>
</tbody>
</table>
</div>
</div><div class="column" style="width:60%;">
<p><img data-src="img/01-probabilidad/arbol_probabilidad_test_diagnostico.png" width="500"></p>
</div></div>
</div>
</section>
<section class="slide level2">

<p>Para responder a la pregunta se puede aplicar el teorema de la probabilidad total usando el sistema completo <span class="math inline">\(\{E,\overline{E}\}\)</span>:</p>
<div style="width:40%; margin:auto;">
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 4%">
<col style="width: 37%">
<col style="width: 54%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Enfermo</th>
<th style="text-align: center;">No enfermo</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(+\)</span></td>
<td style="text-align: center;"><span style="color:red;">0.090</span></td>
<td style="text-align: center;"><span style="color:red;">0.045</span></td>
<td><span style="color:red;">0.135</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(-\)</span></td>
<td style="text-align: center;">0.010</td>
<td style="text-align: center;">0.855</td>
<td>0.864</td>
</tr>
<tr class="odd">
<td></td>
<td style="text-align: center;">0.1</td>
<td style="text-align: center;">0.9</td>
<td></td>
</tr>
</tbody>
</table>
</div>
<p><span class="math display">\[
P(+) = P(E)P(+|E)+P(\overline E)P(+|\overline E) = 0.1\cdot 0.9 + 0.9\cdot 0.05 = 0.135.
\]</span></p>
<p>Es decir, alrededor del 13.5% de los resultados del test serán positivos.</p>
<p><em>¡En el fondo se trata de una media ponderada de probabilidades!</em></p>
</section>
<section id="teorema-de-bayes" class="slide level2">
<h2>Teorema de Bayes</h2>
<p>Los sucesos de un sistema completo de sucesos <span class="math inline">\(A_1,\cdots,A_n\)</span> también pueden verse como las distintas hipótesis ante un determinado hecho <span class="math inline">\(B\)</span>.</p>
<p>En estas condiciones resulta útil poder calcular las probabilidades a posteriori <span class="math inline">\(P(A_i|B)\)</span> de cada una de las hipótesis.</p>
<div id="thm-bayes" class="theorem">
<p><span class="theorem-title"><strong>Teorema 2 (Bayes)</strong></span> Dado un sistema completo de sucesos <span class="math inline">\(A_1,\ldots,A_n\)</span> y un suceso <span class="math inline">\(B\)</span> de un espacio muestral <span class="math inline">\(\Omega\)</span> y otro suceso <span class="math inline">\(B\)</span> del mismo espacio muestral, la probabilidad de cada suceso <span class="math inline">\(A_i\)</span> <span class="math inline">\(i=1,\ldots,n\)</span> condicionada por <span class="math inline">\(B\)</span> puede calcularse con la siguiente fórmula</p>
<p><span class="math display">\[P(A_i|B) = \frac{P(A_i\cap B)}{P(B)} = \frac{P(A_i)P(B|A_i)}{\sum_{i=1}^n P(A_i)P(B|A_i)}.\]</span></p>
</div>
</section>
<section class="slide level2">

<div id="exm-teorema-bayes" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 2</strong></span> En el ejemplo anterior, una pregunta más interesante es qué diagnosticar a una persona que ha dado positivo en el test.</p>
<p>En este caso se puede interpretar <span class="math inline">\(E\)</span> y <span class="math inline">\(\overline{E}\)</span> como las dos posibles hipótesis para el resultado positivo del test.</p>
<p><strong>Probabilidades a priori</strong> (sin información sobre el síntoma)</p>
<p><span class="math display">\[
P(E)=0.1 \quad \mbox{y}\quad P(\overline E)=0.9
\]</span></p>
<p>Sin información el diagnóstico sería que no tiene la enfermedad.</p>
</div>
</section>
<section class="slide level2">

<p>Sin embargo, si al realizar el test a una persona se obtiene un resultado positivo, dicha información condiciona a las hipótesis, y para decidir entre ellas es necesario calcular sus probabilidades a posteriori, es decir, <span class="math inline">\(P(E|+)\)</span> y <span class="math inline">\(P(\overline{E}|+)\)</span>.</p>
<p><strong>Probabilidades a posteriori</strong> (condicionando por el síntoma)</p>
<div style="width:40%; margin:auto;">
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 4%">
<col style="width: 37%">
<col style="width: 54%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Enfermo</th>
<th style="text-align: center;">No enfermo</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(+\)</span></td>
<td style="text-align: center;"><span style="color:#0099CC;">0.090</span></td>
<td style="text-align: center;"><span style="color:#ff2152;">0.045</span></td>
<td><span style="color:#03BF3D;">0.135</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(-\)</span></td>
<td style="text-align: center;">0.010</td>
<td style="text-align: center;">0.855</td>
<td>0.864</td>
</tr>
<tr class="odd">
<td></td>
<td style="text-align: center;">0.1</td>
<td style="text-align: center;">0.9</td>
<td></td>
</tr>
</tbody>
</table>
</div>
<p><span class="math display">\[\begin{align*}
P(E|+) &amp;= \frac{P(E)P(+|E)}{P(E)P(+|E)+P(\overline{E})P(+|\overline{E})} = \frac{0.1\cdot 0.9}{0.1\cdot 0.9 + 0.9\cdot 0.05} = \frac{\textcolor{#0099CC}{0.09}}{\textcolor{#03BF3D}{0.135}}=0.667,\\
P(\overline{E}|+) &amp;= \frac{P(\overline{E})P(+|\overline{E})}{P(E)P(+|E)+P(\overline{E})P(+|\overline{E})} = \frac{0.9\cdot 0.05}{0.1\cdot 0.9 + 0.9\cdot 0.05} = \frac{\textcolor{#ff2152}{0.045}}{\textcolor{#03BF3D}{0.135}}=0.333.
\end{align*}\]</span></p>
<p>Con un resultado positivo en el test, la probabilidad de tener la enfermedad ha aumentado y ahora el diagnóstico sería que tiene la enfermedad.</p>
</section>
<section class="slide level2">

<div id="exr-teorema-bayes" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 1</strong></span> Se dispone de dos test <span class="math inline">\(A\)</span> y <span class="math inline">\(B\)</span> para diagnosticar una enfermedad con una prevalencia del 1% en la población. El test <span class="math inline">\(A\)</span> tiene una sensibilidad del 98% y una especificidad del 80%, mientras que el test <span class="math inline">\(B\)</span> tiene una sensibilidad del 75% y una especificidad del 99%.</p>
<ol type="a">
<li>¿Cuál de los dos test funcionaría mejor como test de cribado?</li>
<li>Si aplicamos el test de cribado a una persona y da positivo, ¿cuál es la probabilidad de que esté enferma? ¿Qué diagnosticaríamos?</li>
<li>Si aplicamos a una persona el test de cribado primero y luego el otro test y ambos dan positivo, ¿cuál es la probabilidad de que esté enferma? ¿Qué diagnosticaríamos?</li>
</ol>
</div>
</section>
<section id="regla-de-bayes" class="slide level2">
<h2>Regla de Bayes</h2>
<p>En terminología bayesiana, si <span class="math inline">\(H\)</span> representa una hipótesis y <span class="math inline">\(D\)</span> representa los datos observados, entonces el teorema de Bayes se puede expresar como la siguiente regla de actualización de la probabilidad de la hipótesis <span class="math inline">\(H\)</span> dada la evidencia <span class="math inline">\(D\)</span>:</p>
<p><br></p>
<div class="centered">
<p><span class="myblue fragment" style="margin-right: 2em;" data-fragment-index="1">Probabilidad a posteriori</span> <span class="myred fragment" style="margin-right: 2em;" data-fragment-index="2">Probabilidad a priori</span> <span class="mygreen fragment" style="margin-right: 2em;" data-fragment-index="3">Verosimilitud</span></p>
</div>
<div style="position: relative; height: 100px;">
<p><style>
.arrow-anim-314308-path {
  stroke-dasharray: 2000;
  stroke-dashoffset: 2000;
}
.arrow-anim-314308-marker {
  opacity: 0;
}
.fragment.visible .arrow-anim-314308-path {
  animation: arrow-anim-314308-draw 0.50s ease forwards;
}
.fragment.visible .arrow-anim-314308-marker {
  animation: arrow-anim-314308-marker-appear 0.1s ease forwards;
  animation-delay: 0.05s;
}
@keyframes arrow-anim-314308-draw {
  to { stroke-dashoffset: 0; }
}
@keyframes arrow-anim-314308-marker-appear {
  to { opacity: 1; }
}
@media (prefers-reduced-motion: reduce) {
  .arrow-anim-314308-path {
    stroke-dasharray: none;
    stroke-dashoffset: 0;
  }
  .arrow-anim-314308-marker {
    opacity: 1;
  }
  .fragment.visible .arrow-anim-314308-path,
  .fragment.visible .arrow-anim-314308-marker {
    animation: none;
  }
}
</style><span class="fragment custom" data-fragment-index="1"></span></p><div style="position: absolute; left: 230.0px; top: -20.0px; pointer-events: none; z-index: 9999;"><svg width="170.0" height="140.0" viewbox="0 0 170.0 140.0" xmlns="http://www.w3.org/2000/svg" style="overflow: visible;"><defs><marker id="arrow-562762" markerwidth="10" markerheight="10" refx="0" refy="5.0" orient="auto-start-reverse" markerunits="strokeWidth"><path class="arrow-anim-314308-marker" d="M 0 0 L 10 5.0 L 0 10 z" fill="#0099CC"></path></marker></defs><path class="arrow-anim-314308-path" d="M 20.0,20.0 L 150.0,120.0" stroke="#0099CC" stroke-width="2" fill="none" marker-end="url(#arrow-562762)"></path></svg></div> <style>
.arrow-anim-151406-path {
  stroke-dasharray: 2000;
  stroke-dashoffset: 2000;
}
.arrow-anim-151406-marker {
  opacity: 0;
}
.fragment.visible .arrow-anim-151406-path {
  animation: arrow-anim-151406-draw 0.50s ease forwards;
}
.fragment.visible .arrow-anim-151406-marker {
  animation: arrow-anim-151406-marker-appear 0.1s ease forwards;
  animation-delay: 0.05s;
}
@keyframes arrow-anim-151406-draw {
  to { stroke-dashoffset: 0; }
}
@keyframes arrow-anim-151406-marker-appear {
  to { opacity: 1; }
}
@media (prefers-reduced-motion: reduce) {
  .arrow-anim-151406-path {
    stroke-dasharray: none;
    stroke-dashoffset: 0;
  }
  .arrow-anim-151406-marker {
    opacity: 1;
  }
  .fragment.visible .arrow-anim-151406-path,
  .fragment.visible .arrow-anim-151406-marker {
    animation: none;
  }
}
</style><span class="fragment custom" data-fragment-index="2"><div style="position: absolute; left: 520.0px; top: -20.0px; pointer-events: none; z-index: 9999;"><svg width="40.0" height="140.0" viewbox="0 0 40.0 140.0" xmlns="http://www.w3.org/2000/svg" style="overflow: visible;"><defs><marker id="arrow-601871" markerwidth="10" markerheight="10" refx="0" refy="5.0" orient="auto-start-reverse" markerunits="strokeWidth"><path class="arrow-anim-151406-marker" d="M 0 0 L 10 5.0 L 0 10 z" fill="#ff2152"></path></marker></defs><path class="arrow-anim-151406-path" d="M 20.0,20.0 L 20.0,120.0" stroke="#ff2152" stroke-width="2" fill="none" marker-end="url(#arrow-601871)"></path></svg></div></span> <style>
.arrow-anim-768077-path {
  stroke-dasharray: 2000;
  stroke-dashoffset: 2000;
}
.arrow-anim-768077-marker {
  opacity: 0;
}
.fragment.visible .arrow-anim-768077-path {
  animation: arrow-anim-768077-draw 0.50s ease forwards;
}
.fragment.visible .arrow-anim-768077-marker {
  animation: arrow-anim-768077-marker-appear 0.1s ease forwards;
  animation-delay: 0.05s;
}
@keyframes arrow-anim-768077-draw {
  to { stroke-dashoffset: 0; }
}
@keyframes arrow-anim-768077-marker-appear {
  to { opacity: 1; }
}
@media (prefers-reduced-motion: reduce) {
  .arrow-anim-768077-path {
    stroke-dasharray: none;
    stroke-dashoffset: 0;
  }
  .arrow-anim-768077-marker {
    opacity: 1;
  }
  .fragment.visible .arrow-anim-768077-path,
  .fragment.visible .arrow-anim-768077-marker {
    animation: none;
  }
}
</style><span class="fragment custom" data-fragment-index="3"><div style="position: absolute; left: 680.0px; top: -20.0px; pointer-events: none; z-index: 9999;"><svg width="140.0" height="140.0" viewbox="0 0 140.0 140.0" xmlns="http://www.w3.org/2000/svg" style="overflow: visible;"><defs><marker id="arrow-585002" markerwidth="10" markerheight="10" refx="0" refy="5.0" orient="auto-start-reverse" markerunits="strokeWidth"><path class="arrow-anim-768077-marker" d="M 0 0 L 10 5.0 L 0 10 z" fill="#03BF3D"></path></marker></defs><path class="arrow-anim-768077-path" d="M 120.0,20.0 L 20.0,120.0" stroke="#03BF3D" stroke-width="2" fill="none" marker-end="url(#arrow-585002)"></path></svg></div></span> <style>
.arrow-anim-207296-path {
  stroke-dasharray: 2000;
  stroke-dashoffset: 2000;
}
.arrow-anim-207296-marker {
  opacity: 0;
}
.fragment.visible .arrow-anim-207296-path {
  animation: arrow-anim-207296-draw 0.50s ease forwards;
}
.fragment.visible .arrow-anim-207296-marker {
  animation: arrow-anim-207296-marker-appear 0.1s ease forwards;
  animation-delay: 0.05s;
}
@keyframes arrow-anim-207296-draw {
  to { stroke-dashoffset: 0; }
}
@keyframes arrow-anim-207296-marker-appear {
  to { opacity: 1; }
}
@media (prefers-reduced-motion: reduce) {
  .arrow-anim-207296-path {
    stroke-dasharray: none;
    stroke-dashoffset: 0;
  }
  .arrow-anim-207296-marker {
    opacity: 1;
  }
  .fragment.visible .arrow-anim-207296-path,
  .fragment.visible .arrow-anim-207296-marker {
    animation: none;
  }
}
</style><span class="fragment custom" data-fragment-index="1"><div style="position: absolute; left: 230.0px; top: -20.0px; pointer-events: none; z-index: 9999;"><svg width="170.0" height="140.0" viewbox="0 0 170.0 140.0" xmlns="http://www.w3.org/2000/svg" style="overflow: visible;"><defs><marker id="arrow-790718" markerwidth="10" markerheight="10" refx="0" refy="5.0" orient="auto-start-reverse" markerunits="strokeWidth"><path class="arrow-anim-207296-marker" d="M 0 0 L 10 5.0 L 0 10 z" fill="#0099CC"></path></marker></defs><path class="arrow-anim-207296-path" d="M 20.0,20.0 L 150.0,120.0" stroke="#0099CC" stroke-width="2" fill="none" marker-end="url(#arrow-790718)"></path></svg></div></span><p></p>
</div>
<p><span class="math display">\[
\textcolor{#0099CC}{P(H|D)} = \frac{\textcolor{#ff2152}{P(H)}\times \textcolor{#03BF3D}{P(D|H)}}{P(D)}
\]</span></p>
<div style="position: relative; height: 100px;">
<style>
.arrow-anim-404979-path {
  stroke-dasharray: 2000;
  stroke-dashoffset: 2000;
}
.arrow-anim-404979-marker {
  opacity: 0;
}
.fragment.visible .arrow-anim-404979-path {
  animation: arrow-anim-404979-draw 0.50s ease forwards;
}
.fragment.visible .arrow-anim-404979-marker {
  animation: arrow-anim-404979-marker-appear 0.1s ease forwards;
  animation-delay: 0.05s;
}
@keyframes arrow-anim-404979-draw {
  to { stroke-dashoffset: 0; }
}
@keyframes arrow-anim-404979-marker-appear {
  to { opacity: 1; }
}
@media (prefers-reduced-motion: reduce) {
  .arrow-anim-404979-path {
    stroke-dasharray: none;
    stroke-dashoffset: 0;
  }
  .arrow-anim-404979-marker {
    opacity: 1;
  }
  .fragment.visible .arrow-anim-404979-path,
  .fragment.visible .arrow-anim-404979-marker {
    animation: none;
  }
}
</style><span class="fragment custom" data-fragment-index="4"><div style="position: absolute; left: 550.0px; top: -20.0px; pointer-events: none; z-index: 9999;"><svg width="40.0" height="140.0" viewbox="0 0 40.0 140.0" xmlns="http://www.w3.org/2000/svg" style="overflow: visible;"><defs><marker id="arrow-327986" markerwidth="10" markerheight="10" refx="0" refy="5.0" orient="auto-start-reverse" markerunits="strokeWidth"><path class="arrow-anim-404979-marker" d="M 0 0 L 10 5.0 L 0 10 z" fill="black"></path></marker></defs><path class="arrow-anim-404979-path" d="M 20.0,120.0 L 20.0,20.0" stroke="black" stroke-width="2" fill="none" marker-end="url(#arrow-327986)"></path></svg></div></span>
</div>
<div class="centered">
<p><span class="fragment" data-fragment-index="4">Evidencia marginal (normalizador)</span></p>
</div>
</section>
<section id="función-de-verosimilitud" class="slide level2">
<h2>Función de verosimilitud</h2>
<p>En la regla de Bayes, la probabilidad <span class="math inline">\(P(D|H)\)</span> se conoce como <em>verosimilitud</em> de la hipótesis <span class="math inline">\(H\)</span> dada la evidencia <span class="math inline">\(D\)</span>.</p>
<p>Cuando tenemos varias hipótesis, la verosimilitud de cada una de ellas se puede comparar con la de las otras para determinar cuál es la más compatible con los datos observados.</p>
<div id="def-funcion-verosimilitud" class="theorem definition">
<p><span class="theorem-title"><strong>Definición 2 (Función de verosimilitud)</strong></span> Dado un sistema completo de sucesos con hipótesis <span class="math inline">\(H_1, H_2, \ldots, H_n\)</span> de un experimento aleatorio, y un suceso <span class="math inline">\(D\)</span> que representa la evidencia observada, la <em>función de verosimilitud</em> es una función que asigna a cada hipótesis <span class="math inline">\(H_i\)</span> la probabilidad de observar la evidencia <span class="math inline">\(D\)</span> dada esa hipótesis, es decir,</p>
<p><span class="math display">\[
L(H_i|D) = P(D|H_i)
\]</span></p>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>Los valores de la función de verosimilitud son probabilidades condicionadas, pero la variable de la función de verosimilitud es el condicionante, es decir, la hipótesis <span class="math inline">\(H_i\)</span>, no la evidencia <span class="math inline">\(D\)</span>.</p>
<p><span class="math display">\[
L(x|D) = P(D|x)
\]</span></p>
</div>
</div>
</div>
</section>
<section class="slide level2">

<div id="exm-funcion-verosimilitud" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 3</strong></span> Consideremos el ejemplo del test diagnóstico anterior, con sensibilidad del 90% y especificidad del 95%.</p>
<p>Dada la evidencia de que el resultado del test ha sido positivo, la función de verosimilitud de las hipótesis <span class="math inline">\(E\)</span> y <span class="math inline">\(\overline{E}\)</span> es</p>
<p>La función de verosimilitud de las dos posibles hipótesis <span class="math inline">\(E\)</span> y <span class="math inline">\(\overline{E}\)</span> dada la evidencia <span class="math inline">\(+\)</span> es</p>
<p><span class="math display">\[
L(E|+) = P(+|E) = 0.9 \quad \mbox{y} \quad L(\overline{E}|+) = P(+|\overline{E}) = 1 - 0.95 = 0.05.
\]</span></p>
<p>En este caso, la hipótesis <span class="math inline">\(E\)</span> es mucho más compatible con la evidencia que la hipótesis <span class="math inline">\(\overline{E}\)</span>.</p>
</div>
<h3 id="interpretación-de-la-función-de-verosimilitud">Interpretación de la función de verosimilitud</h3>
<p>La función de verosimilitud se puede interpretar como una medida de la compatibilidad de cada hipótesis con los datos observados.</p>
<p><em>Cuanto mayor sea la función de verosimilitud de una hipótesis dada la evidencia, más plausible será la hipótesis.</em></p>
<p>Es importante destacar que la función de verosimilitud no es una función de probabilidad, ya que la suma de la verosimilitud de todas las hipótesis no tiene por qué ser igual a 1.</p>
<div id="exm-interpretacion-funcion-verosimilitud" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 4</strong></span> La siguiente tabla refleja las probabilidad a priori y la función de verosimilitud de las hipótesis <span class="math inline">\(E\)</span> y <span class="math inline">\(\overline{E}\)</span> dada la evidencia <span class="math inline">\(+\)</span> en el ejemplo del test diagnóstico.</p>
<table class="caption-top">
<colgroup>
<col style="width: 14%">
<col style="width: 40%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Hipótesis</th>
<th style="text-align: center;">Probabilidad a priori <span class="math inline">\(P(H)\)</span></th>
<th style="text-align: center;">Función de verosimilitud <span class="math inline">\(L(H|D)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(E\)</span></td>
<td style="text-align: center;">0.1</td>
<td style="text-align: center;">0.9</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\overline{E}\)</span></td>
<td style="text-align: center;">0.9</td>
<td style="text-align: center;">0.05</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="probabilidad-a-posteriori" class="slide level2">
<h2>Probabilidad a posteriori</h2>
<p>Si disponemos de la probabilidad a priori de cada hipótesis y de la función de verosimilitud dada la evidencia, entonces es posible calcular la probabilidad a posteriori de cada hipótesis dada la evidencia utilizando la regla de Bayes.</p>
<p><span class="math display">\[
\textcolor{#0099CC}{P(H_i|D)} = \frac{\textcolor{#ff2152}{P(H_i)}\times \textcolor{#03BF3D}{P(D|H_i)}}{P(D)}
\]</span></p>
<p>La probabilidad del denominador <span class="math inline">\(P(D)\)</span> es un factor común para todas las hipótesis, por lo que podemos decir que la probabilidad a posteriori de cada hipótesis es proporcional al producto de su probabilidad a priori por su función de verosimilitud:</p>
<p><span class="math display">\[
\textcolor{#0099CC}{P(H_i|D)} \propto \textcolor{#ff2152}{P(H_i)}\times \textcolor{#03BF3D}{P(D|H_i)}
\]</span></p>
</section>
<section class="slide level2">

<div id="exm-probabilidad-posteriori" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 5</strong></span> En el ejemplo del test diagnóstico, dado que el test ha resultado positivo, tenemos las siguientes plausibilidades a posteriori.</p>
<table class="caption-top">
<colgroup>
<col style="width: 9%">
<col style="width: 27%">
<col style="width: 2%">
<col style="width: 31%">
<col style="width: 2%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Hipótesis</th>
<th style="text-align: center;">Probabilidad a priori <span class="math inline">\(P(H)\)</span></th>
<th style="text-align: center;"></th>
<th style="text-align: center;">Función de verosimilitud <span class="math inline">\(L(H|D)\)</span></th>
<th style="text-align: center;"></th>
<th style="text-align: center;">Plausibilidad a posteriori</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(E\)</span></td>
<td style="text-align: center;">0.1</td>
<td style="text-align: center;"><span class="math inline">\(\times\)</span></td>
<td style="text-align: center;">0.9</td>
<td style="text-align: center;"><span class="math inline">\(=\)</span></td>
<td style="text-align: center;">0.090</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\overline{E}\)</span></td>
<td style="text-align: center;">0.9</td>
<td style="text-align: center;"><span class="math inline">\(\times\)</span></td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;"><span class="math inline">\(=\)</span></td>
<td style="text-align: center;">0.045</td>
</tr>
</tbody>
</table>
<p>Como puede observarse, la suma de las plausibilidades a posteriori no es igual a 1, por lo que no se pueden interpretar como probabilidades. Sin embargo, sí podemos compararlas, y en este caso la hipótesis <span class="math inline">\(E\)</span> es el doble de plausible que la hipótesis <span class="math inline">\(\overline{E}\)</span> dada la evidencia de que el test ha resultado positivo.</p>
</div>
</section>
<section class="slide level2">

<div class="centered">
<p><em>¿Cómo podríamos transformar las plausibilidades a posteriori en probabilidades a posteriori?</em></p>
</div>
</section>
<section class="slide level2">

<p>Podemos normalizar las plausibilidades a posteriori para obtener probabilidades a posteriori, dividiendo cada una de ellas por la suma de todas las plausibilidades a posteriori.</p>
<table class="caption-top">
<colgroup>
<col style="width: 9%">
<col style="width: 19%">
<col style="width: 2%">
<col style="width: 22%">
<col style="width: 2%">
<col style="width: 17%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Hipótesis</th>
<th style="text-align: center;">Probabilidad a priori <span class="math inline">\(P(H)\)</span></th>
<th style="text-align: center;"></th>
<th style="text-align: center;">Función de verosimilitud <span class="math inline">\(L(H|D)\)</span></th>
<th style="text-align: center;"></th>
<th style="text-align: center;">Plausibilidad a posteriori</th>
<th style="text-align: center;">Probabilidad a posteriori <span class="math inline">\(P(H|D)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(E\)</span></td>
<td style="text-align: center;">0.1</td>
<td style="text-align: center;"><span class="math inline">\(\times\)</span></td>
<td style="text-align: center;">0.9</td>
<td style="text-align: center;"><span class="math inline">\(=\)</span></td>
<td style="text-align: center;">0.090</td>
<td style="text-align: center;">0.09/(0.09+0.045) = 0.667</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\overline{E}\)</span></td>
<td style="text-align: center;">0.9</td>
<td style="text-align: center;"><span class="math inline">\(\times\)</span></td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;"><span class="math inline">\(=\)</span></td>
<td style="text-align: center;">0.045</td>
<td style="text-align: center;">0.045/(0.09+0.045) = 0.333</td>
</tr>
</tbody>
</table>
</section>
<section id="simulación-de-la-regla-de-bayes" class="slide level2">
<h2>Simulación de la regla de Bayes</h2>
<p>Podemos simular el procedimiento de actualización de la probabilidad de una hipótesis dada la evidencia, que realiza la regla de Bayes. Para ello necesitamos tomar muestras aleatorias de:</p>
<ul>
<li>La distribución a priori de la hipótesis <span class="math inline">\(H\)</span>.</li>
<li>La distribución conjunta de la hipótesis <span class="math inline">\(H\)</span> y la evidencia <span class="math inline">\(D\)</span> teniendo en cuenta la función de verosimilitud <span class="math inline">\(L(H|D)\)</span>.</li>
</ul>
</section>
<section id="muestreo-de-la-distribución-a-priori" class="slide level2">
<h2>Muestreo de la distribución a priori</h2>
<div id="exr-muestreo-distribucion-priori" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 2</strong></span> Obtener una muestra aleatoria de tamaño <span class="math inline">\(n=10000\)</span> de la distribución a priori de la hipótesis <span class="math inline">\(H\)</span> con probabilidades <span class="math inline">\(P(E)=0.1\)</span> y <span class="math inline">\(P(\overline{E})=0.9\)</span> y representar gráficamente la distribución muestral.</p>
</div>
<details>
<summary>
<strong>Solución</strong>
</summary>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href=""></a>df_H <span class="ot">=</span> <span class="fu">tibble</span>(hipótesis <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"E"</span>, <span class="st">"NoE"</span>))  <span class="co"># Hipótesis</span></span>
<span id="cb1-3"><a href=""></a>prior <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.1</span>, <span class="fl">0.9</span>)  <span class="co"># P(E) y P(No E)</span></span>
<span id="cb1-4"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">123</span>)  <span class="co"># Para reproducibilidad</span></span>
<span id="cb1-5"><a href=""></a>n <span class="ot">&lt;-</span> <span class="dv">10000</span>  <span class="co"># Tamaño de la muestra</span></span>
<span id="cb1-6"><a href=""></a><span class="co"># Muestreo de la distribución a priori</span></span>
<span id="cb1-7"><a href=""></a>muestra_prior <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(df_H, <span class="at">size =</span> n, <span class="at">weight =</span> prior, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-8"><a href=""></a><span class="co"># Diagrama de barras de la distribución de frecuencias</span></span>
<span id="cb1-9"><a href=""></a><span class="fu">ggplot</span>(muestra_prior, <span class="fu">aes</span>(<span class="at">x =</span> hipótesis)) <span class="sc">+</span></span>
<span id="cb1-10"><a href=""></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> myblue) <span class="sc">+</span></span>
<span id="cb1-11"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Muestra aleatoria de la distribución a priori"</span>,</span>
<span id="cb1-12"><a href=""></a>       <span class="at">x =</span> <span class="st">"Hipótesis"</span>, <span class="at">y =</span> <span class="st">"Frecuencia"</span>) <span class="sc">+</span></span>
<span id="cb1-13"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-2-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
</details>
</section>
<section id="muestreo-de-la-distribución-conjunta" class="slide level2">
<h2>Muestreo de la distribución conjunta</h2>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a><span class="co"># Muestreo de la función de verosimilitud (resultado del test)</span></span>
<span id="cb2-2"><a href=""></a>muestra_prior <span class="ot">&lt;-</span> muestra_prior <span class="sc">|&gt;</span></span>
<span id="cb2-3"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">test =</span> <span class="fu">ifelse</span>(<span class="fu">runif</span>(<span class="fu">n</span>()) <span class="sc">&lt;</span> <span class="fu">ifelse</span>(hipótesis <span class="sc">==</span> <span class="st">"E"</span>, <span class="fl">0.9</span>, <span class="fl">0.05</span>), <span class="st">"+"</span>, <span class="st">"-"</span>))</span>
<span id="cb2-4"><a href=""></a><span class="co"># Diagrama de barras de la distribución de frecuencias del test</span></span>
<span id="cb2-5"><a href=""></a><span class="fu">ggplot</span>(muestra_prior, <span class="fu">aes</span>(<span class="at">x =</span> hipótesis, <span class="at">fill =</span> test)) <span class="sc">+</span></span>
<span id="cb2-6"><a href=""></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb2-7"><a href=""></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb2-8"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución de frecuencias del resultado del test"</span>,</span>
<span id="cb2-9"><a href=""></a>       <span class="at">x =</span> <span class="st">"Hipótesis"</span>, <span class="at">y =</span> <span class="st">"Frecuencia relativa"</span>) <span class="sc">+</span></span>
<span id="cb2-10"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-3-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
</section>
<section id="muestreo-de-la-distribución-a-posteriori" class="slide level2">
<h2>Muestreo de la distribución a posteriori</h2>
<p>Una vez tenemos la distribución conjunta, podemos obtener una muestra de la distribución a posteriori, filtrando por la evidencia de que el resultado del test ha sido positivo.</p>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a><span class="co"># Filtrar casos con test positivos</span></span>
<span id="cb3-2"><a href=""></a>muestra_posterior <span class="ot">&lt;-</span> muestra_prior <span class="sc">|&gt;</span> <span class="fu">filter</span>(test <span class="sc">==</span> <span class="st">"+"</span>)</span>
<span id="cb3-3"><a href=""></a><span class="co"># Diagrama de barras de la distribución de frecuencias de la muestra a posteriori</span></span>
<span id="cb3-4"><a href=""></a><span class="fu">ggplot</span>(muestra_posterior, <span class="fu">aes</span>(<span class="at">x =</span> hipótesis, <span class="at">y =</span> <span class="fu">after_stat</span>(count <span class="sc">/</span> <span class="fu">sum</span>(count)))) <span class="sc">+</span></span>
<span id="cb3-5"><a href=""></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> myblue) <span class="sc">+</span></span>
<span id="cb3-6"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Muestra aleatoria de la distribución a posteriori"</span>,</span>
<span id="cb3-7"><a href=""></a>       <span class="at">x =</span> <span class="st">"Hipótesis"</span>, <span class="at">y =</span> <span class="st">"Frecuencia relativa"</span>) <span class="sc">+</span></span>
<span id="cb3-8"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-4-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
<p>Como se puede observar, la distribución de frecuencias a posteriori coincide con las probabilidades a posteriori calculadas con la regla de Bayes.</p>
</section>
<section class="slide level2">

<div id="exr-teorema-bayes" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 3</strong></span> Se dispone de dos test <span class="math inline">\(A\)</span> y <span class="math inline">\(B\)</span> para diagnosticar una enfermedad con una prevalencia del 1% en la población. El test <span class="math inline">\(A\)</span> tiene una sensibilidad del 98% y una especificidad del 80%, mientras que el test <span class="math inline">\(B\)</span> tiene una sensibilidad del 75% y una especificidad del 99%.</p>
<ol type="a">
<li>Obtener una muestra aleatoria de tamaño 100000 de la distribución a priori de la hipótesis.</li>
<li>Obtener una muestra aleatoria de tamaño 100000 de la distribución conjunta de las hipótesis y el resultado del test A.</li>
<li>Obtener una muestra aleatoria de la distribución a posteriori de las hipótesis dada la evidencia de que el test A ha resultado positivo.</li>
<li>Obtener una muestra aleatoria de la distribución conjunta de las hipótesis y el resultado del test B.</li>
<li>Obtener una muestra aleatoria de la distribución a posteriori de las hipótesis dada la evidencia de que el test B ha resultado positivo.</li>
</ol>
</div>
</section>
<section id="distribuciones-conjugadas" class="slide level2">
<h2>Distribuciones conjugadas</h2>
<p>Hemos visto que para obtener la distribución de probabilidad a posteriori de una hipótesis dada la evidencia, es necesario combinar la función de probabilidad a priori de la hipótesis con la función de verosimilitud dada la evidencia, utilizando la regla de Bayes.</p>
<p>Existen determinadas familias de distribuciones de probabilidad que, al combinarse con otras familias de distribuciones, mantienen su forma funcional. Estas familias se denominan <em>distribuciones conjugadas</em> y son de gran utilidad en el contexto de la inferencia bayesiana.</p>
<p>Las distribuciones conjugadas más comunes son:</p>
<ul>
<li>Beta-Binomial</li>
<li>Beta-Geometrica</li>
<li>Gamma-Poisson</li>
<li>Gamma-Exponencial</li>
<li>Normal-Normal</li>
</ul>
</section>
<section id="distribución-conjugada-beta-binomial" class="slide level2">
<h2>Distribución conjugada Beta-Binomial</h2>
<p>Si <span class="math inline">\(p\sim \mbox{Beta}(\alpha, \beta)\)</span> sigue una distribución Beta de parámetros <span class="math inline">\(\alpha\)</span> y <span class="math inline">\(\beta\)</span>, y <span class="math inline">\(X\sim B(n, p)\)</span> sigue una distribución Binomial con parámetros <span class="math inline">\(n\)</span> y <span class="math inline">\(p\)</span>, entonces la distribución a posteriori de <span class="math inline">\(p\)</span> dado <span class="math inline">\(X=k\)</span> es también una distribución beta,</p>
<p><span class="math display">\[
p|X=k \sim \mbox{Beta}(\alpha+k, \beta+n-k).
\]</span></p>
</section>
<section class="slide level2">

<div id="exm-distribucion-conjugada-beta-binomial" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 6</strong></span> Supongamos que queremos estimar la proporción de fumadores en nuestra ciudad tenemos una distribución a priori de <span class="math inline">\(p\)</span> dada por una distribución Beta con parámetros <span class="math inline">\(\alpha=2\)</span> y <span class="math inline">\(\beta=5\)</span>, es decir, <span class="math inline">\(p\sim \mbox{Beta}(2, 5)\)</span>. Si tomamos una muestra aleatoria de <span class="math inline">\(n=30\)</span> personas y observamos que <span class="math inline">\(k=10\)</span> de ellas son fumadoras, entonces la distribución a posteriori de <span class="math inline">\(p\)</span> dado <span class="math inline">\(X=30\)</span> es</p>
<p><span class="math display">\[
p|X=10 \sim \mbox{Beta}(2+10, 5+30-10) = \mbox{Beta}(12, 25).
\]</span></p>
</div>
</section>
<section id="distribución-conjugada-gamma-poisson" class="slide level2">
<h2>Distribución conjugada Gamma-Poisson</h2>
<p>Si <span class="math inline">\(\lambda \sim \mbox{Gamma}(\alpha, \beta)\)</span> sigue una distribución Gamma de parámetros <span class="math inline">\(\alpha\)</span> y <span class="math inline">\(\beta\)</span>, y <span class="math inline">\(X\sim \mbox{P}(\lambda)\)</span> sigue una distribución Poisson con parámetro <span class="math inline">\(\lambda\)</span>, entonces la distribución a posteriori de <span class="math inline">\(\lambda\)</span> dado <span class="math inline">\(X=k\)</span> es también una distribución Gamma,</p>
<p><span class="math display">\[
\lambda|\{X=k\} \sim \mbox{Gamma}(\alpha+k, \beta+1).
\]</span></p>
<p>Si se toman <span class="math inline">\(n\)</span> muestras independientes de la misma distribución Poisson <span class="math inline">\(P(\lambda)\)</span>, entonces la distribución a posteriori de <span class="math inline">\(\lambda\)</span> dado <span class="math inline">\(X_1=x_1,\ldots,X_n=x_n\)</span> es también una distribución Gamma,</p>
<p><span class="math display">\[
\lambda|\{X_1=x_1,\ldots,X_n=x_n\} \sim \mbox{Gamma}\left(\alpha+\sum_{i=1}^n x_i, \beta+n\right).
\]</span></p>
</section>
<section class="slide level2">

<div id="exm-distribucion-conjugada-gamma-poisson" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 7</strong></span> Supongamos que queremos estimar la tasa de nacimientos diarios en una ciudad. Tenemos una distribución a priori de <span class="math inline">\(\lambda\)</span> dada por una distribución Gamma con parámetros <span class="math inline">\(\alpha=2\)</span> y <span class="math inline">\(\beta=5\)</span>, es decir, <span class="math inline">\(\lambda \sim \mbox{Gamma}(2, 5)\)</span>. Si observamos que en una muestra de 5 días se han producido <span class="math inline">\(X_1=10, X_2=8, X_3=9, X_4=11, X_5=7\)</span> eventos, entonces la distribución a posteriori de <span class="math inline">\(\lambda\)</span> es</p>
<p><span class="math display">\[\begin{align*}
\lambda |\{X_1=10, X_2=8, X_3=9, X_4=11, X_5=7\}
&amp;\sim \mbox{Gamma}(2+10+8+9+11+7, 5+5) \\
&amp;= \mbox{Gamma}(47, 10).
\end{align*}\]</span></p>
</div>
</section>
<section id="distribución-conjugada-normal-normal" class="slide level2">
<h2>Distribución conjugada Normal-Normal</h2>
<p>Si <span class="math inline">\(\mu \sim N(\theta, \tau^2)\)</span> sigue una distribución Normal de media <span class="math inline">\(\theta\)</span> y varianza <span class="math inline">\(\tau^2\)</span>, y <span class="math inline">\(X\sim N(\mu, \sigma^2)\)</span> sigue una distribución Normal con media <span class="math inline">\(\mu\)</span> y varianza <span class="math inline">\(\sigma^2\)</span>, entonces la distribución a posteriori de <span class="math inline">\(\mu\)</span> dado <span class="math inline">\(X=x\)</span> es también una distribución Normal,</p>
<p><span class="math display">\[
\mu|X=x \sim N\left(\frac{\frac{\theta}{\tau^2}+\frac{x}{\sigma^2}}{\frac{1}{\tau^2}+\frac{1}{\sigma^2}}, \frac{1}{\frac{1}{\tau^2}+\frac{1}{\sigma^2}}\right)
= N\left(\frac{\theta\sigma^2 + x\tau^2}{\sigma^2 + \tau^2}, \frac{\sigma^2\tau^2}{\sigma^2 + \tau^2}\right).
\]</span></p>
<p>Si se toman <span class="math inline">\(n\)</span> muestras independientes de la misma distribución Normal <span class="math inline">\(N(\mu, \sigma^2)\)</span>, entonces la distribución a posteriori de <span class="math inline">\(\mu\)</span> dado <span class="math inline">\(X_1=x_1,\ldots,X_n=x_n\)</span> es también una distribución Normal,</p>
<p><span class="math display">\[\begin{align*}
\mu|\{X_1=x_1,\ldots,X_n=x_n\} &amp;\sim N\left(\frac{\frac{\theta}{\tau^2}+\frac{\sum_{i=1}^n x_i}{\sigma^2}}{\frac{1 }{\tau^2}+\frac{n}{\sigma^2}}, \frac{1}{\frac{1}{\tau^2}+\frac{n}{\sigma^2}}\right) \\
&amp;= N\left(\frac{\theta\sigma^2 + \bar{x}n\tau^2}{\sigma^2 + n\tau^2  }, \frac{\sigma^2\tau^2}{\sigma^2 + n\tau^2}\right).
\end{align*}\]</span></p>
</section>
<section class="slide level2">

<div id="exm-distribucion-conjugada-normal-normal" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 8</strong></span> Supongamos que el peso perdido con una dieta sigue una distribución normal $N(, 4) y queremos estimar el peso medio <span class="math inline">\(\mu\)</span> perdido con la dieta. Tenemos una distribución a priori de <span class="math inline">\(\mu\)</span> dada por una distribución Normal con media <span class="math inline">\(\theta=10\)</span> y varianza <span class="math inline">\(\tau^2=1\)</span>, es decir, <span class="math inline">\(\mu \sim N(10, 1)\)</span>. Si tomanos una muestra aleatoria de <span class="math inline">\(n=20\)</span> personas que han seguido la dieta y observamos que el peso medio perdido es <span class="math inline">\(\bar{x}=8\)</span>, entonces la distribución a posteriori de <span class="math inline">\(\mu\)</span> es</p>
<p><span class="math display">\[
\mu|\{X_1,\ldots,X_{20}\} \sim N\left(\frac{10\cdot 4 + 8\cdot 20\cdot 1}{4 + 20\cdot 1}, \frac{4\cdot 1}{4 + 20\cdot 1}\right) = N(8.57, 0.17).
\]</span></p>
</div>
</section>
<section id="modelos-bayesianos" class="slide level2">
<h2>Modelos bayesianos</h2>
<p>Un modelo bayesiano es un modelo estadístico que incorpora la incertidumbre sobre los parámetros desconocidos a través de distribuciones de probabilidad a priori, y que utiliza la regla de Bayes para actualizar estas distribuciones a posteriori a medida que se va obteniendo nueva información a través de los datos observados.</p>
<p>Los modelos bayesianos puedon considerarse <em>modelos de aprendizaje autmático</em> puesto que aprenden distribuciones con la experiencia que se va adquiriendo a través de los datos observados.</p>
</section>
<section id="elementos-de-un-modelo-bayesiano" class="slide level2">
<h2>Elementos de un modelo bayesiano</h2>
<p>Para definir un modelo bayesiano es necesario especificar:</p>
<ol type="1">
<li>El espacio de las hipótesis o parámetros desconocidos.</li>
<li>La distribución de probabilidad a priori de las hipótesis o parámetros desconocidos que refleja la incertidumbre inicial sobre ellos antes de observar los datos.</li>
<li>La distribución de probabilidad de los datos observados para cada hipótesis o valor de los parámetros desconocidos, que viene dada a través de la función de verosimilitud.</li>
</ol>

<img data-src="img/02-regla-bayes/modelo-bayesiano.png" class="r-stretch quarto-figure-center"><p class="caption">Esquema de un modelo bayesiano</p></section>
<section id="distribuciones-de-probabilidad-a-priori-discretas-y-continuas" class="slide level2">
<h2>Distribuciones de probabilidad a priori discretas y continuas</h2>
<p>Dependiendo de la naturaleza de las hipótesis o parámetros desconocidos, el espacio de hipótesis puede ser discreto o continuo. Esto da lugar a dos tipos de distribuciones de probabilidad a priori.</p>
<ul>
<li><p><strong>Distribuciones a priori discretas</strong>. Se utilizan cuando el espacio de hipótesis es discreto, es decir, las hipótesis o parámetros desconocidos toman un número finito o contable de valores, como por ejemplo el caso del test diagnóstico con las hipótesis <span class="math inline">\(E\)</span> y <span class="math inline">\(\overline{E}\)</span>.</p></li>
<li><p><strong>Distribuciones a priori continuas</strong>. Se utilizan cuando el espacio de hipótesis es continuo, es decir, las hipótesis o parámetros desconocidos pueden tomar cualquier valor dentro de un intervalo o región del espacio, como por ejemplo el caso de la estimación de la media o una proporción de una población.</p></li>
</ul>
</section>
<section id="distribuciones-de-los-datos-observados-condicionados-por-las-hipótesis" class="slide level2">
<h2>Distribuciones de los datos observados condicionados por las hipótesis</h2>
<p>Del mismo modo, dependiendo de la naturaleza de los datos observados, la función de verosimilitud puede modelarse mediante distribuciones de probabilidad discretas o continuas.</p>
<ul>
<li><p><strong>Distribuciones de probabilidad discretas</strong>. Se utilizan cuando los datos observados son discretos, es decir, toman un número finito o contable de valores, como por ejemplo el número de éxitos en una serie de ensayos independientes.</p></li>
<li><p><strong>Distribuciones de probabilidad continuas</strong>. Se utilizan cuando los datos observados son continuos, es decir, pueden tomar cualquier valor dentro de un intervalo o región del espacio, como por ejemplo la altura o el peso de una persona.</p></li>
</ul>
</section>
<section id="tipos-de-modelos-bayesianos" class="slide level2">
<h2>Tipos de modelos bayesianos</h2>
<p>Según el tipo de la distribución a priori y de la distribución de los datos utilizada para calcular la función de verosimilitud, tenemos distintos tipos de modelos bayesianos.</p>

<img data-src="img/02-regla-bayes/taxonomia-modelos-bayesianos.png" class="r-stretch quarto-figure-center"><p class="caption">Taxonomía de modelos bayesianos</p></section>
<section id="modelos-bayesianos-más-utilizados" class="slide level2">
<h2>Modelos bayesianos más utilizados</h2>
<ul>
<li><p><strong>Prior discreto + verosimilitud discreta</strong>. Las parejas más habituales son uniforme discreta con Binomial o Poisson, y priors ad hoc definidos por un experto con Multinomial o categórica. Es el caso del diagnóstico médico con hipótesis finitas.</p></li>
<li><p><strong>Prior discreto + verosimilitud continua</strong>. Aparece en comparación y selección de modelos. La pareja más importante es uniforme sobre modelos con Normal o Weibull para calcular factores de Bayes. El caso spike-and-slab con Normal es la base de la selección bayesiana de variables en regresión.</p></li>
<li><p><strong>Prior continuo + verosimilitud discreta</strong>. Aquí están los pares conjugados más importantes de la epidemiología: Beta-Binomial para proporciones, Dirichlet-Multinomial para categorías, Gamma-Poisson para conteos, y Beta-Geométrica para tiempo hasta el primer evento.</p></li>
<li><p><strong>Prior continuo + verosimilitud continua</strong> — Es el caso más general. Los pares conjugados más importantes son Normal-Normal, Normal Inv-Gamma y Gamma-Exponencial para tasas. Todo lo demás (regresión con covariables, modelos mixtos, supervivencia) no tiene forma analítica cerrada y requiere aproximación por MCMC.</p></li>
</ul>
</section>
<section id="modelo-beta---binomial" class="slide level2">
<h2>Modelo Beta - Binomial</h2>
<p>Cuando el parámetro de interés es una proporción <span class="math inline">\(\theta\)</span>, como por ejemplo el la proporción de fumadores en una población, y los datos observados son el número de éxitos <span class="math inline">\(X\)</span> en una serie de <span class="math inline">\(n\)</span> ensayos independientes, como por ejemplo el número de personas fumadoras en una muestra, el modelo bayesiano más utilizado es el modelo Beta-Binomial.</p>
<ul>
<li>Prior: <span class="math inline">\(\theta \sim \text{Beta}(\alpha, \beta)\)</span></li>
<li>Verosimilitud: <span class="math inline">\(X|\theta \sim B(n, \theta)\)</span>.</li>
</ul>
</section>
<section class="slide level2">

<div id="exr-modelo-beta-binomial" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 4</strong></span> Supongamos que queremos estimar la proporción de fumadores en nuestra ciudad. Sabemos que en varias muestras tomadas en otras ciudades similares, la proporción media estaba alrededor del 33% y que la menor y mayor proporción observadas fueron del 19% y del 48%, respectivamente.</p>
<p>¿Qué distribución Beta podríamos utilizar para modelizar la distribución a priori?</p>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Ayuda</strong></p>
</div>
<div class="callout-content">
<p>Usa la aplicación <a href="https://nube.aprendeconalf.es/shiny/distribuciones/">https://nube.aprendeconalf.es/shiny/distribuciones/</a> para probar distintas distribuciones Beta y encontrar aquella que mejor se ajuste a la información.</p>
</div>
</div>
</div>
</section>
<section class="slide level2">

<details>
<summary>
<strong>Solución</strong>
</summary>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb4-2"><a href=""></a>y <span class="ot">&lt;-</span> <span class="fu">dbeta</span>(x, <span class="at">shape1 =</span> <span class="dv">30</span>, <span class="at">shape2 =</span> <span class="dv">60</span>)</span>
<span id="cb4-3"><a href=""></a>df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(θ <span class="ot">=</span> x, <span class="at">densidad =</span> y)</span>
<span id="cb4-4"><a href=""></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> θ, <span class="at">y =</span> densidad)) <span class="sc">+</span></span>
<span id="cb4-5"><a href=""></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> myblue) <span class="sc">+</span></span>
<span id="cb4-6"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución Beta con α=30 y β=60"</span>,</span>
<span id="cb4-7"><a href=""></a>       <span class="at">x =</span> <span class="st">"Proporción de fumadores (θ)"</span>, <span class="at">y =</span> <span class="st">"Densidad"</span>) <span class="sc">+</span></span>
<span id="cb4-8"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-5-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
<p>También podemos usar el paquete <a href="https://bayes-rules.github.io/bayesrules/docs/index.html"><code>bayesrules</code></a> para visualizar las distribuciones más características en estadística bayesiana.</p>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a><span class="fu">library</span>(bayesrules)</span>
<span id="cb5-2"><a href=""></a><span class="fu">plot_beta</span>(<span class="at">alpha =</span> <span class="dv">30</span>, <span class="at">beta =</span> <span class="dv">60</span>) <span class="sc">+</span> </span>
<span id="cb5-3"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución Beta con α=30 y β=60"</span>,</span>
<span id="cb5-4"><a href=""></a>       <span class="at">x =</span> <span class="st">"Proporción de fumadores (θ)"</span>, <span class="at">y =</span> <span class="st">"Densidad"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-6-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
</details>
</section>
<section class="slide level2">

<div id="exr-modelo-beta-binomial-2" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 5</strong></span> Tras realizar un nuevo sondeo en la nuestra ciudad hemos observado que en una muestra de 100 personas, 20 son fumadoras.</p>
<p>¿Cuál es la función de verosimilitud para un proporción de fumadores en la ciudad <span class="math inline">\(\theta\)</span>?</p>
</div>
<details>
<summary>
<strong>Solución</strong>
</summary>
<p>Llamemos <span class="math inline">\(Y\)</span> al número de personas fumadoras en una muestra de tamaño <span class="math inline">\(n=100\)</span>. Suponiendo que la proporción de personas fumadoras en la ciudad es <span class="math inline">\(\theta\)</span>, el número de personas fumadoras observadas en una muestra aleatoria de 100 personas sigue una distribución Binomial con parámetros <span class="math inline">\(n=100\)</span> y <span class="math inline">\(\theta\)</span>.</p>
<p><span class="math display">\[
Y|\theta \sim B(n=100, \theta)
\]</span></p>
<p>por lo que la función de verosimilitud es</p>
<span class="math display">\[
L(\theta|Y=20) = P(Y=20|\theta) = \binom{100}{20} \theta^{20} (1-\theta)^{80}.
\]</span>
</details>
</section>
<section class="slide level2">

<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href=""></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb6-2"><a href=""></a>y <span class="ot">&lt;-</span> <span class="fu">dbinom</span>(<span class="dv">20</span>, <span class="at">size =</span> <span class="dv">100</span>, <span class="at">prob =</span> x)</span>
<span id="cb6-3"><a href=""></a><span class="co"># Función de verosimilitud para y = 20</span></span>
<span id="cb6-4"><a href=""></a>df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(θ <span class="ot">=</span> x, <span class="at">verosimilitud =</span> y)</span>
<span id="cb6-5"><a href=""></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> θ, <span class="at">y =</span> verosimilitud)) <span class="sc">+</span></span>
<span id="cb6-6"><a href=""></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> myblue, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb6-7"><a href=""></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Función de verosimilitud para y = 20"</span>,</span>
<span id="cb6-8"><a href=""></a>        <span class="at">x =</span> <span class="st">"Proporción de fumadores (θ)"</span>, <span class="at">y =</span> <span class="st">"Verosimilitud"</span>) <span class="sc">+</span></span>
<span id="cb6-9"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-7-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
<p>O bien, usando el paquete <code>bayesrules</code>,</p>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a><span class="fu">plot_binomial_likelihood</span>(<span class="at">y =</span> <span class="dv">20</span>, <span class="at">n =</span> <span class="dv">100</span>) <span class="sc">+</span></span>
<span id="cb7-2"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Función de verosimilitud para y = 20"</span>,</span>
<span id="cb7-3"><a href=""></a>       <span class="at">x =</span> <span class="st">"Proporción de fumadores (θ)"</span>, <span class="at">y =</span> <span class="st">"Verosimilitud"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-8-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
</section>
<section class="slide level2">

<p>Una vez que tenemos las distribuciones a priori y la función de verosimilitud, podemos calcular la distribución a posteriori utilizando la regla de Bayes.</p>
<p><span class="math display">\[
f(\theta|Y=20) = \frac{f(\theta)L(\theta|Y=20)}{P(Y=20)}
\]</span></p>
<p>Sin embargo, la constante normalizadora <span class="math inline">\(P(Y=20)\)</span> es difícil de calcular ya que requiere acumular las probabilidades <span class="math inline">\(f(\theta)L(\theta|Y=20)\)</span> para cualquier <span class="math inline">\(\theta\)</span>. Pero como <span class="math inline">\(\theta\)</span> es una variable continua que puede tomar cualquier valor real entre 0 y 1, esta suma se convierte en la integral</p>
<p><span class="math display">\[
P(Y=20) = \int_0^1 f(\theta)L(\theta|Y=20) d\theta
\]</span></p>
</section>
<section class="slide level2">

<p>Afortunadamente, aprovechando la distribución conjugada Beta-Binomial, sabemos que en este caso la distribución a posteriori de <span class="math inline">\(\theta\)</span> dado <span class="math inline">\(Y=20\)</span> es también una distribución Beta con parámetros <span class="math inline">\(\alpha=30+20=50\)</span> y <span class="math inline">\(\beta=60+100-20=140\)</span>, es decir, <span class="math inline">\(\theta|Y=20 \sim \mbox{Beta}(50, 140)\)</span>.</p>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href=""></a><span class="fu">plot_beta</span>(<span class="at">alpha =</span> <span class="dv">50</span>, <span class="at">beta =</span> <span class="dv">140</span>) <span class="sc">+</span> </span>
<span id="cb8-2"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución a posteriori de θ dado Y=20"</span>,</span>
<span id="cb8-3"><a href=""></a>       <span class="at">x =</span> <span class="st">"Proporción de fumadores (θ)"</span>, <span class="at">y =</span> <span class="st">"Densidad"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-9-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
</section>
<section class="slide level2">

<p>Podemos dibujar las tres distribuciones, a priori, verosimilitud y a posteriori, en la misma gráfica mediante la función <a href="https://bayes-rules.github.io/bayesrules/docs/reference/plot_beta_binomial.html"><code>plot_beta_binomial()</code></a> del paquete <code>bayesrules</code>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong><code>plot_beta_binomial()</code></strong></p>
</div>
<div class="callout-content">
<p>Dibuja la distribución Beta a priori, la distribución Binomial de la función de verosimilitud y la distribución Beta a posteriori dado el número de éxitos observado en la muestra.</p>
<p>Parámetros:</p>
<ul>
<li><code>alpha</code>: Parámetro <span class="math inline">\(\alpha\)</span> de la distribución Beta a priori.</li>
<li><code>beta</code>: Parámetro <span class="math inline">\(\beta\)</span> de la distribución Beta a priori.</li>
<li><code>y</code>: Número de éxitos observados en la muestra.</li>
<li><code>n</code>: Tamaño de la muestra.</li>
</ul>
</div>
</div>
</div>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a><span class="fu">plot_beta_binomial</span>(<span class="at">alpha =</span> <span class="dv">30</span>, <span class="at">beta =</span> <span class="dv">60</span>, <span class="at">y =</span> <span class="dv">20</span>, <span class="at">n =</span> <span class="dv">100</span>) <span class="sc">+</span></span>
<span id="cb9-2"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución a priori, función de verosimilitud y distribución a posteriori"</span>,</span>
<span id="cb9-3"><a href=""></a>       <span class="at">x =</span> <span class="st">"Proporción de fumadores (θ)"</span>, <span class="at">y =</span> <span class="st">"Densidad / Verosimilitud"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-10-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
</section>
<section id="simulación-de-la-distribución-a-posteriori" class="slide level2">
<h2>Simulación de la distribución a posteriori</h2>
<p>Cuando no sea posible determinar analíticamente la distribución teórica a posteriori, como por ejemplo en el caso de modelos bayesianos con distribuciones no conjugadas, entonces se puede simular la distribución a posteriori mediante técnicas de muestreo.</p>
<p>Las técnicas de muestreo más habituales, por orden de antigüedad, son:</p>
<ul>
<li>Muestreo de rejilla (grid sampling)</li>
<li>Markov Chain Monte Carlo (MCMC)</li>
<li>Hamiltonian Monte Carlo (HMC)</li>
</ul>
</section>
<section id="simulación-de-la-distribución-a-posteriori-mediante-muestreo-de-rejilla" class="slide level2">
<h2>Simulación de la distribución a posteriori mediante muestreo de rejilla</h2>
<p>La técnica de muestreo de rejilla es la más sencilla y consiste en:</p>
<ol type="1">
<li>Definir una rejilla de valores posibles para la hipótesis o parámetro desconocido.</li>
<li>Calcular la función de verosimilitud para cada uno de estos valores.</li>
<li>Multiplicarla por la probabilidad a priori correspondiente a cada valor.</li>
<li>Normalizar el resultado para obtener una distribución a posteriori aproximada.</li>
</ol>
</section>
<section class="slide level2">

<div id="exm-simulacion-posteriori-rejilla" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 9</strong></span> En el ejemplo anterior para estimar la proporción de personas fumadoras, partiendo de la distribución a priori <span class="math inline">\(\theta \sim \mbox{Beta}(30, 60)\)</span> y de la función de verosimilitud <span class="math inline">\(L(\theta|Y=20) = P(Y=20|\theta) = \binom{100}{20} \theta^{20} (1-\theta)^{80}\)</span>, el siguiente código simula la distribución a posteriori de <span class="math inline">\(\theta\)</span> dado <span class="math inline">\(Y=20\)</span> mediante muestreo de rejilla.</p>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href=""></a><span class="co"># Rejilla de 100 posibles valores de θ entre 0 y 1</span></span>
<span id="cb10-2"><a href=""></a>rejilla <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb10-3"><a href=""></a><span class="co"># Función de verosimilitud para cada valor de θ</span></span>
<span id="cb10-4"><a href=""></a>verosimilitud <span class="ot">&lt;-</span> <span class="fu">dbinom</span>(<span class="dv">20</span>, <span class="at">size =</span> <span class="dv">100</span>, <span class="at">prob =</span> rejilla)</span>
<span id="cb10-5"><a href=""></a><span class="co"># Probabilidad a priori para cada valor de θ</span></span>
<span id="cb10-6"><a href=""></a>prior <span class="ot">&lt;-</span> <span class="fu">dbeta</span>(rejilla, <span class="at">shape1 =</span> <span class="dv">30</span>, <span class="at">shape2 =</span> <span class="dv">60</span>)</span>
<span id="cb10-7"><a href=""></a><span class="co"># Plausibilidad a posteriori para cada valor de θ</span></span>
<span id="cb10-8"><a href=""></a>posterior <span class="ot">&lt;-</span> prior <span class="sc">*</span> verosimilitud</span>
<span id="cb10-9"><a href=""></a><span class="co"># Normalizamos la plausibilidad a posteriori para obtener una distribución de probabilidad</span></span>
<span id="cb10-10"><a href=""></a>df_posterior <span class="ot">&lt;-</span> <span class="fu">tibble</span>(θ <span class="ot">=</span> rejilla, <span class="at">posterior =</span> posterior <span class="sc">/</span> <span class="fu">sum</span>(posterior))</span>
<span id="cb10-11"><a href=""></a><span class="co"># Gráfica de la distribución a posteriori</span></span>
<span id="cb10-12"><a href=""></a><span class="fu">ggplot</span>(df_posterior, <span class="fu">aes</span>(<span class="at">x =</span> θ, <span class="at">y =</span> posterior)) <span class="sc">+</span></span>
<span id="cb10-13"><a href=""></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> myblue, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb10-14"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución a posteriori de θ dado Y=20 (simulación de rejilla)"</span>,</span>
<span id="cb10-15"><a href=""></a>       <span class="at">x =</span> <span class="st">"Proporción de fumadores (θ)"</span>, <span class="at">y =</span> <span class="st">"Densidad"</span>) <span class="sc">+</span></span>
<span id="cb10-16"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-11-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
</div>
</section>
<section class="slide level2">

<p>Para ver si esta distribución simulada se parece a la distribución teórica <span class="math inline">\(Beta(50, 140)\)</span>, podemos extraer una muestra aleatoria de ella suficientemente grande y dibujar su histograma.</p>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb11-2"><a href=""></a><span class="co"># Muestra aleatoria de tamaño 10000</span></span>
<span id="cb11-3"><a href=""></a>muestra_posterior <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(df_posterior, <span class="at">size =</span> <span class="dv">10000</span>, <span class="at">weight =</span> posterior, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-4"><a href=""></a><span class="co"># Histograma de la muestra a posteriori</span></span>
<span id="cb11-5"><a href=""></a><span class="fu">ggplot</span>(muestra_posterior, <span class="fu">aes</span>(<span class="at">x =</span> θ)) <span class="sc">+</span></span>
<span id="cb11-6"><a href=""></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), <span class="at">binwidth =</span> <span class="fl">0.01</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">fill =</span> myblue, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb11-7"><a href=""></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dbeta, <span class="at">args =</span> <span class="fu">list</span>(<span class="dv">50</span>, <span class="dv">140</span>), <span class="at">color =</span> myred) <span class="sc">+</span></span>
<span id="cb11-8"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histograma de la muestra aleatoria de la distribución a posteriori"</span>,</span>
<span id="cb11-9"><a href=""></a>       <span class="at">x =</span> <span class="st">"Proporción de fumadores (θ)"</span>, <span class="at">y =</span> <span class="st">"Densidad"</span>) <span class="sc">+</span></span>
<span id="cb11-10"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-12-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
<p><em>Como se puede observar, el histograma de la muestra aleatoria de la distribución a posteriori simulada mediante muestreo de rejilla se ajusta bastante bien a la función de densidad de la distribución teórica <span class="math inline">\(Beta(50, 140)\)</span>.</em></p>
</section>
<section class="slide level2">

<div id="exr-simulacion-posteriori-rejilla" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 6</strong></span> Partiendo de la distribución a posteriori anterior para la proporción de fumadores, <span class="math inline">\(p\sim Beta(50, 140)\)</span>, simula la distribución a posteriori si se toma otra muestra de tamaño 300 en la que aparecen 140 personas fumadoras.</p>
</div>
<details>
<summary>
<strong>Solución</strong>
</summary>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href=""></a><span class="co"># Rejilla de 100 posibles valores de θ entre 0 y 1</span></span>
<span id="cb12-2"><a href=""></a>rejilla <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb12-3"><a href=""></a><span class="co"># Función de verosimilitud para cada valor de θ con la nueva muestra</span></span>
<span id="cb12-4"><a href=""></a>verosimilitud <span class="ot">&lt;-</span> <span class="fu">dbinom</span>(<span class="dv">140</span>, <span class="at">size =</span> <span class="dv">300</span>, <span class="at">prob =</span> rejilla)</span>
<span id="cb12-5"><a href=""></a><span class="co"># Probabilidad a priori para cada valor de θ (distribución a posteriori anterior)</span></span>
<span id="cb12-6"><a href=""></a>prior <span class="ot">&lt;-</span> <span class="fu">dbeta</span>(rejilla, <span class="at">shape1 =</span> <span class="dv">50</span>, <span class="at">shape2 =</span> <span class="dv">140</span>)</span>
<span id="cb12-7"><a href=""></a><span class="co"># Plausibilidad a posteriori para cada valor de θ</span></span>
<span id="cb12-8"><a href=""></a>posterior <span class="ot">&lt;-</span> prior <span class="sc">*</span> verosimilitud</span>
<span id="cb12-9"><a href=""></a><span class="co"># Normalización de la plausibilidad a posteriori</span></span>
<span id="cb12-10"><a href=""></a>df_posterior <span class="ot">&lt;-</span> <span class="fu">tibble</span>(θ <span class="ot">=</span> rejilla, <span class="at">posterior =</span> posterior <span class="sc">/</span> <span class="fu">sum</span>(posterior))</span>
<span id="cb12-11"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb12-12"><a href=""></a><span class="co"># Muestra aleatoria de tamaño 10000</span></span>
<span id="cb12-13"><a href=""></a>muestra_posterior <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(df_posterior, <span class="at">size =</span> <span class="dv">10000</span>, <span class="at">weight =</span> posterior, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb12-14"><a href=""></a><span class="co"># Histograma de la muestra a posteriori</span></span>
<span id="cb12-15"><a href=""></a><span class="fu">ggplot</span>(muestra_posterior, <span class="fu">aes</span>(<span class="at">x =</span> θ)) <span class="sc">+</span></span>
<span id="cb12-16"><a href=""></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), <span class="at">binwidth =</span> <span class="fl">0.01</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">fill =</span> myblue, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb12-17"><a href=""></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dbeta, <span class="at">args =</span> <span class="fu">list</span>(<span class="dv">50</span><span class="sc">+</span><span class="dv">140</span>, <span class="dv">140</span><span class="sc">+</span><span class="dv">300-140</span>), <span class="at">color =</span> myred) <span class="sc">+</span></span>
<span id="cb12-18"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histograma de la muestra aleatoria de la distribución a posteriori"</span>,</span>
<span id="cb12-19"><a href=""></a>       <span class="at">x =</span> <span class="st">"Proporción de fumadores (θ)"</span>, <span class="at">y =</span> <span class="st">"Densidad"</span>) <span class="sc">+</span></span>
<span id="cb12-20"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-13-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
</details>
</section>
<section id="modelo-gamma-poisson" class="slide level2">
<h2>Modelo Gamma-Poisson</h2>
<p>Cuando el parámetro de interés es una tasa <span class="math inline">\(\lambda\)</span>, como por ejemplo la tasa de nacimientos diarios en una ciudad, y los datos observados son el número de eventos <span class="math inline">\(X\)</span> en un intervalo de tiempo dado, como por ejemplo el número de nacimientos en un día, el modelo bayesiano más utilizado es el modelo Gamma-Poisson.</p>
<ul>
<li>Prior: <span class="math inline">\(\lambda \sim \text{Gamma}(\alpha, \beta)\)</span></li>
<li>Verosimilitud: <span class="math inline">\(X|\lambda \sim P(\lambda)\)</span>.</li>
</ul>
</section>
<section class="slide level2">

<div id="exr-modelo-gamma-poisson" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 7</strong></span> Supongamos que queremos estimar la incidencia de infartos diarios en España por cada millón habitantes. Sabemos que en varios países similares, la tasa media de infartos es de 5 por cada 1000 habitantes al año, y que la menor y mayor tasa observadas fueron de 2 y 10 por cada 1000 habitantes al año, respectivamente.</p>
<p>¿Qué distribución Gamma podríamos utilizar para modelizar la distribución a priori?</p>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Ayuda</strong></p>
</div>
<div class="callout-content">
<p>Usa la aplicación <a href="https://nube.aprendeconalf.es/shiny/distribuciones/">https://nube.aprendeconalf.es/shiny/distribuciones/</a> para probar distintas distribuciones Gamma y encontrar aquella que mejor se ajuste a la información.</p>
</div>
</div>
</div>
<details>
<summary>
<strong>Solución</strong>
</summary>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href=""></a><span class="fu">plot_gamma</span>(<span class="at">shape =</span> <span class="dv">10</span>, <span class="at">rate =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb13-2"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución Gamma con α=2 y β=0.4"</span>,</span>
<span id="cb13-3"><a href=""></a>       <span class="at">x =</span> <span class="st">"Tasa de infartos (λ)"</span>, <span class="at">y =</span> <span class="st">"Densidad"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-14-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
</details>
</section>
<section class="slide level2">

<div id="exr-modelo-gamma-poisson-2" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 8</strong></span> Tras realizar un nuevo sondeo hemos observado que en una muestra de 5 días se han producido <span class="math inline">\(X_1=10, X_2=8, X_3=9, X_4=11, X_5=7\)</span> infartos.</p>
<p>¿Cuál es la función de verosimilitud para para tasa de infartos <span class="math inline">\(\lambda\)</span>?</p>
</div>
<details>
<summary>
<strong>Solución</strong>
</summary>
<p>Llamemos <span class="math inline">\(Y\)</span> al número de infartos diarios. Suponiendo que la tasa de infartos diarios es <span class="math inline">\(\lambda\)</span>, el número de infartos diarios puede modelizarse con una distribución de Poisson de parámetro <span class="math inline">\(\lambda\)</span>, es decir, <span class="math inline">\(Y\sim P(\lambda\)</span>), por lo que la función de verosimilitud para una tasa de infartos <span class="math inline">\(\lambda\)</span> dado el número de infartos observados en 5 días es</p>
<p><span class="math display">\[\begin{align*}
L(\lambda|Y=(10,8,9,11,7)) = &amp;P(Y_1=10|\lambda)P(Y_2=8|\lambda)P(Y_3=9|\lambda)\\
&amp;P(Y_4=11|\lambda)P(Y_5=7|\lambda).
\end{align*}\]</span></p>
<p>por lo que la función de verosimilitud es</p>
<span class="math display">\[\begin{align*}
L(\lambda|Y=(10,8,9,11,7))
&amp;= \frac{e^{-\lambda}\lambda^{10}}{10!} \frac{e^{-\lambda}\lambda^{8}}{8!} \frac{e^{-\lambda}\lambda^{9}}{9!}\frac{e^{-\lambda}\lambda^{11}}{11!} \frac{e^{-\lambda}\lambda^{7}}{7!} \\
&amp;= \frac{ e^{-5\lambda}\lambda^{45}}{10!8!9!11!7!}.
\end{align*}\]</span>
</details>
</section>
<section class="slide level2">

<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href=""></a><span class="fu">plot_poisson_likelihood</span>(<span class="at">y =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">11</span>, <span class="dv">7</span>), <span class="at">lambda_upper_bound =</span> <span class="dv">15</span>) <span class="sc">+</span></span>
<span id="cb14-2"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Función de verosimilitud para la muestra de 5 días"</span>,</span>
<span id="cb14-3"><a href=""></a>       <span class="at">x =</span> <span class="st">"Tasa de infartos (λ)"</span>, <span class="at">y =</span> <span class="st">"Verosimilitud"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-15-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
</section>
<section class="slide level2">

<p>Una vez que tenemos las distribuciones a priori y la función de verosimilitud, podemos calcular la distribución a posteriori utilizando la regla de Bayes.</p>
<p><span class="math display">\[
f(\lambda|Y=(10,8,9,11,7)) = \frac{f(\lambda)L(\lambda|Y=(10,8,9,11,7))}{P(Y=(10,8,9,11,7))}
\]</span></p>
<p>De nuevo, la constante normalizadora <span class="math inline">\(P(Y=(10,8,9,11,7))\)</span> es difícil de calcular ya que requiere acumular las probabilidades <span class="math inline">\(f(\lambda)L(\lambda|Y=(10,8,9,11,7))\)</span> para cualquier <span class="math inline">\(\lambda\)</span>. Pero como <span class="math inline">\(\lambda\)</span> es una variable continua que puede tomar cualquier valor real entre 0 y <span class="math inline">\(\infty\)</span>, esta suma se convierte en la integral</p>
<p><span class="math display">\[
P(Y=(10,8,9,11,7)) = \int_0^\infty f(\lambda)L(\lambda|Y=(10,8,9,11,7)) d\lambda
\]</span></p>
</section>
<section class="slide level2">

<p>De nuevo, podemos ahorrarnos el cálculo de la integral aprovechando la distribución conjugada Gamma-Poisson, sabemos que en este caso la distribución a posteriori de <span class="math inline">\(\lambda\)</span> dada la muestra <span class="math inline">\(Y_1=10, Y_2=8, Y_3=9, Y_4=11, Y_5=7\)</span> es también una distribución Gamma con parámetros <span class="math inline">\(\alpha=10+10+8+9+11+7\)</span> y <span class="math inline">\(\beta=2+5\)</span>, es decir, <span class="math inline">\(\lambda \sim \mbox{Gamma}(55, 7)\)</span>.</p>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href=""></a><span class="fu">plot_gamma</span>(<span class="at">shape =</span> <span class="dv">55</span>, <span class="at">rate =</span> <span class="dv">7</span>) <span class="sc">+</span> </span>
<span id="cb15-2"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución a posteriori de λ"</span>,</span>
<span id="cb15-3"><a href=""></a>       <span class="at">x =</span> <span class="st">"Tasa de infartos (λ)"</span>, <span class="at">y =</span> <span class="st">"Densidad"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-16-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
</section>
<section class="slide level2">

<p>Podemos dibujar las tres distribuciones, a priori, verosimilitud y a posteriori, en la misma gráfica mediante la función <a href="https://bayes-rules.github.io/bayesrules/docs/reference/plot_gamma_poisson.html"><code>plot_gamma_poisson()</code></a> del paquete <code>bayesrules</code>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong><code>plot_gamma_poisson()</code></strong></p>
</div>
<div class="callout-content">
<p>Dibuja la distribución Gamma a priori, la distribución Poisson de la función de verosimilitud y la distribución Gamma a posteriori dada una muestra de conteos.</p>
<p>Parámetros:</p>
<ul>
<li><code>shape</code>: Parámetro <span class="math inline">\(\alpha\)</span> de la distribución Gamma a priori.</li>
<li><code>rate</code>: Parámetro <span class="math inline">\(\beta\)</span> de la distribución Gamma a priori.</li>
<li><code>sum_y</code>: Suma de los conteos observados en la muestra.</li>
<li><code>n</code>: Tamaño de la muestra.</li>
</ul>
</div>
</div>
</div>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href=""></a><span class="fu">plot_gamma_poisson</span>(<span class="at">shape =</span> <span class="dv">10</span>, <span class="at">rate =</span> <span class="dv">2</span>, <span class="at">sum_y =</span> <span class="dv">45</span>, <span class="at">n =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb16-2"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución a priori, función de verosimilitud y distribución a posteriori"</span>,</span>
<span id="cb16-3"><a href=""></a>       <span class="at">x =</span> <span class="st">"Tasa de infartos (λ)"</span>, <span class="at">y =</span> <span class="st">"Densidad / Verosimilitud"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-17-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
<h3 id="simulación-de-la-distribución-a-posteriori-mediante-muestreo-de-rejilla-1">Simulación de la distribución a posteriori mediante muestreo de rejilla</h3>
<div id="exm-simulacion-posteriori-rejilla-gamma-poisson" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 10</strong></span> Partiendo de la distribución a priori <span class="math inline">\(\lambda \sim \mbox{Gamma}(10, 2)\)</span> y de la función de verosimilitud <span class="math inline">\(L(\lambda|Y=(10, 8, 9, 11, 7))\)</span>, el siguiente código permite simular la distribución a posteriori de <span class="math inline">\(\lambda\)</span> mediante muestreo de rejilla.</p>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href=""></a><span class="co"># Rejilla de 100 posibles valores de λ entre 0 y 15</span></span>
<span id="cb17-2"><a href=""></a>rejilla <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">15</span>, <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb17-3"><a href=""></a><span class="co"># Función de verosimilitud para cada valor de λ</span></span>
<span id="cb17-4"><a href=""></a>verosimilitud <span class="ot">&lt;-</span> <span class="fu">sapply</span>(rejilla, <span class="cf">function</span>(l) <span class="fu">prod</span>(<span class="fu">dpois</span>(<span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">11</span>, <span class="dv">7</span>), <span class="at">lambda =</span> l)))</span>
<span id="cb17-5"><a href=""></a><span class="co"># Probabilidad a priori para cada valor de λ</span></span>
<span id="cb17-6"><a href=""></a>prior <span class="ot">&lt;-</span> <span class="fu">dgamma</span>(rejilla, <span class="at">shape =</span> <span class="dv">10</span>, <span class="at">rate =</span> <span class="dv">2</span>)</span>
<span id="cb17-7"><a href=""></a><span class="co"># Plausibilidad a posteriori para cada valor de λ</span></span>
<span id="cb17-8"><a href=""></a>posterior <span class="ot">&lt;-</span> prior <span class="sc">*</span> verosimilitud</span>
<span id="cb17-9"><a href=""></a><span class="co"># Normalizamos la plausibilidad a posteriori para obtener una distribución de probabilidad</span></span>
<span id="cb17-10"><a href=""></a>df_posterior <span class="ot">&lt;-</span> <span class="fu">tibble</span>(λ <span class="ot">=</span> rejilla, <span class="at">posterior =</span> posterior <span class="sc">/</span> <span class="fu">sum</span>(posterior))</span>
<span id="cb17-11"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb17-12"><a href=""></a><span class="co"># Muestra aleatoria de tamaño 10000</span></span>
<span id="cb17-13"><a href=""></a>muestra_posterior <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(df_posterior, <span class="at">size =</span> <span class="dv">10000</span>, <span class="at">weight =</span> posterior, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-14"><a href=""></a><span class="co"># Histograma de la muestra a posteriori</span></span>
<span id="cb17-15"><a href=""></a><span class="fu">ggplot</span>(muestra_posterior, <span class="fu">aes</span>(<span class="at">x =</span> λ)) <span class="sc">+</span></span>
<span id="cb17-16"><a href=""></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), <span class="at">binwidth =</span> <span class="fl">0.5</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">fill =</span> myblue, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb17-17"><a href=""></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dgamma, <span class="at">args =</span> <span class="fu">list</span>(<span class="dv">55</span>, <span class="dv">7</span>), <span class="at">color =</span> myred) <span class="sc">+</span></span>
<span id="cb17-18"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histograma de la muestra aleatoria de la distribución a posteriori"</span>,</span>
<span id="cb17-19"><a href=""></a>       <span class="at">x =</span> <span class="st">"Tasa de infartos (λ)"</span>, <span class="at">y =</span> <span class="st">"Densidad"</span>) <span class="sc">+</span></span>
<span id="cb17-20"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-18-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
</div>
</section>
<section class="slide level2">

<div id="exr-simulacion-posteriori-rejilla-gamma-poisson-2" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 9</strong></span> Partiendo de la distribución a posteriori anterior para la tasa de infartos, <span class="math inline">\(\lambda\sim \mbox{Gamma}(55, 7)\)</span>, simula la distribución a posteriori si se toma otra muestra de tamaño 5 en la que se han producido <span class="math inline">\(X_1=5, X_2=7, X_3=4, X_4=6, X_5=3\)</span>.</p>
</div>
<details>
<summary>
<strong>Solución</strong>
</summary>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href=""></a><span class="co"># Rejilla de 100 posibles valores de λ entre 0 y 15</span></span>
<span id="cb18-2"><a href=""></a>rejilla <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">15</span>, <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb18-3"><a href=""></a><span class="co"># Función de verosimilitud para cada valor de λ con la nueva muestra</span></span>
<span id="cb18-4"><a href=""></a>verosimilitud <span class="ot">&lt;-</span> <span class="fu">sapply</span>(rejilla, <span class="cf">function</span>(l) <span class="fu">prod</span>(<span class="fu">dpois</span>(<span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">3</span>), <span class="at">lambda =</span> l)))</span>
<span id="cb18-5"><a href=""></a><span class="co"># Probabilidad a priori para cada valor de λ (distribución a posteriori anterior)</span></span>
<span id="cb18-6"><a href=""></a>prior <span class="ot">&lt;-</span> <span class="fu">dgamma</span>(rejilla, <span class="at">shape =</span> <span class="dv">55</span>, <span class="at">rate =</span> <span class="dv">7</span>)</span>
<span id="cb18-7"><a href=""></a><span class="co"># Plausibilidad a posteriori para cada valor de λ</span></span>
<span id="cb18-8"><a href=""></a>posterior <span class="ot">&lt;-</span> prior <span class="sc">*</span> verosimilitud</span>
<span id="cb18-9"><a href=""></a><span class="co"># Normalización de la plausibilidad a posteriori</span></span>
<span id="cb18-10"><a href=""></a>df_posterior <span class="ot">&lt;-</span> <span class="fu">tibble</span>(λ <span class="ot">=</span> rejilla, <span class="at">posterior =</span> posterior <span class="sc">/</span> <span class="fu">sum</span>(posterior))</span>
<span id="cb18-11"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb18-12"><a href=""></a><span class="co"># Muestra aleatoria de tamaño 10000</span></span>
<span id="cb18-13"><a href=""></a>muestra_posterior <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(df_posterior, <span class="at">size =</span> <span class="dv">10000</span>, <span class="at">weight =</span> posterior, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-14"><a href=""></a><span class="co"># Histograma de la muestra a posteriori</span></span>
<span id="cb18-15"><a href=""></a><span class="fu">ggplot</span>(muestra_posterior, <span class="fu">aes</span>(<span class="at">x =</span> λ)) <span class="sc">+</span></span>
<span id="cb18-16"><a href=""></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), <span class="at">binwidth =</span> <span class="fl">0.5</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">fill =</span> myblue, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span> </span>
<span id="cb18-17"><a href=""></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dgamma, <span class="at">args =</span> <span class="fu">list</span>(<span class="dv">55</span><span class="sc">+</span><span class="dv">25</span>, <span class="dv">7</span><span class="sc">+</span><span class="dv">5</span>), <span class="at">color =</span> myred) <span class="sc">+</span></span>
<span id="cb18-18"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histograma de la muestra aleatoria de la distribución a posteriori"</span>,</span>
<span id="cb18-19"><a href=""></a>       <span class="at">x =</span> <span class="st">"Tasa de infartos (λ)"</span>, <span class="at">y =</span> <span class="st">"Densidad"</span>) <span class="sc">+</span></span>
<span id="cb18-20"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-19-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
</details>
</section>
<section id="independencia-del-orden-de-obtención-de-los-datos" class="slide level2">
<h2>Independencia del orden de obtención de los datos</h2>
<p>Una de las propiedades más importantes de la regla de Bayes es que el orden en el que se obtienen los datos no afecta a la distribución a posteriori, es decir</p>
<p><span class="math display">\[
f(\theta|Y_1, Y_2) = f(\theta|Y_2, Y_1).
\]</span></p>
<p>La demostración es sencilla. Si primero se observa <span class="math inline">\(Y_1\)</span>,</p>
<p><span class="math display">\[
f(\theta|Y_1) = \frac{f(\theta)L(\theta|Y_1)}{P(Y_1)}
\]</span></p>
<p>y después <span class="math inline">\(Y_2\)</span></p>
<p><span class="math display">\[
f(\theta|Y_1,Y_2) = \frac{\frac{f(\theta)L(\theta|Y_1)}{P(Y_1)}L(\theta|Y_2)}{P(Y_2)} = \frac{f(\theta)L(\theta|Y_1)L(\theta|Y_2)}{P(Y_1)P(Y_2)} = \frac{f(\theta)L(\theta|Y_2)L(\theta|Y_1)}{P(Y_2)P(Y_1)} = f(\theta|Y_2,Y_1).
\]</span></p>
</section>
<section id="modelo-normal-normal" class="slide level2">
<h2>Modelo Normal-Normal</h2>
<p>Cuando el parámetro de interés es una media <span class="math inline">\(\mu\)</span>, como por ejemplo el nivel medio de colesterol en sangre, y los datos <span class="math inline">\(X\)</span> siguen una distribución Normal, como por ejemplo el nivel de colesterol en sangre, el modelo bayesiano más utilizado es el modelo Normal-Normal.</p>
<ul>
<li>Prior: <span class="math inline">\(\mu \sim N(\theta, \tau^2)\)</span></li>
<li>Verosimilitud: <span class="math inline">\(X|\mu \sim N(\mu, \sigma^2)\)</span>.</li>
</ul>
</section>
<section class="slide level2">

<div id="exr-modelo-normal-normal" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 10</strong></span> Supongamos que queremos estimar el nivel medio de colesterol en sangre en una población. Sabemos que en poblaciones similares, el nivel de colesterol medio está en un rango que va de 191 a 209 mg/dL. ¿Qué distribución Normal podríamos utilizar para modelizar la distribución a priori?</p>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Ayuda</strong></p>
</div>
<div class="callout-content">
<p>Usa la aplicación <a href="https://nube.aprendeconalf.es/shiny/distribuciones/">https://nube.aprendeconalf.es/shiny/distribuciones/</a> para probar distintas distribuciones Normal y encontrar aquella que mejor se ajuste a la información.</p>
</div>
</div>
</div>
<details>
<summary>
<strong>Solución</strong>
</summary>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href=""></a><span class="fu">plot_normal</span>(<span class="at">mean =</span> <span class="dv">200</span>, <span class="at">sd =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb19-2"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución Normal con media 200 y desviación estándar 2"</span>,</span>
<span id="cb19-3"><a href=""></a>       <span class="at">x =</span> <span class="st">"Nivel de colesterol (mg/dL)"</span>, <span class="at">y =</span> <span class="st">"Densidad"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-20-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
</details>
</section>
<section class="slide level2">

<div id="exr-modelo-normal-normal-2" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 11</strong></span> Tras realizar un nuevo sondeo hemos observado que en una muestra de 10 personas el nivel medio de colesterol en sangre es de 230, 226, 245, 228, 232, 235, 232, 244, 251, 247 mg/dL. Suponiendo que el nivel de colesterol en sangre sigue una distribución Normal con desviación típica conocida de 40 mg/dL (algo razonable al tratarse de una variable continua biológica), ¿cuál es la función de verosimilitud para el nivel medio de colesterol <span class="math inline">\(\mu\)</span>?</p>
</div>
<details>
<summary>
<strong>Solución</strong>
</summary>
<p>Llamemos <span class="math inline">\(Y\)</span> al nivel de colesterol en sangre. Suponiendo que el nivel de colesterol en sangre sigue una distribución Normal con media <span class="math inline">\(\mu\)</span> y desviación típica conocida de 40 mg/dL, es decir, <span class="math inline">\(Y\sim N(\mu, 40^2)\)</span>, entonces la función de verosimilitud para el nivel medio de colesterol <span class="math inline">\(\mu\)</span> dado el nivel medio observado en la muestra es</p>
<p><span class="math display">\[
L(\mu|y) = \frac{1}{(2\pi \sigma^2)^{n/2}} \exp\left(-\frac{1}{2\sigma^2} \sum_{i=1}^n (y_i - \mu)^2\right)
\]</span></p>
donde <span class="math inline">\(y = (y_1, \ldots, y_n)\)</span> es el vector de observaciones y <span class="math inline">\(\sigma^2 = 40^2\)</span>.
</details>
</section>
<section class="slide level2">

<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href=""></a>muestra <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">230</span>, <span class="dv">226</span>, <span class="dv">245</span>, <span class="dv">228</span>, <span class="dv">232</span>, <span class="dv">235</span>, <span class="dv">232</span>, <span class="dv">244</span>, <span class="dv">251</span>, <span class="dv">247</span>)</span>
<span id="cb20-2"><a href=""></a><span class="fu">plot_normal_likelihood</span>(<span class="at">y =</span> muestra, <span class="at">sigma =</span> <span class="dv">40</span>) <span class="sc">+</span></span>
<span id="cb20-3"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Función de verosimilitud para el nivel medio de colesterol"</span>,</span>
<span id="cb20-4"><a href=""></a>       <span class="at">x =</span> <span class="st">"Nivel medio de colesterol (μ)"</span>, <span class="at">y =</span> <span class="st">"Verosimilitud"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-21-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
</section>
<section class="slide level2">

<p>Al igual que con los otros modelos, una vez tenemos definidas la función de verosimilitud y la distribución a priori, podemos calcular la distribución a posteriori utilizando la regla de Bayes.</p>
<p>Podemos dibujar las tres distribuciones, a priori, verosimilitud y a posteriori, en la misma gráfica mediante la función <a href="https://bayes-rules.github.io/bayesrules/docs/reference/plot_normal_normal.html"><code>plot_normal_normal()</code></a> del paquete <code>bayesrules</code>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong><code>plot_normal_normal()</code></strong></p>
</div>
<div class="callout-content">
<p>Dibuja la distribución Normal a priori, la distribución Normal de la función de verosimilitud y la distribución Normal a posteriori dado una muestra de datos.</p>
<p>Parámetros:</p>
<ul>
<li><code>mean</code>: Media de la distribución Normal a priori.</li>
<li><code>sd</code>: Desviación estándar de la distribución Normal a priori.</li>
<li><code>y</code>: Vector de observaciones de la muestra.</li>
<li><code>sigma</code>: Desviación estándar conocida de la distribución Normal de la función de verosimilitud.</li>
</ul>
</div>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href=""></a>media <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">c</span>(<span class="dv">230</span>, <span class="dv">226</span>, <span class="dv">245</span>, <span class="dv">228</span>, <span class="dv">232</span>, <span class="dv">235</span>, <span class="dv">232</span>, <span class="dv">244</span>, <span class="dv">251</span>, <span class="dv">247</span>))</span>
<span id="cb21-2"><a href=""></a><span class="fu">plot_normal_normal</span>(<span class="at">mean =</span> <span class="dv">200</span>, <span class="at">sd =</span> <span class="dv">3</span>, <span class="at">y_bar =</span> media, <span class="at">n =</span> <span class="dv">10</span>, <span class="at">sigma =</span> <span class="dv">40</span>) <span class="sc">+</span></span>
<span id="cb21-3"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución a priori, función de verosimilitud y distribución a posteriori"</span>, </span>
<span id="cb21-4"><a href=""></a>       <span class="at">x =</span> <span class="st">"Nivel medio de colesterol (μ)"</span>, <span class="at">y =</span> <span class="st">"Densidad / Verosimilitud"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-22-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
</section>
<section id="explosión-combinatoria-del-muestreo-de-rejilla" class="slide level2">
<h2>Explosión combinatoria del muestreo de rejilla</h2>
<p>El muestreo de rejilla es sencillo pero no es factible para modelos bayesianos con muchos parámetros, ya que el número de puntos en la rejilla crece exponencialmente con el número de parámetros, lo que hace que el cálculo de la función de verosimilitud y la normalización de la distribución a posteriori sea computacionalmente prohibitivo. La siguiente tabla refleja el crecimiento computacional del muestreo de rejilla a medida que aumenta el número de parámetros y el número de puntos en la rejilla.</p>
<table class="caption-top">
<colgroup>
<col style="width: 24%">
<col style="width: 34%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Número de parámetros</th>
<th style="text-align: right;">Número de puntos por parámetro</th>
<th style="text-align: right;">Número total de puntos en la rejilla</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">10,000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">1,000,000</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">100,000,000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">10,000,000,000</td>
</tr>
</tbody>
</table>
<p>Por esta razón, para modelos bayesianos con muchos parámetros se utilizan técnicas de muestreo más eficientes como MCMC o HMC.</p>
</section>
<section id="muestreos-basádos-en-procesos-de-monte-carlo" class="slide level2">
<h2>Muestreos basádos en procesos de Monte Carlo</h2>
<p>Los métodos de Monte Carlo tratan de generar muestras representativas de la distribución a posteriori con un coste computacional mucho menor que el muestreo de rejilla. Los dos tipos principales son:</p>
<ul>
<li><strong>Markov Chain Monte Carlo (MCMC)</strong>. Es una familia de algoritmos generan cadenas de Markov cuya distribución estacionaria es la distribución a posteriori deseada. Los algoritmos parten de un valor inicial de cada parámetro y en cada iteración se propone un nuevo valor aleatorio cercano al anterior, que se acepta o rechaza con una regla que garantiza que la cadena converja a la distribución posterior sin necesidad de conocer su constante de normalización. El más conocido de esta familia es el algoritmo de Metropolis-Hastings.</li>
<li><strong>Hamiltonian Monte Carlo (HMC)</strong>. Refina esta idea usando el gradiente del log-posterior para proponer saltos grandes y coherentes con la geometría de la distribución, evitando el paseo aleatorio ineficiente de algoritmos más simples como Metropolis-Hastings, lo que lo hace especialmente potente en modelos con muchos parámetros correlacionados.</li>
</ul>
</section>
<section id="el-lenguaje-stan" class="slide level2">
<h2>El lenguaje Stan</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>El lenguaje Stan es un lenguaje de programación específico para el modelado e inferencia bayesiana que implementa algoritmos de muestreo eficientes como HMC.</p>
</div><div class="column" style="width:10%;">

</div><div class="column" style="width:15%;">
<p><img data-src="img/logos/stan-logo.png"></p>
</div></div>
<ul>
<li>Es un lenguaje declarativo que permite definir modelos bayesianos complejos de manera sencilla.</li>
<li>Compila los modelos a código C++ optimizado por lo que es capaz de generar muestras aleatorias de distribuciones a posteriori multiparamétricas de forma rápida y eficiente.</li>
<li>Permite también realizar análisis de convergencia y sensibilidad de las muestras generadas.</li>
</ul>
</section>
<section id="estructura-de-un-programa-en-stan" class="slide level2">
<h2>Estructura de un programa en Stan</h2>
<p>Un programa en Stan se compone de varios bloques declarativos:</p>
<ul>
<li><code>data</code>: Declara las variables observadas en los datos, sus dimensiones, tipos y rango posible de valores.</li>
<li><code>parameters</code>: Declara los parámetros del modelo que queremos estimar, sus dimensiones, tipos y rango posible de valores.</li>
<li><code>model</code>: Define la estructura del modelo bayesiano, especificando la distribución a priori de los parámetros y la función de verosimilitud de los datos dados los parámetros.</li>
<li><code>generated quantities</code>: Permite definir variables adicionales que se calculan a partir de los parámetros y los datos, como por ejemplo predicciones o métricas de medidas de ajuste del modelo.</li>
</ul>
</section>
<section class="slide level2">

<div id="exm-stan" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 11</strong></span> A continuación se muestra un programa en Stan para el modelo Beta-Binomial para estimar la proporción de fumadores.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode numberSource stan number-lines code-with-copy"><code class="sourceCode stan"><span id="cb22-1"><a href=""></a><span class="co">// modelo-beta-binomial.stan</span></span>
<span id="cb22-2"><a href=""></a><span class="co">// Datos</span></span>
<span id="cb22-3"><a href=""></a><span class="kw">data</span> {</span>
<span id="cb22-4"><a href=""></a>  <span class="dt">int</span>&lt;<span class="kw">lower</span> = <span class="dv">0</span>, <span class="kw">upper</span> = <span class="dv">10</span>&gt; Y;</span>
<span id="cb22-5"><a href=""></a>}</span>
<span id="cb22-6"><a href=""></a><span class="co">// Parmámetros</span></span>
<span id="cb22-7"><a href=""></a><span class="kw">parameters</span> {</span>
<span id="cb22-8"><a href=""></a>  <span class="dt">real</span>&lt;<span class="kw">lower</span> = <span class="dv">0</span>, <span class="kw">upper</span> = <span class="dv">1</span>&gt; pi;</span>
<span id="cb22-9"><a href=""></a>}</span>
<span id="cb22-10"><a href=""></a><span class="co">// Modelo</span></span>
<span id="cb22-11"><a href=""></a><span class="kw">model</span> {</span>
<span id="cb22-12"><a href=""></a>  Y ~ binomial(<span class="dv">100</span>, pi);</span>
<span id="cb22-13"><a href=""></a>  pi ~ beta(<span class="dv">30</span>, <span class="dv">60</span>);</span>
<span id="cb22-14"><a href=""></a>}</span>
<span id="cb22-15"><a href=""></a><span class="co">// Posterior predictivo: simular nuevas observaciones</span></span>
<span id="cb22-16"><a href=""></a><span class="kw">generated quantities</span> {</span>
<span id="cb22-17"><a href=""></a>  <span class="dt">int</span> y_rep = binomial_rng(<span class="dv">100</span>, pi);</span>
<span id="cb22-18"><a href=""></a>}</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="el-paquete-rstan" class="slide level2">
<h2>El paquete <code>rstan</code></h2>
<p>El paquete <a href="https://mc-stan.org/rstan/articles/rstan.html"><code>rstan</code></a> es la interfaz de R para el lenguaje Stan, que permite compilar y ejecutar modelos escritos en Stan desde R, así como analizar los resultados obtenidos.</p>
<p>Los programas de Stan se especifican en una cadena de caracteres y se compilan mediante la función <code>stan</code>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong><code>stan()</code></strong></p>
</div>
<div class="callout-content">
<p>Compila un programa de Stan y simula el muestreo de la distribución a posteriori dados los datos.</p>
<ul>
<li><code>model_code</code>: Cadena de caracteres con el código del programa de Stan.</li>
<li><code>data</code>: Lista con los datos a pasar al programa de Stan.</li>
<li><code>chains</code>: Número de cadenas de Markov a simular.</li>
<li><code>iter</code>: Número de iteraciones para el muestreo (tamaño de cada cadena)</li>
<li><code>seed</code>: Semilla para la generación de números aleatorios.</li>
</ul>
</div>
</div>
</div>
</section>
<section class="slide level2">

<div id="exm-stan-rstan" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 12</strong></span> El siguiente código define un modelo Gamma-Poisson para el número de infartos diarios, con una distribución a priori <span class="math inline">\(\lambda \sim \mbox{Gamma}(10, 2)\)</span> y una función de verosimilitud <span class="math inline">\(L(\lambda|Y)\)</span> Poisson, lo compila y simula el muestreo de la distribución a posteriori.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href=""></a><span class="fu">library</span>(rstan)</span>
<span id="cb23-2"><a href=""></a><span class="co"># Código del programa de Stan</span></span>
<span id="cb23-3"><a href=""></a>modelo <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb23-4"><a href=""></a><span class="st">data {</span></span>
<span id="cb23-5"><a href=""></a><span class="st">  int&lt;lower=0&gt; n; // número de días</span></span>
<span id="cb23-6"><a href=""></a><span class="st">  int&lt;lower=0&gt; y[n]; // número de infartos diarios</span></span>
<span id="cb23-7"><a href=""></a><span class="st">}</span></span>
<span id="cb23-8"><a href=""></a><span class="st">parameters {</span></span>
<span id="cb23-9"><a href=""></a><span class="st">  real&lt;lower=0&gt; lambda; // tasa de infartos</span></span>
<span id="cb23-10"><a href=""></a><span class="st">}</span></span>
<span id="cb23-11"><a href=""></a><span class="st">model {</span></span>
<span id="cb23-12"><a href=""></a><span class="st">  y ~ poisson(lambda); // función de verosimilitud</span></span>
<span id="cb23-13"><a href=""></a><span class="st">  lambda ~ gamma(10, 2); // distribución a priori</span></span>
<span id="cb23-14"><a href=""></a><span class="st">}</span></span>
<span id="cb23-15"><a href=""></a><span class="st">"</span></span>
<span id="cb23-16"><a href=""></a>posterior_sim <span class="ot">&lt;-</span> <span class="fu">stan</span>(<span class="at">model_code =</span> modelo, </span>
<span id="cb23-17"><a href=""></a>    <span class="at">data =</span> <span class="fu">list</span>(<span class="at">n =</span> <span class="dv">5</span>, <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">11</span>, <span class="dv">7</span>)), </span>
<span id="cb23-18"><a href=""></a>    <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">iter =</span> <span class="dv">5000</span><span class="sc">*</span><span class="dv">2</span>, <span class="at">seed =</span> <span class="dv">123</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</section>
<section class="slide level2">

<p>El resultado es una muestra de 4 cadenas de Markov de tamaño 5000 cada una, es decir, un total de 20.000 muestras de la distribución a posteriori de <span class="math inline">\(\lambda\)</span> dado el número de infartos diarios observado en la muestra.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href=""></a><span class="fu">library</span>(broom.mixed)</span>
<span id="cb24-2"><a href=""></a><span class="fu">library</span>(knitr)</span>
<span id="cb24-3"><a href=""></a><span class="fu">tidy</span>(posterior_sim, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>) <span class="sc">|&gt;</span> </span>
<span id="cb24-4"><a href=""></a><span class="fu">kable</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">lambda</td>
<td style="text-align: right;">7.84497</td>
<td style="text-align: right;">1.063241</td>
<td style="text-align: right;">5.889406</td>
<td style="text-align: right;">10.08914</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section class="slide level2">

<p>Podemos visualizar la traza cuatro cadenas de Markov generadas con la función <code>mcmc_trace</code> del paquete <a href="https://mc-stan.org/bayesplot/"><code>bayesplot</code></a>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href=""></a><span class="fu">library</span>(bayesplot)</span>
<span id="cb25-2"><a href=""></a><span class="fu">mcmc_trace</span>(posterior_sim, <span class="at">pars =</span> <span class="st">"lambda"</span>) <span class="sc">+</span></span>
<span id="cb25-3"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Trazas de las cadenas de Markov para λ"</span>,</span>
<span id="cb25-4"><a href=""></a>       <span class="at">x =</span> <span class="st">"Iteración"</span>, <span class="at">y =</span> <span class="st">"Valor de λ"</span>) <span class="sc">+</span></span>
<span id="cb25-5"><a href=""></a>  <span class="fu">theme_gray</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-25-1.png" width="960" class="r-stretch"></section>
<section class="slide level2">

<p>Haciendo un zoom sobre una de estas cadenas podemos observar cómo recorre los distintos valores de la distribución a posteriori.</p>

<img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-26-1.png" width="960" class="r-stretch"><p>Se puede observar que la cadena toma valores entre 5 y11.</p>
</section>
<section class="slide level2">

<p>Podemos visualizar la distribución a posteriori de <span class="math inline">\(\lambda\)</span> con la función <code>mcmc_dens</code> del paquete <code>bayesplot</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href=""></a><span class="fu">mcmc_dens</span>(posterior_sim, <span class="at">pars =</span> <span class="st">"lambda"</span>) <span class="sc">+</span></span>
<span id="cb26-2"><a href=""></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dgamma, <span class="at">args =</span> <span class="fu">list</span>(<span class="dv">55</span>, <span class="dv">7</span>), <span class="at">color =</span> myred) <span class="sc">+</span></span>
<span id="cb26-3"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución a posteriori de λ"</span>,</span>
<span id="cb26-4"><a href=""></a>       <span class="at">x =</span> <span class="st">"Tasa de infartos (λ)"</span>, <span class="at">y =</span> <span class="st">"Densidad"</span>) <span class="sc">+</span></span>
<span id="cb26-5"><a href=""></a>  <span class="fu">theme_gray</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-27-1.png" width="960" class="r-stretch"></section>
<section class="slide level2">

<div id="exr-stan-rstan" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 12</strong></span> Definir un modelo Normal-Normal en Stan para el nivel medio de colesterol en sangre, con una distribución a priori <span class="math inline">\(N(200, 2^2)\)</span> y una función de verosimilitud Normal con desviación estándar conocida de 40 mg/dL, compilarlo y simular el muestreo de la distribución a posteriori dada la muestra de 10 personas con niveles de colesterol 230, 226, 245, 228, 232, 235, 232, 244, 251, 247.</p>
</div>
</section>
<section class="slide level2">

<details>
<summary>
<strong>Solución</strong>
</summary>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href=""></a><span class="co"># Código del programa de Stan</span></span>
<span id="cb27-2"><a href=""></a>modelo <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb27-3"><a href=""></a><span class="st">data {  </span></span>
<span id="cb27-4"><a href=""></a><span class="st">  int&lt;lower=0&gt; n; // número de personas</span></span>
<span id="cb27-5"><a href=""></a><span class="st">  vector[n] y; // niveles de colesterol</span></span>
<span id="cb27-6"><a href=""></a><span class="st">}</span></span>
<span id="cb27-7"><a href=""></a><span class="st">parameters {</span></span>
<span id="cb27-8"><a href=""></a><span class="st">  real mu; // nivel medio de colesterol</span></span>
<span id="cb27-9"><a href=""></a><span class="st">}</span></span>
<span id="cb27-10"><a href=""></a><span class="st">model {</span></span>
<span id="cb27-11"><a href=""></a><span class="st">  y ~ normal(mu, 40); // función de verosimilitud</span></span>
<span id="cb27-12"><a href=""></a><span class="st">  mu ~ normal(200, 3); // distribución a priori</span></span>
<span id="cb27-13"><a href=""></a><span class="st">}</span></span>
<span id="cb27-14"><a href=""></a><span class="st">"</span></span>
<span id="cb27-15"><a href=""></a>posterior_sim <span class="ot">&lt;-</span> <span class="fu">stan</span>(<span class="at">model_code =</span> modelo, </span>
<span id="cb27-16"><a href=""></a>    <span class="at">data =</span> <span class="fu">list</span>(<span class="at">n =</span> <span class="dv">10</span>, <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">230</span>, <span class="dv">226</span>, <span class="dv">245</span>, <span class="dv">228</span>, <span class="dv">232</span>, <span class="dv">235</span>, <span class="dv">232</span>, <span class="dv">244</span>, <span class="dv">251</span>, <span class="dv">247</span>)), </span>
<span id="cb27-17"><a href=""></a>    <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">iter =</span> <span class="dv">5000</span><span class="sc">*</span><span class="dv">2</span>, <span class="at">seed =</span> <span class="dv">123</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</details>
</section>
<section class="slide level2">

<details>
<summary>
<strong>Solución (continuación)</strong>
</summary>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href=""></a><span class="fu">mcmc_dens</span>(posterior_sim, <span class="at">pars =</span> <span class="st">"mu"</span>) <span class="sc">+</span></span>
<span id="cb28-2"><a href=""></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm, <span class="at">args =</span> <span class="fu">list</span>(<span class="fl">201.97</span>, <span class="fu">sqrt</span>(<span class="fl">8.52</span>)), <span class="at">color =</span> myred) <span class="sc">+</span></span>
<span id="cb28-3"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución a posteriori de μ"</span>,</span>
<span id="cb28-4"><a href=""></a>       <span class="at">x =</span> <span class="st">"Nivel medio de colesterol (μ)"</span>, <span class="at">y =</span> <span class="st">"Densidad"</span>) <span class="sc">+</span></span>
<span id="cb28-5"><a href=""></a>  <span class="fu">theme_gray</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-29-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</details>
</section>
<section id="análisis-de-las-cadenas-de-markov" class="slide level2">
<h2>Análisis de las cadenas de Markov</h2>
<p>El principal problema de la generación de muestras de la distribución a posteriori mediante cadenas de Markov con MCMC o HMC es que los valores de las cadenas no son independientes. Cada valor de la cadena depende del anterior, y aunque el algoritmo busca que la muestra se ajuste a la distribución de a posteriori, a veces puede fallar y generar muestras poco representativas.</p>

<img data-src="img/02-regla-bayes/cadenas-markov-anomalas.png" class="r-stretch quarto-figure-center"><p class="caption">Cadenenas de Markov anómalas</p></section>
<section class="slide level2">

<p>Para analizar la calidad de las muestras generadas por MCMC o HMC se pueden utilizar distintas técnicas:</p>
<ul>
<li><strong>Análisis de la traza</strong>. Consiste en visualizar las trazas de las cadenas de Markov para detectar patrones anómalos, como por ejemplo cadenas que no convergen a la misma distribución, cadenas que no exploran toda la distribución a posteriori o cadenas que se quedan atrapadas en un valor concreto.</li>
<li><strong>Análisis de la autocorrelación</strong>. Consiste en calcular la autocorrelación de las muestras generadas para detectar si los valores de la cadena están muy correlacionados entre sí, lo que indicaría que la muestra no es representativa de la distribución a posteriori.</li>
<li><strong>Análisis de la eficiencia</strong>. Consiste en calcular el número efectivo de muestras independientes que se han generado, lo que permite evaluar la eficiencia del algoritmo de muestreo utilizado.</li>
<li><strong>Análisis de la consistencia</strong>. Consiste en comparando la variabilidad de los valores muestreados en todas las cadenas combinadas con la variabilidad dentro de cada cadena individual.</li>
</ul>
</section>
<section id="análisis-de-la-traza" class="slide level2">
<h2>Análisis de la traza</h2>
<p>Para analizar la distribución de frecuencias de las trazas de las cadenas de Markov podemos utilizar la función <code>mcmc_dens_overlay</code> del paquete <code>bayesplot</code>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong><code>mcmc_dens_overlay()</code></strong></p>
</div>
<div class="callout-content">
<p>Dibuja las distribuciones de frecuenicas de cada cadena de Markov generada.</p>
<p>Parámetros:</p>
<ul>
<li><code>fit</code>: Objeto de clase <code>stanfit</code> con el resultado del muestreo de la distribución a posteriori.</li>
<li><code>pars</code>: Vector de caracteres con los nombres de los parámetros a analizar.</li>
</ul>
</div>
</div>
</div>
<div id="exm-analisis-traza" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 13</strong></span> &nbsp;</p>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href=""></a><span class="fu">mcmc_dens_overlay</span>(posterior_sim, <span class="at">pars =</span> <span class="st">"mu"</span>) <span class="sc">+</span></span>
<span id="cb29-2"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución de frecuencias de las trazas de las cadenas de Markov para μ"</span>,</span>
<span id="cb29-3"><a href=""></a>       <span class="at">x =</span> <span class="st">"Nivel medio de colesterol (μ)"</span>, </span>
<span id="cb29-4"><a href=""></a>       <span class="at">y =</span> <span class="st">"Densidad"</span>) <span class="sc">+</span></span>
<span id="cb29-5"><a href=""></a>  <span class="fu">theme_gray</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-30-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
</div>
</section>
<section id="análisis-de-la-autocorrelación" class="slide level2">
<h2>Análisis de la autocorrelación</h2>
<p>Cada valor de la cadena de Markov depende del anterior, lo que genera una cadena de dependencias</p>
<p><span class="math display">\[
\theta_1 \to \theta_2 \to \theta_3 \to \ldots \to \theta_{n-2} \to \theta_{n-1} \to \theta_n
\]</span></p>
<p>Aunque la dependencia del valor <span class="math inline">\(\theta_n\)</span> del valor anterior <span class="math inline">\(\theta_{n-1}\)</span> es muy fuerte, es de esperar que la dependencia del valor <span class="math inline">\(\theta_{n-i}\)</span> disminuya a medida que <span class="math inline">\(i\)</span> aumenta. Esta dependencia entre los valores de la cadena de Markov se conoce como <em>autocorrelación</em>.</p>
<div id="def-autocorrelación" class="theorem definition">
<p><span class="theorem-title"><strong>Definición 3 (Autocorrelación de una cadena de Markov)</strong></span> Dada una cadena de Markov <span class="math inline">\(\theta_i\)</span> con <span class="math inline">\(i=1, \ldots, n\)</span>, la autocorrelación de orden <span class="math inline">\(k\)</span> se define como</p>
<p><span class="math display">\[
\rho_k = \frac{\text{Cov}(\theta_i, \theta_{i+k})}{\mbox{Var}(\theta_i)}
\]</span> donde <span class="math inline">\(\text{Cov}(\theta_i, \theta_{i+k})\)</span> es la covarianza entre el valor <span class="math inline">\(\theta_i\)</span> y el valor <span class="math inline">\(\theta_{i+k}\)</span>, y <span class="math inline">\(\text{Var}(\theta_i)\)</span> es la varianza de los valores <span class="math inline">\(\theta_i\)</span>.</p>
</div>
</section>
<section class="slide level2">

<p>Para la autocorrelación de las muestras generadas podemos usar la función <code>mcmc_acf</code> del paquete <code>bayesplot</code>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong><code>mcmc_acf()</code></strong></p>
</div>
<div class="callout-content">
<p>Dibuja la función de autocorrelación de las muestras generadas por MCMC o HMC.</p>
<p>Parámetros:</p>
<ul>
<li><code>fit</code>: Objeto de clase <code>stanfit</code> con el resultado del muestreo de la distribución a posteriori.</li>
<li><code>pars</code>: Vector de caracteres con los nombres de los parámetros a analizar.</li>
<li><code>lags</code>: Número de ordenes o retardos para calcular la autocorrelación.</li>
</ul>
</div>
</div>
</div>
<div id="exm-analisis-autocorrelacion" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 14</strong></span> &nbsp;</p>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href=""></a><span class="fu">mcmc_acf</span>(posterior_sim, <span class="at">pars =</span> <span class="st">"mu"</span>, <span class="at">lags =</span> <span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb30-2"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Función de autocorrelación de las muestras generadas por MCMC para μ"</span>,</span>
<span id="cb30-3"><a href=""></a>       <span class="at">x =</span> <span class="st">"Orden o retardo (k)"</span>, </span>
<span id="cb30-4"><a href=""></a>       <span class="at">y =</span> <span class="st">"Autocorrelación (ρ_k)"</span>) <span class="sc">+</span></span>
<span id="cb30-5"><a href=""></a>  <span class="fu">theme_gray</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-31-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
</div>
<p>Se observa que tras 5 iteraciones la autocorrelación es prácticamente nula.</p>
</section>
<section id="análisis-de-eficiencia" class="slide level2">
<h2>Análisis de eficiencia</h2>
<p>La eficiencia de una cadena de Markov generada por MCMC o HMC se puede evaluar calculando el <em>número efectivo de muestras independientes</em> (ESS) que se han generado, que es el número de muestras realmente independientes a las que equivale nuestra de una cadena de Markov autocorrelada.</p>
<p>Podemos analizar la eficiencia de las muestras generadas con la función <code>mcmc_neff</code> del paquete <code>bayesplot</code>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong><code>neff_ratio()</code></strong></p>
</div>
<div class="callout-content">
<p>Calcula la tasa de número efectivo de muestras independientes (ESS) de las cadenas de Markov generadas por MCMC o HMC.</p>
<p>Parámetros:</p>
<ul>
<li><code>fit</code>: Objeto de clase <code>stanfit</code> con el resultado del muestreo de la distribución a posteriori.</li>
<li><code>pars</code>: Vector de caracteres con los nombres de los parámetros a analizar.</li>
</ul>
</div>
</div>
</div>
<div id="exm-analisis-eficiencia" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 15</strong></span> &nbsp;</p>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href=""></a><span class="fu">neff_ratio</span>(posterior_sim, <span class="at">pars =</span> <span class="st">"mu"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3672184</code></pre>
</div>
</div></div>
</div>
<p>En este caso el número efectivo de muestras independientes es un 36.7% de las muestras generadas.</p>
</section>
<section id="análisis-de-consistencia" class="slide level2">
<h2>Análisis de consistencia</h2>
<p>La consistencia de las muestras generadas por MCMC o HMC se puede evaluar comparando la variabilidad de los valores muestreados en todas las cadenas combinadas con la variabilidad dentro de cada cadena individual.</p>
<div id="def-metrica-r-hat" class="theorem definition">
<p><span class="theorem-title"><strong>Definición 4 (Métrica <span class="math inline">\(\hat{R}\)</span>)</strong></span> Dada una colección de cadenas de Markov generadas por un mismo proceso (MCMC o HMC), la métrica <span class="math inline">\(\hat{R}\)</span> se define como la raíz cuadrada de la razón entre la variabilidad total de los valores muestreados en todas las cadenas combinadas y la variabilidad dentro de cada cadena individual.</p>
<p><span class="math display">\[
\hat{R} = \sqrt{\frac{\mbox{Var}_{total}}{\mbox{Var}_{individual}}}
\]</span></p>
</div>
<p>Si la variabilidad entre cadenas es similar a la variabilidad dentro de cada cadena, <span class="math inline">\(\hat{R} \approx 1\)</span>, lo que indica que las cadenas han convergido a la misma distribución a posteriori y las muestras son consistentes.</p>
</section>
<section class="slide level2">

<p>Podemos analizar la consistencia de las muestras generadas con la función <code>rhat</code> del paquete <code>bayesplot</code>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong><code>rhat()</code></strong></p>
</div>
<div class="callout-content">
<p>Calcula la métrica <span class="math inline">\(\hat{R}\)</span> para evaluar la consistencia de las muestras generadas por MCMC o HMC.</p>
<p>Parámetros:</p>
<ul>
<li><code>fit</code>: Objeto de clase <code>stanfit</code> con el resultado del muestreo de la distribución a posteriori.</li>
<li><code>pars</code>: Vector de caracteres con los nombres de los parámetros a analizar.</li>
</ul>
</div>
</div>
</div>
<div id="exm-analisis-consistencia" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 16</strong></span> Veamos cuanto vale la métrica <span class="math inline">\(\hat{R}\)</span> para las cadenas de Markov generadas de la distribución a posteriori del nivel de colesterol medio.</p>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href=""></a><span class="fu">rhat</span>(posterior_sim, <span class="at">pars =</span> <span class="st">"mu"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.000358</code></pre>
</div>
</div></div>
<p>El valor es prácticamente 1, por lo que las 4 cadenas de Markov generadas son consistentes.</p>
</div>
</section>
<section id="dependencia-de-los-resultados-en-la-elección-de-la-distribución-a-priori" class="slide level2">
<h2>Dependencia de los resultados en la elección de la distribución a priori</h2>
<p>Una de las críticas más comunes a la inferencia bayesiana es que los resultados pueden depender de la elección de la distribución a priori, lo que puede introducir un sesgo subjetivo en el análisis.</p>
<p>Los defensores de la Estadística Bayesiana argumentan que la elección de la distribución a priori debe basarse en el conocimiento previo disponible sobre el fenómeno que se está estudiando, y no en una preferencia personal o arbitraria.</p>
<p>No obstante, es importante realizar un análisis de sensibilidad para evaluar cómo varían los resultados a posteriori al cambiar la distribución a priori, lo que permite identificar si los resultados son robustos o si dependen en gran medida de la elección de la distribución a priori.</p>
</section>
<section id="uso-de-distribuciones-a-priori-poco-informativas" class="slide level2">
<h2>Uso de distribuciones a priori poco informativas</h2>
<p>Una forma de minimizar la influencia de la elección de la distribución a priori es utilizar distribuciones a priori poco informativas, que son distribuciones que asignan una probabilidad similar a un amplio rango de valores del parámetro, como por ejemplo la distribución uniforme continua.</p>
<div id="exm-distribucion-priori-poco-informativa" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 17</strong></span> Veamos cómo se ve afectada la distribución a poteriori en el ejemplo de la estimación del nivel de colesterol medio usando una distribución a priori uniforme continua <span class="math inline">\(U(190, 210)\)</span>.</p>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href=""></a><span class="co"># Código del programa de Stan</span></span>
<span id="cb35-2"><a href=""></a>modelo <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb35-3"><a href=""></a><span class="st">data {  </span></span>
<span id="cb35-4"><a href=""></a><span class="st">  int&lt;lower=0&gt; n; // número de personas</span></span>
<span id="cb35-5"><a href=""></a><span class="st">  vector[n] y; // niveles de colesterol</span></span>
<span id="cb35-6"><a href=""></a><span class="st">}</span></span>
<span id="cb35-7"><a href=""></a><span class="st">parameters {</span></span>
<span id="cb35-8"><a href=""></a><span class="st">  real&lt;lower=150, upper=300&gt; mu; // nivel medio de colesterol</span></span>
<span id="cb35-9"><a href=""></a><span class="st">}</span></span>
<span id="cb35-10"><a href=""></a><span class="st">model {</span></span>
<span id="cb35-11"><a href=""></a><span class="st">  y ~ normal(mu, 40) ; // función de verosimilitud</span></span>
<span id="cb35-12"><a href=""></a><span class="st">  mu ~ uniform(150, 300); // distribución a priori</span></span>
<span id="cb35-13"><a href=""></a><span class="st">}</span></span>
<span id="cb35-14"><a href=""></a><span class="st">"</span></span>
<span id="cb35-15"><a href=""></a>posterior_sim <span class="ot">&lt;-</span> <span class="fu">stan</span>(<span class="at">model_code =</span> modelo, </span>
<span id="cb35-16"><a href=""></a>    <span class="at">data =</span> <span class="fu">list</span>(<span class="at">n =</span> <span class="dv">10</span>, <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">230</span>, <span class="dv">226</span>, <span class="dv">245</span>, <span class="dv">228</span>, <span class="dv">232</span>, <span class="dv">235</span>, <span class="dv">232</span>, <span class="dv">244</span>, <span class="dv">251</span>, <span class="dv">247</span>)), </span>
<span id="cb35-17"><a href=""></a>    <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">iter =</span> <span class="dv">5000</span><span class="sc">*</span><span class="dv">2</span>, <span class="at">seed =</span> <span class="dv">123</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href=""></a><span class="fu">mcmc_dens</span>(posterior_sim, <span class="at">pars =</span> <span class="st">"mu"</span>) <span class="sc">+</span></span>
<span id="cb36-2"><a href=""></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm, <span class="at">args =</span> <span class="fu">list</span>(<span class="fl">201.97</span>, <span class="fu">sqrt</span>(<span class="fl">8.52</span>)), <span class="at">color =</span> myred) <span class="sc">+</span></span>
<span id="cb36-3"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución a posteriori de μ"</span>,</span>
<span id="cb36-4"><a href=""></a>       <span class="at">x =</span> <span class="st">"Nivel medio de colesterol (μ)"</span>, <span class="at">y =</span> <span class="st">"Densidad"</span>) <span class="sc">+</span></span>
<span id="cb36-5"><a href=""></a>  <span class="fu">theme_gray</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-35-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
</section>
<section class="slide level2">

<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href=""></a>posterior_sim <span class="ot">&lt;-</span> <span class="fu">stan</span>(<span class="at">model_code =</span> modelo, </span>
<span id="cb37-2"><a href=""></a>    <span class="at">data =</span> <span class="fu">list</span>(<span class="at">n =</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">2</span>, <span class="at">y =</span> <span class="fu">rnorm</span>(<span class="dv">10</span><span class="sc">^</span><span class="dv">2</span>, <span class="at">mean =</span> <span class="fl">201.97</span>, <span class="at">sd =</span> <span class="fu">sqrt</span>(<span class="fl">8.52</span>))), </span>
<span id="cb37-3"><a href=""></a>    <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">iter =</span> <span class="dv">5000</span><span class="sc">*</span><span class="dv">2</span>, <span class="at">seed =</span> <span class="dv">123</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><br></p>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href=""></a><span class="fu">mcmc_dens</span>(posterior_sim, <span class="at">pars =</span> <span class="st">"mu"</span>) <span class="sc">+</span></span>
<span id="cb38-2"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución a posteriori de μ"</span>,</span>
<span id="cb38-3"><a href=""></a>       <span class="at">x =</span> <span class="st">"Nivel medio de colesterol (μ)"</span>, <span class="at">y =</span> <span class="st">"Densidad"</span>) <span class="sc">+</span></span>
<span id="cb38-4"><a href=""></a>  <span class="fu">theme_gray</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="02-regla-bayes_files/figure-revealjs/unnamed-chunk-37-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
<div class="centered">
<p><em>Para muestras pequeñas puede haber bastante discrepancia entre las distribuciones posteriores generadas por distintas distribuciones a priori, pero esa diferencia se disipa a medida que tenemos más datos.</em></p>
</div>
</section>
<section id="elección-de-la-distribución-a-priori.-tipos-de-distribuciones-a-priori." class="slide level2">
<h2>Elección de la distribución a priori. Tipos de distribuciones a priori.</h2>
<p>Aunque ya hemos visto que la elección de la distribución a priori no es relevante cuando tenemos muchos datos, para muestras pequeñas, una eleción adecuada de la distribución a priori es determinante.</p>
<ul>
<li><p><strong>No informativas</strong>. Asignan la misma plausibilidad a todos los valores del parámetro, incluso cuando hay valores del parámetro que no tienen sentido.</p></li>
<li><p><strong>Poco informativas</strong>. Asignan una probabilidad similar a un amplio rango de valores del parámetro, pero descartan valores que no tienen sentido.</p></li>
<li></li>
<li><p><strong>Informativas</strong>. Reflejan un conocimiento previo sólido sobre el parámetro de interés, lo que puede ser útil para mejorar la precisión de las estimaciones cuando se dispone de poca información en los datos.</p></li>
</ul>
</section>
<section id="distribuciones-a-priori-no-informativas" class="slide level2">
<h2>Distribuciones a priori no informativas</h2>
<p>Una distribución a priori no informativa asigna la misma plausibilidad al todo el rango de valores del parámetro.</p>
<p>El caso más extremo es modelo uniforme impropio <span class="math inline">\(f(\theta) \propto 1\)</span>, que no es una distribución de probabilidad porque no integra a 1, pero produce distribuciones a posteriori adecuadas con suficientes datos.</p>
<p><strong>¿Cuándo usarla?</strong> Se puede usar cuando no tenemos información previa y los datos son abundantes.</p>
<p><strong>¿Cuándo no usarla?:</strong> No debería usarse con muestras pequeñas, porque el posterior puede ser inestable o producir estimaciones absurdas.</p>
<div id="exm-distribucion-priori-no-informativa" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 18</strong></span> Para estimar la tensión arterial sistólica media de una población se utiliza un modelo uniforme <span class="math inline">\(f(\mu) \propto 1\)</span> que asigna la misma plausibilidad a cualquier valor de <span class="math inline">\(\mu&gt;0\)</span></p>
</div>
</section>
<section id="distribuciones-a-priori-poco-informativas" class="slide level2">
<h2>Distribuciones a priori poco informativas</h2>
<p>Una distribución a priori poco informativa asigna una probabilidad similar a un amplio rango de valores del parámetro, pero descarta valores que no tienen sentido.</p>
<p>Suele utilizarse una distribución uniforme continua restringiendo el rango de valores del parámetro a aquellos que son plausibles, o una distribución Normal con una desviación estándar grande para reflejar la incertidumbre sobre el valor del parámetro.</p>
<p><strong>¿Cuándo usarla?</strong> Se puede usar cuando no tenemos información previa pero queremos evitar que el posterior sea inestable o produzca estimaciones absurdas con muestras pequeñas. Es la opción más habitual cuando no hay información sólida sobre la incertidumbre del parámetro.</p>
<p><strong>¿Cuándo no usarla?:</strong> No debería usarse cuando tenemos información previa sólida sobre el parámetro de interés, porque no aprovecha esa información para mejorar la precisión de las estimaciones, especialmente si tenemos pocos datos.</p>
<div id="exm-distribucion-priori-poco-informativa" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 19</strong></span> Para estimar la tensión arterial sistólica media de una población se utiliza un modelo uniforme <span class="math inline">\(\mu \sim U(70, 200)\)</span> que asigna la misma plausibilidad a cualquier valor de <span class="math inline">\(\mu\)</span> entre 70 y 200 mmHg, pero descarta valores menores de 80 o mayores de 200 mmHg que no tienen sentido.</p>
</div>
</section>
<section id="distribuciones-a-priori-informativas" class="slide level2">
<h2>Distribuciones a priori informativas</h2>
<p>Una distribución a priori informativa refleja un conocimiento previo sólido sobre el parámetro de interés (resultados de estudios anteriores, valores de referencia clínica, opinión de expertos), para modelizar su incertidumbre, lo que puede ser útil para mejorar la precisión de las estimaciones cuando se dispone de poca información en los datos.</p>
<p>Suelen utilizarse distribuciones conjugadas de las distribuciones de los datos.</p>
<p><strong>¿Cuándo usarla?</strong> Cuando tenemos evidencia previa sólida (metaanálisis, registros históricos, valores fisiológicos bien establecidos). Siempre debe documentarse y justificarse.</p>
<p><strong>¿Cuándo no usarla?</strong> No debería usarse cuando no tenemos información previa sólida sobre el parámetro de interés, porque puede introducir un sesgo subjetivo en el análisis y producir estimaciones poco fiables, especialmente si tenemos pocos datos.</p>
<div id="exm-distribucion-priori-informativa" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 20</strong></span> Para estimar la tensión arterial sistólica media de una población se utiliza un modelo Normal <span class="math inline">\(\mu \sim N(120, 15^2)\)</span> que refleja el conocimiento previo sobre la tensión arterial sistólica media en poblaciones similares, con una media de 120 mmHg y una desviación estándar de 15 mmHg para reflejar la incertidumbre sobre ese valor.</p>
</div>
</section>
<section id="distribuciones-a-priori-recomendadas" class="slide level2">
<h2>Distribuciones a priori recomendadas</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Situación</th>
<th>Prior recomendado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Media poblacional</td>
<td><code>normal(valor_referencia, incertidumbre)</code></td>
</tr>
<tr class="even">
<td>Desviación típica</td>
<td><code>half_t(3, 0, 1)</code> o <code>exponential(1)</code></td>
</tr>
<tr class="odd">
<td>Proporción sin información previa</td>
<td><code>beta(1, 1)</code> o <code>beta(0.5, 0.5)</code></td>
</tr>
<tr class="even">
<td>Proporción con información previa</td>
<td><code>beta()</code> calibrada con la media y la varianza observadas</td>
</tr>
<tr class="odd">
<td>Coeficientes de regresión (datos estandarizados)</td>
<td><code>normal(0, 1)</code></td>
</tr>
<tr class="even">
<td>Coeficientes de regresión (datos sin estandarizar)</td>
<td><code>normal(0, 2.5)</code> — recomendación de Gelman</td>
</tr>
<tr class="odd">
<td>Muchos predictores, selección de variables</td>
<td><code>horseshoe(df=1)</code></td>
</tr>
<tr class="even">
<td>Regresión logística, coeficientes</td>
<td><code>normal(0, 2.5)</code> o <code>student_t(7, 0, 2.5)</code></td>
</tr>
</tbody>
</table>
</section>
<section id="distribuciones-a-priori-en-epidemiología" class="slide level2">
<h2>Distribuciones a priori en Epidemiología</h2>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Parámetro</th>
<th>Distribución prior</th>
<th>Parámetros habituales</th>
<th>Conjugada con</th>
<th>Aplicación en epidemiología</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Prevalencia, proporción</td>
<td>Beta(α, β)</td>
<td>Beta(1,1) uniforme · Beta(0.5,0.5) Jeffreys · Beta(2,5) informativa</td>
<td>Binomial / Bernoulli</td>
<td>Prevalencia de enfermedad, tasa de ataque, sensibilidad/especificidad de test</td>
</tr>
<tr class="even">
<td>Vector de proporciones</td>
<td>Dirichlet(α₁,…,αₖ)</td>
<td>Dir(1,…,1) uniforme · Dir(0.5,…,0.5) Jeffreys</td>
<td>Multinomial / Categórica</td>
<td>Distribución de serotipos, variantes, grupos de riesgo</td>
</tr>
<tr class="odd">
<td>Tasa de incidencia, tasa de mortalidad</td>
<td>Gamma(α, β)</td>
<td>Gamma(0.01, 0.01) difusa · Gamma(2, 0.5) débil</td>
<td>Poisson / Exponencial</td>
<td>Incidencia de casos por 100.000 hab., mortalidad, tasa de hospitalización</td>
</tr>
<tr class="even">
<td>Número reproductivo R₀, R(t)</td>
<td>Gamma(α, β)</td>
<td>Gamma(1, 0.2) · Gamma(2, 0.5)</td>
<td>Poisson (ecuación renovación)</td>
<td>Transmisibilidad de enfermedades infecciosas, estimación de R(t)</td>
</tr>
<tr class="odd">
<td>Media poblacional (tensión arterial, colesterol, glucemia)</td>
<td>Normal(μ₀, σ₀²)</td>
<td>N(valor referencia, σ amplio)</td>
<td>Normal (σ² conocida)</td>
<td>Estimación de la media de biomarcadores clínicos</td>
</tr>
<tr class="even">
<td>Media y varianza poblacional</td>
<td>Normal-Inv-Gamma(μ₀,λ,α,β)</td>
<td>Hiperparámetros basados en valores de referencia</td>
<td>Normal completa</td>
<td>Biomarcadores con media y varianza desconocidas</td>
</tr>
<tr class="odd">
<td>Log-odds, coeficiente de regresión logística</td>
<td>Normal(0, σ²)</td>
<td>N(0, 2.5²) Gelman · N(0, 1) estandarizado</td>
<td>— (MCMC)</td>
<td>Factores de riesgo en estudios de casos y controles, OR ajustado</td>
</tr>
<tr class="even">
<td>Log-hazard ratio, coeficiente de supervivencia</td>
<td>Normal(0, σ²)</td>
<td>N(0, 2.5²)</td>
<td>— (MCMC)</td>
<td>Análisis de supervivencia: tiempo hasta evento, censura</td>
</tr>
<tr class="odd">
<td>Desviación típica, varianza residual</td>
<td>half-Normal(0, σ) · half-t(ν,0,σ)</td>
<td>half-N(0,1) · half-t(3,0,1) Gelman</td>
<td>— (MCMC)</td>
<td>Variabilidad residual en regresión, modelos mixtos</td>
</tr>
<tr class="even">
<td>Varianza de efectos aleatorios</td>
<td>half-t(ν, 0, σ) · Gamma-Inversa(α,β)</td>
<td>half-t(3,0,1) recomendado · IG(0.01,0.01) clásico</td>
<td>— (MCMC)</td>
<td>Heterogeneidad entre centros, hospitales, regiones en modelos jerárquicos</td>
</tr>
<tr class="odd">
<td>Correlación entre efectos aleatorios</td>
<td>LKJ(η)</td>
<td>LKJ(1) uniforme · LKJ(2) concentrado</td>
<td>— (MCMC)</td>
<td>Correlación entre interceptos y pendientes en modelos mixtos</td>
</tr>
<tr class="even">
<td>Eficacia vacunal (escala log-OR)</td>
<td>Normal(0, σ²) · Beta (escala probabilidad)</td>
<td>N(log(0.5), 0.5²) informativa</td>
<td>— (MCMC)</td>
<td>Ensayos clínicos de vacunas, estudios de efectividad vacunal</td>
</tr>
<tr class="odd">
<td>Sensibilidad y especificidad de test</td>
<td>Beta(α, β)</td>
<td>Beta(18,2) Se≈90% · Beta(38,2) Sp≈95%</td>
<td>Binomial</td>
<td>Evaluación de pruebas diagnósticas, modelos de misclasificación</td>
</tr>
<tr class="even">
<td>Coeficientes en modelos con muchas variables</td>
<td>Horseshoe(df) · Normal(0,1)</td>
<td>horseshoe(df=1) · N(0,1) estandarizado</td>
<td>— (MCMC)</td>
<td>Selección de factores de riesgo, estudios de exposición múltiple</td>
</tr>
<tr class="odd">
<td>Parámetro de forma Weibull (supervivencia)</td>
<td>Gamma(α, β) · half-Normal</td>
<td>Gamma(1,1) · half-N(0,1)</td>
<td>— (MCMC)</td>
<td>Modelos paramétricos de supervivencia, tiempo hasta recaída o muerte</td>
</tr>
<tr class="even">
<td>Fracción atribuible poblacional</td>
<td>Beta(α, β)</td>
<td>Beta(1,1) uniforme · informativa según estudios previos</td>
<td>Binomial</td>
<td>Proporción de casos atribuibles a un factor de riesgo modificable</td>
</tr>
</tbody>
</table>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="img/logos/sticker-estadistica-bayesiana-r.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="02-regla-bayes_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="02-regla-bayes_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="02-regla-bayes_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="02-regla-bayes_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="02-regla-bayes_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="02-regla-bayes_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="02-regla-bayes_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="02-regla-bayes_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="02-regla-bayes_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="02-regla-bayes_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiado");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiado");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>